src/css/core.css
src/css/theme-dark.css
src/css/theme-fresh.css
src/gridOptionsWrapper.js
src/groupCreator.js
src/rowController.js
src/rowRenderer.js
src/selectionController.js
src/test.js
src/utils.js
test.html
website/angular-grid-grouping/example3.js
website/angular-grid-grouping/example5.js
website/angular-grid-grouping/groupingFooters.html
website/angular-grid-grouping/groupingFooters.js
website/angular-grid-grouping/index.php
website/angular-grid-selection/groupSelection.html
website/angular-grid-selection/groupSelection.js
website/angular-grid-selection/index.php
website/dist/angularGrid-latest.js
website/example-account-report/account.js
website/example.html
website/example.js
website/why-the-world-needed-another-angularjs-grid/index.html

Now it's possible to include a footer in your groups.

Group footers

---

src/angularGrid.js
src/colModel.js
src/gridOptionsWrapper.js
src/rowRenderer.js
website/angular-grid-column-definitions/index.php
website/angular-grid-datasource/index.php
website/dist/angularGrid-1.1.js
website/dist/angularGrid-latest.js
website/documentation.php
website/example.js

added tab navigation

---

src/filter/numberFilter.js

NumberFilter didn't work correctly, when value in a table was 0.

Fixed filtering zero numbers.

---

src/angularGrid.js
src/columnController.js
src/filter/setFilterModel.js
src/selectionController.js
website/angular-grid-filtering/example1.js
website/angular-grid-filtering/index.php
website/angular-grid-resizing/example2.html
website/angular-grid-resizing/example2.js
website/angular-grid-resizing/index.php
website/dist/angularGrid-latest.js

Selection API and autoFitColumns

Selection API and autoFitColumns

---

src/angularGrid.js

Fix to allow api.onNewDatasource

---

src/js/inMemoryRowController.js

https://github.com/ceolter/angular-grid/issues/29

fix for issue 29

---

docs/angular-grid-cell-rendering/index.php
docs/angular-grid-cell-template/ageTemplate.html
docs/angular-grid-cell-template/example1.html
docs/angular-grid-cell-template/example1.js
docs/angular-grid-cell-template/index.php
docs/angular-grid-column-definitions/index.php
docs/angular-grid-filtering/index.php
docs/documentation_header.php
docs/traige.txt
src/js/rowRenderer.js
src/js/templateService.js

https://github.com/ceolter/angular-grid/issues/90

fixed issue 90

---

package.json

Can you add this in so I can properly `require('angular-grid')` using browserify?

Package.json update for browserify compatibility

---

package.json

Switched main entry in package.json to minified dist

---

docs/angular-grid-grid-options/index.php
src/ts/gridOptions.ts
src/ts/gridOptionsWrapper.ts
src/ts/headerRenderer.ts
src/ts/toolPanel/columnSelectionPanel.ts
src/ts/widgets/agList.ts

Added columnResized, columnVisibilityChanged and columnOrderChanged callbacks to gridOptions.

294 - Column change callbacks on gridOptions.

---

src/ts/filter/setFilter.ts
src/ts/filter/setFilterModel.ts

I changed SetFilter and SetFilterModel to support filtering when field is array.

SetFilter for arrays

---

docs/angular-grid-grouping/example6.html
docs/angular-grid-grouping/example6.js
docs/angular-grid-grouping/index.php
gulpfile.js
src/ts/columnController.ts
src/ts/gridOptions.ts
src/ts/gridOptionsWrapper.ts
src/ts/rowControllers/inMemoryRowController.ts

I also updated the docs accordingly.
I didn't include the docs/dist/angular-grid.js since you said that you will generate this yourself, but you'll need to generate it to test the example that I added into the documentation.

Adding the `suppressGroupRow` option

---

docs/angular-grid-api/index.php
docs/angular-grid-column-api/index.php
docs/javascript-grid-callbacks/index.php
docs/javascript-grid-events/index.php
docs/javascript-grid-properties/index.php

minor changes to match case sensitiveness with real filename in docs.

fix(docs): make same case with filename

---

src/ts/rowControllers/paginationController.ts

style.visibility = null not always works on all IE, but = "" works

fix(pagination): visibility = null does not work on some IE

---

src/ts/rowControllers/paginationController.ts

Pagination no longer submits enclosing forms

---

src/ts/headerRendering/renderedHeaderCell.ts

This PR should fix the issue on http://www.ag-grid.com/forum/showthread.php?tid=2921

fix: `this` scope issue in headerClass

---

docs/angular-grid-icons/index.php

Small typo

---

src/ts/csvCreator.ts

- Include special UTF-8 marker so Excel recognizes non-ASCII characters.
- Allow user to specify a custom column separator.

Small changes in csv export to smoothen usage in Excel

---

src/ts/rendering/renderedCell.ts

Hi,
this remove a useless log recently added

remove log for context menu

---

src/ts/rowControllers/virtualPageRowController.ts

Fix bug in virtual page row

---

src/ts/columnController/balancedColumnTreeBuilder.ts
src/ts/columnController/columnController.ts
src/ts/columnController/columnUtils.ts
src/ts/entities/rowNode.ts
src/ts/selectionController.ts

Across multiple files deptFirst was written instead of depthFirst. Since the typos are in a public API, feel free to ignore this pull request.
Thanks

Fix typo in depthFirst across various files

---

packages/ag-grid-docs/src/angular-getting-started/index.php
packages/ag-grid-docs/src/best-angular-2-data-grid/index.php
packages/ag-grid-docs/src/javascript-getting-started/index.php

SEO - Angular Landing Page

---

community-modules/core/src/styles/ag-theme-base/sass/parts/_menu.scss
community-modules/core/src/ts/focusController.ts
community-modules/core/src/ts/grid.ts
community-modules/core/src/ts/gridApi.ts
community-modules/core/src/ts/gridCore.ts
community-modules/core/src/ts/gridPanel/gridPanel.ts
community-modules/core/src/ts/gridPanel/navigationService.ts
community-modules/core/src/ts/gridPanel/rowDragFeature.ts
community-modules/core/src/ts/headerRendering/header/headerComp.ts
community-modules/core/src/ts/headerRendering/standardMenu.ts
community-modules/core/src/ts/interfaces/iContextMenuFactory.ts
community-modules/core/src/ts/layout/tabbedLayout.ts
community-modules/core/src/ts/main.ts
community-modules/core/src/ts/rendering/beans.ts
community-modules/core/src/ts/rendering/cellComp.ts
community-modules/core/src/ts/rendering/checkboxSelectionComponent.ts
community-modules/core/src/ts/rendering/rowComp.ts
community-modules/core/src/ts/rendering/rowDragComp.ts
community-modules/core/src/ts/rendering/rowRenderer.ts
community-modules/core/src/ts/undoRedo/undoRedoService.ts
enterprise-modules/clipboard/src/clipboard/clipboardService.ts
enterprise-modules/column-tool-panel/src/columnToolPanel/primaryColsListPanel.ts
enterprise-modules/column-tool-panel/src/columnToolPanel/primaryColsPanel.ts
enterprise-modules/menu/src/menu/contextMenu.ts
enterprise-modules/menu/src/menu/enterpriseMenu.ts
enterprise-modules/menu/src/menu/menuItemComponent.ts
enterprise-modules/menu/src/menu/menuList.ts

AG-2025 - added keyboard navigation to MenuLists and TabbedLayout

Context menu enhancement

---

community-modules/core/src/ts/context/context.ts
community-modules/core/src/ts/utils/function.ts
community-modules/core/src/ts/widgets/componentAnnotations.ts

https://ag-grid.zendesk.com/agent/tickets/12665

AG-4310 Ensure function name is extracted correctly for all browsers

---

community-modules/angular/README.md
community-modules/angular/projects/ag-grid-angular/README.md

Correction to #3928 
Noticed when following the directions and copying commands that there was a misspelling. So instead of ignoring it, I would like to fix it. :D 
@gportela85

Fix misspellings of community

---

community-modules/core/src/ts/entities/colDef.ts
community-modules/core/src/ts/focusController.ts
community-modules/core/src/ts/gridCore.ts
community-modules/core/src/ts/layout/tabbedLayout.ts
community-modules/core/src/ts/utils/keyboard.ts
community-modules/core/src/ts/widgets/popupService.ts

https://ag-grid.atlassian.net/browse/AG-4707

AG-4707 - fixed editors less responsive with multiple instances of the grid

---

charts-packages/ag-charts-angular/projects/ag-charts-angular/package.json

I think this is a causing the issue: ! Invalid tag name "^>=8.0.0":
Can we please release this new change.
i opened the issue in https://github.com/ag-grid/ag-grid/issues/4659

Update package.json | Invalid Tagname i guess | causing install issue

---

grid-packages/ag-grid-docs/example-generator-documentation.js

Fixes the new Plunker `package.json` support for Charts examples :tada:

AG-6577 - Add support for Charts in Plunker package.json.

---

community-modules/core/src/ts/gridBodyComp/navigationService.ts
community-modules/core/src/ts/rendering/cell/cellCtrl.ts
community-modules/core/src/ts/utils/function.ts

This fixes https://ag-grid.atlassian.net/browse/AG-6611 and also adds a better logic for https://ag-grid.atlassian.net/browse/AG-2733

AG-6611 - fixed PageDown and PageUp issues with AutoHeight

---

community-modules/core/src/ts/rendering/overlays/overlayWrapperComponent.ts

https://ag-grid.atlassian.net/browse/AG-6524

AG-6524 - fixed loadingOverlay being removed when columns are added

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/api.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/index.md

https://ag-grid.atlassian.net/browse/AG-6207
Tweak Chart axis tick related documentation after recent tick calculation changes in #5161.

AG-6207 - Update Chart tick-related documentation.

---

charts-packages/ag-charts-community/src/chart/mapping/prepareSeries.test.ts
charts-packages/ag-charts-community/src/chart/mapping/prepareSeries.ts

AG-5740 - Make Charts series option reducers more declarative.

---

community-modules/core/src/ts/headerRendering/cells/column/headerComp.ts
community-modules/core/src/ts/headerRendering/cells/column/sortIndicatorComp.ts
grid-packages/ag-grid-docs/documentation/doc-pages/column-headers/examples/header-template/main.ts

https://ag-grid.atlassian.net/browse/AG-6973

AG-6973 - fixed issue with sortIcons not working with custom templates

---

charts-packages/ag-charts-community/src/chart/chart.ts

https://ag-grid.atlassian.net/browse/AG-6979
Fixes tooltip rendering in Firefox.
Whilst debugging, it appeared that `offsetX` and `offsetY` are both `0` in `Chart.handleTooltip()`, but only in FIrefox. This change ensures we snapshot these properties so they are the correct values when `Chart.handleTooltip()` is invoked.

AG-6979 - Fix tooltip MouseEvent dropping offset{X,Y} in Firefox.

---

community-modules/vue3/src/AgGridColumn.ts

Fix declarative columns for vue3

fix(vue3): declarative columns fix

---

charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts

PR for: https://ag-grid.atlassian.net/browse/AG-5320
Try to stick to the configured `binCount`.

AG-5320 - Fix bins calculation when `binCount` is specified

---

charts-packages/ag-charts-community/src/chart/chart.ts
charts-packages/ag-charts-community/src/chart/test/utils.ts

Will be useful outside of the test function

AG-4460 - Move wait for chart render into chart class

---

charts-packages/ag-charts-community/src/chart/agChartOptions.ts
charts-packages/ag-charts-community/src/chart/series/hierarchy/treemapSeries.ts
community-modules/core/src/ts/interfaces/iAgChartOptions.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-treemap-series/examples/org-chart/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-treemap-series/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json

https://ag-grid.atlassian.net/browse/AG-5220
Ability to customise TreeMap tiles' fill and stroke styles via a formatter function.

AG-5220 - Treemap formatter

---

grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-editor/examples/component-editor-2/numericEditor_reactFunctional.jsx
grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-editor/examples/component-editor-2/numericEditor_reactFunctional.tsx

- Fixes an issue related to navigation only working in the left direction when a field is being edited

FIX: FIXES ISSUE WITH KEYBOARD NAVIGATION

---

charts-packages/ag-charts-community/src/chart/agChartOptions.ts
community-modules/core/src/ts/interfaces/iAgChartOptions.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-7200
JsDocs updates

AG-7200 - Category axis JsDocs updates

---

charts-packages/ag-charts-community/src/axis.ts
charts-packages/ag-charts-community/src/chart/axis/numberAxis.ts
charts-packages/ag-charts-community/src/chart/axis/timeAxis.ts
charts-packages/ag-charts-community/src/chart/crossline/crossLine.ts
charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
charts-packages/ag-charts-community/src/chart/series/seriesMarker.ts
charts-packages/ag-charts-community/src/util/validation.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-6586.
Add more detailed and useful console warning messages to the chart options validation

AG-6586 - Add more detailed charts options validation messages

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/simple-doughnut/main.ts

Add labels to Doughnut example. The thumbnail generation didn't work.

AG-7292 Update Doughnut example in the Gallery

---

grid-packages/ag-grid-docs/documentation/src/pages/components/assets/pages/_license-pricing.scss
grid-packages/ag-grid-docs/documentation/src/pages/license-pricing.tsx

AG-7308 Style pricing page

---

community-modules/core/src/ts/interfaces/iChartOptions.ts
enterprise-modules/charts/src/charts/chartComp/menu/settings/miniChartsContainer.ts
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json

* Replace `CHART_TYPE_KEYS` with `ChartGroupsDef`
* Remove `PartialChartGroupsDef`
* Add comments to Chart Tool Panel types

AG-5026 - Simplify Chart Tool Panel types

---

charts-packages/ag-charts-community/src/chart/agChartOptions.ts
charts-packages/ag-charts-community/src/chart/series/polar/pieSeries.ts
community-modules/core/src/ts/interfaces/iAgChartOptions.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json

- Run formatter during the data processing stage.
- Fix tooltip formatted color mismatch.
- Add `fillOpacity` to formatter return type.

AG-7233 Fix Legend/Tooltip formatter color mismatch

---

charts-packages/ag-charts-community/tools/dev-server/transpiler.js

Emit source files after a change, so that they show up in the dev tools correctly.

Fixed charts dev server sourcemaps after update

---

charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

Provide a correct reference to a datum object for node click handler and tooltip renderer.

AG-7224 Datum ref in Line tooltip & click handler

---

grid-packages/ag-grid-docs/documentation/doc-pages/keyboard-navigation/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/detail-cell-renderer.component_angular.ts
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/detailCellRenderer_react.jsx
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/detailCellRenderer_reactFunctional.jsx
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/detailCellRenderer_reactFunctional.tsx
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/detailCellRenderer_typescript.ts
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/detailCellRenderer_vue.js
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/examples/custom-detail-keyboard-navigation/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/master-detail-custom-detail/index.md

* Add Custom Detail Keyboard Navigation docs (`/master-detail-custom-detail/#keyboard-navigation`)
* Add link from Interactivity > Keyboard Navigation docs to Custom Detail Keyboard Navigation docs (`/keyboard-navigation/#custom-master-detail-navigation`)

AG-5923 - Add Custom Detail Keyboard Navigation docs

---

charts-packages/ag-charts-community/src/axis.ts
charts-packages/ag-charts-community/src/chart/navigator/navigator.ts

Compare visible labels and rotation angles when dragging the navigator.

AG-7297 Recalculate layout when navigating X-axis

---

charts-packages/ag-charts-community/src/chart/agChartV2.ts
charts-packages/ag-charts-community/src/chart/chart.ts
charts-packages/ag-charts-community/src/chart/mapping/prepare.ts
charts-packages/ag-charts-community/src/util/__snapshots__/json.test.ts.snap
charts-packages/ag-charts-community/src/util/json.test.ts
charts-packages/ag-charts-community/src/util/json.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

- Avoid deep data cloning.
- Prevent unnecessary re-renderings.

AG-7387 Improve data handling performance

---

charts-packages/ag-charts-community/src/scale/timeScale.test.ts
charts-packages/ag-charts-community/src/scale/timeScale.ts

https://ag-grid.atlassian.net/browse/AG-7374
Attempts to fix the order of date elements in the `TimeAxis.defaultFormatter()`.

AG-7374 - Fix time axis format order.

---

community-modules/core/src/ts/filter/provided/providedFilter.ts

* Make `Apply` filter button a submit button in a form to allow for `Enter` key to work in the form

AG-5550 - Make Apply filter button a submit button in a form

---

charts-packages/ag-charts-community/src/chart/chart.test.ts
charts-packages/ag-charts-community/src/chart/chart.ts
charts-packages/ag-charts-community/src/chart/test/utils.ts
charts-packages/ag-charts-community/src/util/sanitize.ts

Fixed node click events and highlighting when tooltip is disabled.

AG-7089 Fixed click and highlight when tooltip off

---

community-modules/core/src/ts/entities/iCallbackParams.ts
community-modules/core/src/ts/gridBodyComp/rowContainer/rowContainerComp.ts
community-modules/core/src/ts/gridBodyComp/rowContainer/rowContainerCtrl.ts
community-modules/core/src/ts/gridBodyComp/rowContainer/setPinnedLeftWidthFeature.ts
community-modules/core/src/ts/gridBodyComp/rowContainer/setPinnedRightWidthFeature.ts
community-modules/core/src/ts/gridComp/gridComp.ts
community-modules/core/src/ts/headerRendering/rowContainer/headerRowContainerCtrl.ts
community-modules/core/src/ts/pagination/paginationAutoPageSizeService.ts
community-modules/core/src/ts/rendering/row/rowComp.ts
community-modules/core/src/ts/rendering/row/rowCtrl.ts
community-modules/react/src/reactUi/rows/rowComp.tsx
community-modules/react/src/reactUi/rows/rowContainerComp.tsx
community-modules/solid/src/grid/rows/rowComp.tsx
community-modules/solid/src/grid/rows/rowContainerComp.tsx
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
grid-packages/ag-grid-react/src/reactUi/rows/rowComp.tsx
grid-packages/ag-grid-react/src/reactUi/rows/rowContainerComp.tsx
grid-packages/ag-grid-solid/src/grid/rows/rowComp.tsx
grid-packages/ag-grid-solid/src/grid/rows/rowContainerComp.tsx

https://ag-grid.atlassian.net/browse/AG-7439

AG-7439 - only render rows in pinned column section when there are pinned columns

---

community-modules/core/src/ts/gridBodyComp/rowContainer/rowContainerCtrl.ts
community-modules/core/src/ts/headerRendering/row/headerRowComp.ts
community-modules/core/src/ts/rendering/row/rowCssClassCalculator.ts
community-modules/core/src/ts/rendering/row/rowCtrl.ts
community-modules/core/src/ts/rendering/rowRenderer.ts
community-modules/react/src/reactUi/header/headerRowComp.tsx
community-modules/solid/src/grid/header/headerRowComp.tsx
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
grid-packages/ag-grid-react/src/reactUi/header/headerRowComp.tsx
grid-packages/ag-grid-solid/src/grid/header/headerRowComp.tsx

https://ag-grid.atlassian.net/browse/AG-7504

AG-7504 - fixed infinite loop with print layout + autoHeight

---

README.md

Remove duplicated slash in readme

---

charts-packages/ag-charts-community/src/chart/agChartOptions.ts
charts-packages/ag-charts-community/src/chart/agChartV2.ts
community-modules/all-modules/generate-code-reference-files.js
community-modules/core/src/ts/interfaces/iAgChartOptions.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json

https://ag-grid.atlassian.net/browse/AG-7546
Review fixes for the new `AgChart.updateDelta()` factory update method.

AG-7546 - Review fixes for AgChart.updateDelta() changes.

---

charts-packages/ag-charts-community/src/chart/agChartOptions.ts
charts-packages/ag-charts-community/src/chart/series/hierarchy/treemapSeries.ts
charts-packages/ag-charts-community/src/chart/themes/chartTheme.ts
charts-packages/ag-charts-community/src/chart/themes/darkTheme.ts
community-modules/core/src/ts/interfaces/iAgChartOptions.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-treemap-series/examples/stock-market-index/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json

- Add value label formatter (or key).
- Stop getting value text from colorKey.
- Remove series.labels.color label config.

AG-7588 Treemap value label formatter

---

charts-packages/ag-charts-community/src/chart/cartesianChart.test.ts
charts-packages/ag-charts-community/src/chart/chart.test.ts
charts-packages/ag-charts-community/src/chart/chart.ts
charts-packages/ag-charts-community/src/chart/hierarchyChart.test.ts
charts-packages/ag-charts-community/src/chart/interaction/baseManager.ts
charts-packages/ag-charts-community/src/chart/interaction/highlightManager.ts
charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
charts-packages/ag-charts-community/src/chart/legend.ts
charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
charts-packages/ag-charts-community/src/chart/series/hierarchy/treemapSeries.ts
charts-packages/ag-charts-community/src/chart/series/polar/pieSeries.ts
charts-packages/ag-charts-community/src/chart/series/polar/polarSeries.ts
charts-packages/ag-charts-community/src/chart/series/series.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

https://ag-grid.atlassian.net/browse/AG-7679
Introduces `HighlightManager` to manage current highlighted series/datum state, and simplify handling of 'clearing' the highlight from the dependents.

AG-7679 - Refactor chart series highlight management.

---

charts-packages/ag-charts-community/src/axis.ts

https://ag-grid.atlassian.net/browse/AG-7685

AG-7685 Fix hiding ticks after update

---

charts-packages/ag-charts-community/src/axis.ts
charts-packages/ag-charts-community/src/chart/agChartOptions.ts
charts-packages/ag-charts-community/src/chart/mapping/__snapshots__/prepare.test.ts.snap
charts-packages/ag-charts-community/src/chart/themes/chartTheme.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-6834
Added option to disable axis label collision avoidance

AG-6834 - Allow disabling axis label collision prevention

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/index.md

PR for https://ag-grid.atlassian.net/browse/AG-6424 
docs changes

AG-6424 - Legend events docs changes

---

charts-packages/ag-charts-community/src/axis.ts
charts-packages/ag-charts-community/src/chart/agChartOptions.ts
charts-packages/ag-charts-community/src/chart/mapping/__snapshots__/prepare.test.ts.snap
charts-packages/ag-charts-community/src/chart/themes/chartTheme.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

Pr for https://ag-grid.atlassian.net/browse/AG-7744
Rename 
`autoCollisionRemoval` to `avoidLabelCollisions`
`minGap` to `minLabelSpacing`

AG-7744 - Rename axis label auto removal options properties

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/market-index-treemap/data.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/market-index-treemap/main.ts

- Access for the Treemap node datum has been removed.
- Use Hex colors for Treemap overview example.

AG-7754 Color string values for Treemap example

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/index.md

PR for https://ag-grid.atlassian.net/browse/AG-7762
Updated docs

AG-7762 - Update charts legend `maxWidth`, `maxHeight` documentation

---

charts-packages/ag-charts-community/src/chart/pagination/pagination.ts

https://ag-grid.atlassian.net/browse/AG-7786
Fixes pagination component highlight after a page change (highlight is now correctly maintained).

AG-7786 - Fix pagination highlight on page change.

---

charts-packages/ag-charts-community/src/scene/intersection.ts
charts-packages/ag-charts-community/src/scene/path2D.ts

This PR solves the regression after replacing fake cubic arcs with actual arcs. It is the first step in solving the actual point click issue.

AG-7461 Fix detecting arc intersections

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-api-download/examples/download/data.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api-download/examples/download/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api-download/examples/download/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api-download/examples/download/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api-download/index.md
grid-packages/ag-grid-docs/src/example-generation/chart-utils.ts
grid-packages/ag-grid-docs/src/example-generation/chart-vanilla-src-parser.ts
grid-packages/ag-grid-docs/src/example-generation/chart-vanilla-to-angular.ts
grid-packages/ag-grid-docs/src/example-generation/chart-vanilla-to-react.ts
grid-packages/ag-grid-docs/src/example-generation/chart-vanilla-to-vue.ts
grid-packages/ag-grid-docs/src/example-generation/chart-vanilla-to-vue3.ts
grid-packages/ag-grid-docs/src/example-generation/parser-utils.ts

Now working for each framework.

AG-7897 Chart API Downloads

---

charts-packages/ag-charts-community/src/chart/axis/logAxis.ts

PR for https://ag-grid.atlassian.net/browse/AG-7746

AG-7746 - Allow logAxis min/max to be any non-zero number

---

charts-packages/ag-charts-community/src/chart/agChartOptions.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-7746

AG-7746 - Update logAxis min/max docs

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/examples/axis-tick-density/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/index.md

PR for https://ag-grid.atlassian.net/browse/AG-7909.
Docs updates

Ag 7909/axes docs

---

charts-packages/ag-charts-community/src/chart/axis/logAxis.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/index.md

PR for https://ag-grid.atlassian.net/browse/AG-7746
console warnings and docs changes

Ag 7746/log axis

---

grid-packages/ag-grid-docs/documentation/src/components/ApiDocumentation.module.scss
grid-packages/ag-grid-docs/documentation/src/components/ApiDocumentation.tsx

PR for https://ag-grid.atlassian.net/browse/AG-8030
- Fixes overflow on long types in api reference docs

AG-8030 Fix overflow of long types in api docs

---

charts-community-modules/ag-charts-community/src/chart/chart.test.ts

Final PR for https://ag-grid.atlassian.net/browse/AG-8058

AG-8058 Add tests for node click range 'nearest' and pixel distance

---

charts-community-modules/ag-charts-community/src/chart/legend.ts

Multi-line legends are more complicated than tickets and should be done separately.

AG-8048 Multiple lines are disabled in legends

---

grid-packages/ag-grid-enterprise/package.json
grid-packages/ag-grid-enterprise/test-modifications.sh

Add a CI check so that uncommitted changes to `ag-grid-enterprise/src/main.ts` are detected by CI.

Add CI check for ag-grid-enterprise modifications

---

charts-community-modules/ag-charts-community/src/sparklines-util.ts
grid-enterprise-modules/sparklines/src/sparkline/agSparkline.ts

PR for https://ag-grid.atlassian.net/browse/AG-8127
use standalone `jsonMerge` to clone sparkline options

AG-8127 - Avoid mutating user provided sparkline options

---

charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
charts-community-modules/ag-charts-community/src/chart/overlay/overlay.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overlays/examples/no-data-plain/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overlays/examples/no-data-plain/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overlays/index.md

https://ag-grid.atlassian.net/browse/AG-5750

AG-5750 - Allow noData overlay text only configuration

---

charts-community-modules/ag-charts-community/src/chart/test/utils.ts

PR for https://ag-grid.atlassian.net/browse/AG-3479

AG-3479 WheelEvent test util

---

charts-community-modules/ag-charts-community/src/axis.ts
charts-community-modules/ag-charts-community/src/chart/chartAxis.ts
charts-community-modules/ag-charts-community/src/chart/layout/layoutService.ts
charts-community-modules/ag-charts-community/src/module-support.ts
charts-community-modules/ag-charts-community/src/scale/bandScale.ts
charts-community-modules/ag-charts-community/src/scale/continuousScale.ts
charts-community-modules/ag-charts-community/src/sparklines-util.ts
charts-community-modules/ag-charts-community/src/util/module.ts

PR for https://ag-grid.atlassian.net/browse/AG-4371

Ag 4371/crosshairs

---

grid-enterprise-modules/sparklines/src/sparkline/sparkline.ts

PR for https://ag-grid.atlassian.net/browse/AG-8059

AG-8059 - Update sparklines tooltip when data changes

---

grid-packages/ag-grid-docs/documentation/doc-pages/redux-integration-pt2/examples/redux-file-browser/FileBrowser.jsx
grid-packages/ag-grid-docs/documentation/src/components/example-runner/Extras.jsx
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-angular-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-angular-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-react-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-react-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-react-ts-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-react-ts-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-typescript-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-typescript-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-vue-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-vue-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-vue3-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/charts-vue3-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-angular-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-angular-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-react-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-react-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-react-ts-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-react-ts-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-typescript-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-typescript-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-vue-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-vue-boilerplate/systemjs.config.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-vue3-boilerplate/systemjs.config.dev.js
grid-packages/ag-grid-docs/documentation/static/example-runner/grid-vue3-boilerplate/systemjs.config.js

Clean up SystemJS config to remove unused sections and no longer needed polyfills.

AG-8246 SystemJs cleanup

---

charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
charts-community-modules/ag-charts-community/src/chart/tooltip/tooltip.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-6181
Fixes flashing when hovering over the title and adds a flag to enable this tooltip interaction (defaulted to false).

AG-6181 tooltip interaction fixes

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-pie-series/examples/multi-doughnut-shared/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-pie-series/examples/multi-doughnut-shared/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-pie-series/index.md

PR for https://ag-grid.atlassian.net/browse/AG-8215

AG-8215 Add docs for pie series legendItemKey

---

charts-community-modules/ag-charts-community/src/chart/tooltip/tooltip.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-pie-series/examples/multi-doughnut/main.ts

PR for https://ag-grid.atlassian.net/browse/AG-6181

AG-6181 Fix tooltip no interaction option

---

package.json

https://ag-grid.atlassian.net/browse/AG-8267
Bumps submodules to pickup Charts enterprise module collapse changes.

AG-8267 - Bump submodules.

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/tooltip-interaction/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/tooltip-interaction/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/tooltip-interaction/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/index.md

PR for https://ag-grid.atlassian.net/browse/AG-6181

AG-6181 Add enableInteraction docs

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-crosshairs/index.md

Updated crosshair docs + examples

AG-4371 - Crosshair docs updates

---

charts-community-modules/ag-charts-community/src/chart/chart.ts
charts-community-modules/ag-charts-community/src/chart/mapping/__snapshots__/prepare.test.ts.snap
charts-community-modules/ag-charts-community/src/chart/mapping/prepare.ts
charts-community-modules/ag-charts-community/src/chart/tooltip/tooltip.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-crosshairs/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/tooltip-position/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/tooltip-position/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/tooltip-position/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/index.md

PR for https://ag-grid.atlassian.net/browse/AG-7368

AG-7368 - Allow configuration of tooltip position on a per series basis

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-crosshairs/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/charts-context-menu/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/charts-zoom/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/licensing/menu.json

PR for https://ag-grid.atlassian.net/browse/AG-6166

AG-6166 Add context menu module docs

---

charts-community-modules/ag-charts-community/src/axis.ts
charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

Revert "Ag 5568/axis tick labels"

---

charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
charts-community-modules/ag-charts-community/src/chart/chart.ts
charts-community-modules/ag-charts-community/src/chart/series/series.ts
charts-community-modules/ag-charts-community/src/chart/tooltip/tooltip.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/tooltip-interaction/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/index.md

PR for https://ag-grid.atlassian.net/browse/AG-6181

AG-6181 Tooltip interaction

---

charts-community-modules/ag-charts-community/src/chart/tooltip/tooltip.ts

PR for https://ag-grid.atlassian.net/browse/AG-3227

AG-3227 - Automatically hide the tooltip arrow if offset is configured

---

grid-enterprise-modules/sparklines/src/sparkline/agSparkline.ts
grid-enterprise-modules/sparklines/src/sparkline/area/areaSparkline.ts
grid-enterprise-modules/sparklines/src/sparkline/bar-column/barColumnSparkline.ts
grid-enterprise-modules/sparklines/src/sparkline/line/lineSparkline.ts
grid-enterprise-modules/sparklines/src/sparkline/sparkline.ts
grid-enterprise-modules/sparklines/src/sparkline/tooltip/sparklineTooltip.ts

PR for https://ag-grid.atlassian.net/browse/AG-8327 and https://ag-grid.atlassian.net/browse/AG-6716
Tooltip renderer applied on a per column basis

AG-8327 - Isolate sparkline tooltip renderer to a single column

---

charts-community-modules/ag-charts-community/src/chart/legend.ts

PR for https://ag-grid.atlassian.net/browse/AG-8317

AG-8317 - Update legend markers if marker shape has changed

---

grid-enterprise-modules/sparklines/src/sparkline/agSparkline.test.ts
grid-enterprise-modules/sparklines/src/sparkline/agSparkline.ts
grid-enterprise-modules/sparklines/src/sparkline/sparkline.ts
grid-enterprise-modules/sparklines/src/sparkline/tooltip/sparklineTooltip.ts

PR for https://ag-grid.atlassian.net/browse/AG-8327
Allow all tooltip properties to be configurable on a per column basis.

AG-8372 - Allow per column sparkline tooltip customisation

---

charts-community-modules/ag-charts-community/src/chart/crossline/crossLine.ts
charts-community-modules/ag-charts-community/src/chart/crossline/test/examples.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

https://ag-grid.atlassian.net/browse/AG-7489
Adds use of `DataModel` to `LineSeries`.

AG-7489 - Implement DataModel use in LineSeries.

---

charts-community-modules/ag-charts-community/src/axis.ts
charts-community-modules/ag-charts-community/src/chart/agChart.test.ts
charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
charts-community-modules/ag-charts-community/src/chart/mapping/prepare.test.ts
charts-community-modules/ag-charts-community/src/chart/mapping/prepare.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-5568

Ag 5568/axis ticks

---

charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoom.ts
charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoomModule.ts
charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoomScroller.ts
charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoomSelector.ts
charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoomTransformers.ts

For https://ag-grid.atlassian.net/browse/AG-3479

AG-3479 Change zoom default behaviour and fix limits to area and min zoom

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/examples/axis-min-max/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/examples/axis-min-max/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/examples/axis-min-max/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/examples/axis-nice/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/examples/axis-nice/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/examples/axis-nice/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-ticks/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/licensing/menu.json

PR for https://ag-grid.atlassian.net/browse/AG-7967

AG-7967 - Axis domain docs page

---

charts-community-modules/ag-charts-community/src/chart/mapping/__snapshots__/prepare.test.ts.snap
grid-packages/ag-grid-docs/documentation/doc-pages/charts-area-series/examples/missing-data-area/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-secondary/examples/multiple-axes/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-combination-series/examples/combination/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-layout-horizontal/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-pagination/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/100--stacked-bar/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/100--stacked-column/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/area-with-negative-values/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/chart-customisation/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/column-with-negative-values/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/combination-of-different-series-types/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/custom-marker-shapes/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/custom-tooltips/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/grouped-bar/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/grouped-column/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/line-with-gaps/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/real-time-data-updates/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/real-time-data-updates/provided/modules/reactFunctional/index.jsx
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/real-time-data-updates/provided/modules/reactFunctionalTs/index.tsx
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/real-time-data-updates/provided/modules/typescript/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/simple-line/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/stacked-area/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/stacked-bar/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/stacked-column/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/time-axis-with-irregular-intervals/main.ts

PR for https://ag-grid.atlassian.net/browse/AG-8323

AG-8323 - clean up all `legend.position: 'bottom'` settings in examples

---

charts-community-modules/ag-charts-community/src/chart/chartAxesTypes.ts
charts-community-modules/ag-charts-community/src/chart/factory/chartTypes.ts
charts-community-modules/ag-charts-community/src/chart/factory/setupModules.ts
charts-community-modules/ag-charts-community/src/chart/themes/chartTheme.ts
charts-community-modules/ag-charts-community/src/util/module.ts
charts-enterprise-modules/ag-charts-enterprise/src/crosshair/crosshair.test.ts
charts-enterprise-modules/ag-charts-enterprise/src/crosshair/crosshairModule.ts
charts-enterprise-modules/ag-charts-enterprise/src/crosshair/crosshairTheme.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-8434

AG-8434 - crosshair theme

---

charts-enterprise-modules/ag-charts-enterprise/src/crosshair/crosshairLabel.ts

PR for https://ag-grid.atlassian.net/browse/AG-8486

AG-8486 - Fix crosshair label clipping

---

charts-enterprise-modules/ag-charts-enterprise/src/crosshair/crosshair.ts

PR for https://ag-grid.atlassian.net/browse/AG-8487

AG-8487 - Remove crosshair on mouseout

---

charts-community-modules/ag-charts-community/src/chart/tooltip/tooltip.ts
charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoom.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-8506

AG-8506 Remove global typescript overrides

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/default-tooltip-arrow/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/default-tooltip-arrow/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/default-tooltip-arrow/styles.css
grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/index.md

PR for https://ag-grid.atlassian.net/browse/AG-8364

AG-8364 - Add docs example for configuring tooltip arrow

---

charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoom.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-context-menu/examples/context-menu-actions/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-context-menu/examples/context-menu-actions/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-context-menu/examples/context-menu/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-context-menu/examples/context-menu/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-context-menu/index.md
grid-packages/ag-grid-docs/documentation/doc-pages/charts-zoom/examples/zoom-context-menu/data.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-zoom/examples/zoom-context-menu/index.html
grid-packages/ag-grid-docs/documentation/doc-pages/charts-zoom/examples/zoom-context-menu/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-zoom/index.md

PR for https://ag-grid.atlassian.net/browse/AG-8467

AG-8467 Context menu docs

---

grid-community-modules/core/src/ts/gridBodyComp/gridBodyComp.ts
grid-community-modules/core/src/ts/gridBodyComp/gridBodyCtrl.ts
grid-community-modules/core/src/ts/gridBodyComp/rowContainer/rowContainerEventsFeature.ts
grid-community-modules/react/src/reactUi/gridBodyComp.tsx
grid-community-modules/solid/src/grid/gridBodyComp.tsx
grid-community-modules/styles/src/internal/base/parts/_grid-layout.scss
grid-packages/ag-grid-react/src/reactUi/gridBodyComp.tsx
grid-packages/ag-grid-solid/src/grid/gridBodyComp.tsx

https://ag-grid.atlassian.net/browse/AG-8494

AG-8494 - replace keyboard listeners with clipboard events

---

charts-enterprise-modules/ag-charts-enterprise/src/crosshair/crosshairModule.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-crosshairs/index.md

PR for https://ag-grid.atlassian.net/browse/AG-4371

AG-4371 - Add API reference section to crosshair docs

---

grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes-domain/index.md

PR for https://ag-grid.atlassian.net/browse/AG-7967

AG-7967 - axis domain docs updates

---

charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
charts-community-modules/ag-charts-community/src/motion/states.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-8461
https://github.com/ag-grid/ag-grid/assets/3817697/6df9c6a6-40c1-4bfd-aef9-ddbe376e2d78

AG-8461 Add bar/column series initial load animation

---

charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts

PR for https://ag-grid.atlassian.net/browse/AG-8468
Merging into https://github.com/ag-grid/ag-grid/pull/6596 (do not merge this until that one is done).
https://github.com/ag-grid/ag-grid/assets/3817697/6ede2e4d-5d82-4e26-8521-31d7f869679f

AG-8468 Add scatter series initial load animation

---

charts-community-modules/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts

PR for https://ag-grid.atlassian.net/browse/AG-8461
https://github.com/ag-grid/ag-grid/assets/3817697/e7df4c3e-f413-444d-9dc6-b368b1b3392c

AG-8461 Add histogram series initial load animation

---

charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts

PR for https://ag-grid.atlassian.net/browse/AG-8485
https://github.com/ag-grid/ag-grid/assets/3817697/98c86c41-b06b-47ce-812d-6f1222abc3f9

AG-8465 Add label initial load animations

---

charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-8461 and https://ag-grid.atlassian.net/browse/AG-8463

AG-8461 AG-8463 Add resize animation event to skip animation on resize

---

charts-community-modules/ag-charts-community/src/chart/chart.ts
charts-community-modules/ag-charts-community/src/chart/mapping/prepareSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-pie-series/index.md

PR for https://ag-grid.atlassian.net/browse/AG-8110

AG-8110 Change legend to merge duplicate items

---

grid-enterprise-modules/charts/src/charts/__snapshots__/chartModelMigration.test.ts.snap
grid-enterprise-modules/charts/src/charts/chartModelMigration.test.ts
grid-enterprise-modules/charts/src/charts/chartModelMigration.ts
grid-enterprise-modules/charts/test/chart-model-examples/22.1.0-pie-callout-chart-model.json

https://ag-grid.atlassian.net/browse/AG-8512
Adds `ChartModel` migrations for v30.0.0 release.

AG-8512 - Add v30 ChartModel Migrations.

---

charts-community-modules/ag-charts-community/src/axis.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json

PR for https://ag-grid.atlassian.net/browse/AG-8604

AG-8604 - Fix auto rotation and address SonarCloud issues

---

charts-community-modules/ag-charts-community/src/chart/mapping/prepare.ts
charts-community-modules/ag-charts-community/src/chart/themes/chartTheme.ts
grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-api-cross-filter-chart/examples/most-populous-cities/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-customisation/examples/common-overrides/main.ts
grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-customisation/examples/custom-chart-theme/main.ts

PR for https://ag-grid.atlassian.net/browse/AG-8513

AG-8513 - Integrated charts legend default changes

---

charts-community-modules/ag-charts-community/src/chart/chart.ts

PR for https://ag-grid.atlassian.net/browse/AG-8110

AG-8110 Add warning for legend labels with multiple fills

---

grid-packages/ag-grid-docs/dev-server.js
grid-packages/ag-grid-docs/example-generator-documentation.js

- Add debounce for incremental example generation.
- Debounce is tracked at docs page granularity, so large-scale example updates (`git pull` or `git checkout` cases) don't result in multiple re-generations.
- Trigger rebuild of specific example if number of changed examples < 5 for a docs page.
- Trigger rebuild of all docs page examples if >= 5 examples changed.
- Adjusts `example-generator-documentation.js` to avoid writing files if the content is unchanged.

More dev-server improvements

---

charts-community-modules/ag-charts-community/src/axis.ts

PR for https://ag-grid.atlassian.net/browse/AG-8662

AG-8662 - Fix category axis minSpacing

---

charts-community-modules/ag-charts-community/package.json
grid-community-modules/core/src/ts/filter/floating/provided/textInputFloatingFilter.ts
grid-community-modules/core/src/ts/rendering/cellEditors/dateStringCellEditor.ts
grid-enterprise-modules/charts/jest.config.js
grid-enterprise-modules/charts/package.json
grid-enterprise-modules/charts/src/charts/__snapshots__/chartModelMigration.test.ts.snap
grid-enterprise-modules/charts/tsconfig.test.json
grid-enterprise-modules/clipboard/jest.config.js
grid-enterprise-modules/clipboard/package.json
grid-enterprise-modules/clipboard/tsconfig.test.json
grid-enterprise-modules/core/package.json
grid-enterprise-modules/menu/jest.config.js
grid-enterprise-modules/menu/package.json
grid-enterprise-modules/menu/tsconfig.test.json
grid-enterprise-modules/multi-filter/package.json
grid-enterprise-modules/row-grouping/jest.config.js
grid-enterprise-modules/row-grouping/package.json
grid-enterprise-modules/row-grouping/tsconfig.test.json
grid-enterprise-modules/set-filter/jest.config.js
grid-enterprise-modules/set-filter/package.json
grid-enterprise-modules/set-filter/tsconfig.test.json
grid-enterprise-modules/sparklines/jest.config.js
grid-enterprise-modules/sparklines/package.json
grid-enterprise-modules/sparklines/tsconfig.test.json

Re-enables all earlier disabled tests as a result of the switch to ESM by default.

Fix Jest  config after ESM module switch

---

charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/barUtil.ts
charts-community-modules/ag-charts-community/src/chart/series/series.ts
charts-community-modules/ag-charts-community/src/module-support.ts
charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts

PR for https://ag-grid.atlassian.net/browse/AG-4337
Factor out common code in bar and waterfall series

Ag 4337/waterfall series

---

grid-packages/ag-grid-docs/documentation/doc-pages/component-tooltip/_simple-tooltip-react.md

Update _simple-tooltip-react.md to use useMemo correctly

---

charts-community-modules/ag-charts-community/src/chart/data/dataModel.ts
charts-enterprise-modules/ag-charts-enterprise/src/heatmap/typings.ts
charts-enterprise-modules/ag-charts-enterprise/src/waterfall/typings.ts
charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts
charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallThemes.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-waterfall-series/index.md

PR for https://ag-grid.atlassian.net/browse/AG-8617

AG-8617 - waterfall series total and subtotal items

---

charts-community-modules/ag-charts-community/src/axis.ts
charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
charts-community-modules/ag-charts-community/src/motion/states.ts
charts-community-modules/ag-charts-community/src/scene/selection.ts

PR for https://ag-grid.atlassian.net/browse/AG-8564
Note: We should remove the grid lines on the secondary axes as they look confusing in animation and cause some rendering errors when drawing over other grid lines, but I'll look into that in a future PR.
https://github.com/ag-grid/ag-grid/assets/3817697/6575778a-a077-46a3-9bb9-044b2f52bb44

AG-8564 Axis animation

---

charts-community-modules/ag-charts-community/src/axis.ts
charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
charts-enterprise-modules/ag-charts-enterprise/src/polar-series/radar/radarSeries.ts
charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts

PR for https://ag-grid.atlassian.net/browse/AG-8471
Also fixes https://ag-grid.atlassian.net/browse/AG-8861

AG-8471 bar series animation

---

charts-enterprise-modules/ag-charts-enterprise/src/waterfall/typings.ts
charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts
grid-packages/ag-grid-docs/documentation/doc-pages/charts-waterfall-series/index.md

PR for https://ag-grid.atlassian.net/browse/AG-8616

AG-8616 - Allow removing waterfall series connector lines

---

grid-community-modules/core/src/ts/interfaces/iRichCellEditorParams.ts
grid-community-modules/core/src/ts/widgets/agRichSelect.ts
grid-community-modules/styles/src/internal/base/parts/_common-structural.scss
grid-community-modules/styles/src/internal/base/parts/_widgets.scss
grid-enterprise-modules/rich-select/src/richSelect/richSelectCellEditor.ts

https://ag-grid.atlassian.net/browse/AG-8960

AG-8960 - rich select added support for async values

---

grid-community-modules/core/src/ts/entities/rowNode.ts

Correctly render group footer selection when change to group row by triggering row selected event for footer row

AG-9268 Correctly render group footer row selection

---

grid-packages/ag-grid-docs/documentation/doc-pages/aggregation/index.md

Include the enableValue in the description to highlight aggregate via GUI
Include additional aggregation API properties

AG-7423 Update docs on aggregation

---

grid-enterprise-modules/row-grouping/src/rowGrouping/columnDropZones/baseDropZonePanel.ts

Make rowGroupPanelSuppressSort grid option property reactive by refreshing row group panel when property updates

AG-9479 Make rowGroupPanelSuppressSort grid option property reactive

---

grid-packages/ag-grid-docs/documentation/src/components/example-runner/exampleRuntimeInjectedStyles.jsx

Creates a more consistent styling for action buttons across light and dark mode
| Dark mode  | Light mode |
| ------------- | ------------- |
| ![Screenshot 2023-11-13 at 14 00 29](https://github.com/ag-grid/ag-grid/assets/9768489/607a1f7b-905a-4ec6-9df0-b5f901d6e5ed) | ![Screenshot 2023-11-13 at 14 00 12](https://github.com/ag-grid/ag-grid/assets/9768489/54d1acb5-e34d-45bd-a39f-ca59dc469643) |

AG-3390 Update styling for grid action buttons

---

grid-packages/ag-grid-docs/documentation/src/pages/whats-new.json
grid-packages/ag-grid-docs/documentation/src/pages/whats-new.jsx
grid-packages/ag-grid-docs/documentation/src/pages/whats-new.module.scss

- Adds real changelog content
- Limits columns to 3x3 and breaks properly on mobile

AG-9721 - Update whats new content

---

grid-community-modules/styles/src/internal/themes/quartz/_quartz-variables.scss
grid-packages/ag-grid-docs/documentation/src/components/FrameworkSelectorInsideDocs.module.scss
grid-packages/ag-grid-docs/documentation/src/components/example-runner/ExampleRunnerResult.module.scss
grid-packages/ag-grid-docs/documentation/src/components/example-runner/exampleRuntimeInjectedStyles.jsx
grid-packages/ag-grid-docs/documentation/src/components/search/SearchBox.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/_base.scss
grid-packages/ag-grid-docs/documentation/src/design-system/components/_code.scss
grid-packages/ag-grid-docs/documentation/src/design-system/core/_variables.scss
grid-packages/ag-grid-docs/documentation/src/mainPageDemo/Example.module.scss
grid-packages/ag-grid-docs/documentation/src/pages/whats-new.module.scss

| Before      | After |
| ----------- | ----------- |
| ![image](https://github.com/ag-grid/ag-grid/assets/9768489/deec1e2b-01ec-4e89-9e92-b00716bf732a)      | ![image](https://github.com/ag-grid/ag-grid/assets/9768489/8f5d54ac-c973-44ab-9809-eaaa7e2a42c3)       |

AG-9397 Runner and theme styling improvements

---

grid-community-modules/styles/src/internal/base/parts/_charts.scss

Fixes chevron icon alignment in integrated charts toolpanel.

AG-10267 - Fix Toolpanel Chevron icon alignment

---

grid-packages/ag-grid-docs/documentation/gatsby-ssr.js
grid-packages/ag-grid-docs/documentation/src/components/SideMenu.jsx
grid-packages/ag-grid-docs/documentation/src/design-system/_root.scss
grid-packages/ag-grid-docs/documentation/src/design-system/_typography.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/ApiReference.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/SideNavigation.module.scss

Fixes for website / design system issues

Ag 10044 ds fixes

---

grid-packages/ag-grid-docs/documentation/src/design-system/modules/GridMenu.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/Menu.module.scss

Fixes extra spacing on charts pages nav on mobile

AG-3390 - Move page nav padding top to grid menu styles

---

grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/index.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/miniChartHelpers.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/miniChartWithPolarAxes.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniNightingale.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniRadarArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniRadarLine.ts

PR for https://ag-grid.atlassian.net/browse/AG-10355

Ag 10355/polar mini charts

---

grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/miniChartHelpers.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniNightingale.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniRadarArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniRadarLine.ts

PR for https://ag-grid.atlassian.net/browse/AG-10355

AG-10355 - Add markers to radar line mini chart, improve mini chart data

---

grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/statistical/miniBoxPlot.ts

PR for https://ag-grid.atlassian.net/browse/AG-10394

AG-10394 - Mini box plot chart

---

grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/statistical/miniBoxPlot.ts

PR for https://ag-grid.atlassian.net/browse/AG-10394

AG-10394 - Add axes to mini box plot chart

---

grid-packages/ag-grid-docs/documentation/src/components/site-header/SiteHeader.jsx
grid-packages/ag-grid-docs/documentation/src/design-system/_root.scss
grid-packages/ag-grid-docs/documentation/src/design-system/elements/_button.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/CodeViewer.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/Gif.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/HeaderNav.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/LearningVideos.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/Menu.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/Options.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/PagesNavigation.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/ProductDropdown.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/Search.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/SideNavigation.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/SiteHeader.module.scss

Syncs up Grid design system with charts. Specifically to align with this PR https://github.com/ag-grid/ag-charts/pull/898

Ag 10439 header refactor

---

grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/statistical/miniRangeBar.ts

PR for https://ag-grid.atlassian.net/browse/AG-10449

AG-10449 - Mini range bar

---

grid-enterprise-modules/charts/src/charts/chartComp/chartController.ts
grid-enterprise-modules/charts/src/charts/chartComp/gridChartComp.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/chartSettingsPanel.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/area/miniArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/area/miniNormalizedArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/area/miniStackedArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/bar/miniNormalizedBar.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/bar/miniStackedBar.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/column/miniNormalizedColumn.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/column/miniStackedColumn.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/cumulative/miniWaterfall.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/pie/miniDoughnut.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/pie/miniPie.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniNightingale.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniRadarArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/polar/miniRadarLine.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniChartsContainer.ts

PR for https://ag-grid.atlassian.net/browse/AG-10415

Ag 10415/mini waterfall chart

---

grid-community-modules/core/src/ts/interfaces/iChartOptions.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/format/series/seriesPanel.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/chartSettingsPanel.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/area/miniArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/area/miniNormalizedArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/area/miniStackedArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/bar/miniNormalizedBar.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/bar/miniStackedBar.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/column/miniNormalizedColumn.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/column/miniStackedColumn.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/cumulative/miniWaterfall.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/index.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/pie/miniDoughnut.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/pie/miniPie.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/statistical/miniBoxPlot.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/statistical/miniRangeArea.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniChartsContainer.ts
grid-enterprise-modules/charts/src/charts/chartComp/services/chartTranslationService.ts
grid-enterprise-modules/charts/src/charts/chartComp/utils/UpdateParamsValidator.ts
grid-enterprise-modules/charts/src/charts/chartComp/utils/seriesTypeMapper.ts
grid-enterprise-modules/menu/src/menu/chartMenuItemMapper.ts

PR for https://ag-grid.atlassian.net/browse/AG-10466

Ag 10466/mini range area

---

grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/cumulative/miniHeatmap.ts

PR for https://ag-grid.atlassian.net/browse/AG-10493

AG-10493 - Mini heatmap chart

---

grid-packages/ag-grid-docs/documentation/src/components/site-header/SiteHeader.jsx
grid-packages/ag-grid-docs/documentation/src/design-system/core/_breakpoints.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/HeaderNav.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/OptionsNavigation.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/ProductDropdown.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/Search.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/SiteHeader.module.scss
grid-packages/ag-grid-docs/documentation/src/design-system/modules/Toolbar.module.scss

Updates to products dropdown & general site header layout fixes

Ag 10398 products dropdown improvements

---

grid-community-modules/core/src/ts/interfaces/iChartOptions.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/cumulative/miniSunburst.ts

PR for https://ag-grid.atlassian.net/browse/AG-10503

AG-10503 - Mini sunburst chart

---

grid-community-modules/core/src/ts/interfaces/iChartOptions.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/cumulative/miniRadialColumn.ts
grid-enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/miniChartWithPolarAxes.ts

PR for https://ag-grid.atlassian.net/browse/AG-10513

AG-10513 - Mini radial column

---

grid-enterprise-modules/charts/src/charts/chartComp/services/chartOptionsService.ts

This fixes a bug introduced in 730454f3ae0403825d44620f40609cb7d04764bd

AG-8968 Fix radial bar chart axis settings options

---

grid-enterprise-modules/charts/src/charts/chartComp/model/chartDataModel.ts

RTI-1867 Retain multiple column selection when updating hierarchical integrated chart type

---

documentation/ag-grid-docs/src/content/docs/building/index.mdoc
documentation/ag-grid-docs/src/content/docs/framework-data-flow/index.mdoc
documentation/ag-grid-docs/src/content/docs/infinite-scrolling/index.mdoc
documentation/ag-grid-docs/src/content/docs/licensing/index.mdoc
documentation/ag-grid-docs/src/content/docs/packages-modules/index.mdoc
documentation/ag-grid-docs/src/content/docs/server-side-model-configuration/index.mdoc
documentation/ag-grid-docs/src/content/docs/server-side-model/index.mdoc
documentation/ag-grid-docs/src/content/docs/server-side-operations-graphql/index.mdoc
documentation/ag-grid-docs/src/content/docs/server-side-operations-nodejs/index.mdoc
documentation/ag-grid-docs/src/content/docs/server-side-operations-oracle/index.mdoc
documentation/ag-grid-docs/src/content/docs/server-side-operations-spark/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-area-customisation/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-axis-types/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-bar-customisation/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-column-customisation/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-data/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-line-customisation/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-points-of-interest/index.mdoc
documentation/ag-grid-docs/src/content/docs/sparklines-tooltips/index.mdoc
documentation/ag-grid-docs/src/design-system/core/_breakpoints.scss
documentation/ag-grid-docs/src/design-system/modules/Gif.module.scss
documentation/ag-grid-docs/src/design-system/modules/ImageCaption.module.scss
documentation/ag-grid-docs/src/design-system/modules/LearningVideos.module.scss
documentation/ag-grid-docs/src/design-system/modules/Menu.module.scss
documentation/ag-grid-docs/src/features/pages-navigation/components/PagesNavigation.tsx
documentation/ag-grid-docs/src/pages/404.astro
documentation/ag-grid-docs/src/pages/license-pricing.astro

Ag 3390 website design updates

---

documentation/ag-grid-docs/src/components/product-dropdown/ProductDropdown.tsx
documentation/ag-grid-docs/src/design-system/modules/ProductDropdown.module.scss

Update header product dropdown to activate on hover

Ag 11041 product dropdown improvements

---

documentation/ag-grid-docs/src/components/SiteLogo.tsx
documentation/ag-grid-docs/src/components/footer/Footer.tsx
documentation/ag-grid-docs/src/components/site-header/SiteHeader.astro
documentation/ag-grid-docs/src/design-system/core/_breakpoints.scss
documentation/ag-grid-docs/src/design-system/modules/Footer.module.scss

Some styling updates to the footer, making it light instead of blue so it works on docs pages more nicely 
| Before | After |
|--------|-------|
| ![Before](https://github.com/ag-grid/ag-grid/assets/9768489/db2807e6-de1c-47ce-853c-35708c0a9bf1) | ![After](https://github.com/ag-grid/ag-grid/assets/9768489/cefd4e42-20fd-4713-9380-e8611ba18a8d) |

AG-11017 Footer styling improvements

---

documentation/ag-grid-docs/src/components/theme-builder/EmptyState.module.scss
documentation/ag-grid-docs/src/components/theme-builder/EmptyState.tsx
documentation/ag-grid-docs/src/components/theme-builder/components/general/RootContainer.tsx
documentation/ag-grid-docs/src/pages/theme-builder.astro
external/ag-website-shared/src/images/inline-svgs/theme-builder-dark.svg
external/ag-website-shared/src/images/inline-svgs/theme-builder-light.svg

Ag 11337 theme builder empty state

---

documentation/ag-grid-docs/src/components/theme-builder/components/general/GridPreview.tsx
documentation/ag-grid-docs/src/components/theme-builder/components/grid-config/grid-config-atom.ts
documentation/ag-grid-docs/src/components/theme-builder/components/grid-config/grid-data.ts
documentation/ag-grid-docs/src/components/theme-builder/components/grid-config/grid-options.ts

Updates to themebuilder default dataset, grid options, and grid max size

Ag 9300 theme builder md updates

---

community-modules/client-side-row-model/src/clientSideRowModel/clientSideRowModel.ts
community-modules/core/src/columns/columnModel.ts
community-modules/core/src/dragAndDrop/dragAndDropService.ts
community-modules/core/src/entities/column.ts
community-modules/core/src/environment.ts
community-modules/core/src/events.ts
community-modules/core/src/pagination/paginationAutoPageSizeService.ts
community-modules/core/src/widgets/popupService.ts
community-modules/core/src/widgets/virtualList.ts
community-modules/styles/src/internal/base/_base-variables.scss
community-modules/styles/src/internal/base/parts/_charts.scss
community-modules/styles/src/internal/themes/quartz/_index.scss
community-modules/styles/src/internal/themes/quartz/_quartz-variables.scss
community-modules/theming/src/Theme.ts
community-modules/theming/src/metadata/docs.ts
community-modules/theming/src/parts/core/core-part.ts
community-modules/theming/src/parts/core/css/charts.css
documentation/ag-grid-docs/src/components/theme-builder/components/general/GridPreview.tsx
documentation/ag-grid-docs/src/components/theme-builder/model/rendered-theme.ts
enterprise-modules/advanced-filter/src/advancedFilter/advancedFilterCtrl.ts
enterprise-modules/charts/src/charts/chartComp/menu/chartMenu.ts
enterprise-modules/charts/src/charts/chartService.ts
enterprise-modules/master-detail/src/masterDetail/detailCellRendererCtrl.ts
plugins/ag-grid-generate-code-reference-files/src/executors/generate/formatAST.js
scripts/formatAST.js

JIRA: https://ag-grid.atlassian.net/browse/AG-11501
Branch build for testing: https://testing.ag-grid.com/AG-11501/

AG-11501 Respond to changes in CSS variable values

---

community-modules/core/src/gridComp/gridCtrl.ts
community-modules/styles/src/internal/base/_base-variables.scss
community-modules/styles/src/internal/base/parts/_common-structural.scss
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/index.html
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/main.ts
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/angular/app.component.ts
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/angular/styles.css
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/reactFunctional/index.jsx
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/reactFunctional/styles.css
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/reactFunctionalTs/index.tsx
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/reactFunctionalTs/styles.css
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/provided/modules/vue3/main.js
documentation/ag-grid-docs/src/content/docs/grid-size/_examples/width-and-height/styles.css
documentation/ag-grid-docs/src/content/docs/grid-size/index.mdoc

This card adds a feature where if the grid is initialised within a container that has no height, it adopts a default height of 400px.
https://ag-grid.atlassian.net/browse/AG-10825

AG-10825 default grid height

---

documentation/ag-grid-docs/src/components/Code.module.scss
documentation/ag-grid-docs/src/components/Code.tsx
documentation/ag-grid-docs/src/components/snippet/Snippet.astro
documentation/ag-grid-docs/src/components/snippet/Snippet.tsx
external/ag-website-shared/src/components/icon/Icon.tsx

Add copy to clipboard button option to code snippets

Ag 11837 snippet copy to clipboard

---

community-modules/core/src/entities/rowNode.ts

See https://ag-grid.atlassian.net/browse/AG-8389
See my comments in the linked ticket, I may have misunderstood what is required.

AG-8389 Resync selectable state when group flag changed

---

enterprise-modules/row-grouping/src/rowGrouping/groupStage.ts

See https://ag-grid.atlassian.net/browse/AG-11678 for reproduction and an explanation of the root problem.
Also, as noted in the above ticket:
> This might become a performance issue in applications that frequently move large numbers of rows around using the transaction API.
If there's concern around this case I can set up a benchmark to measure the impact of this change (together with the original tree data performance change) compared to baseline.
EDIT: [f665a98](https://github.com/ag-grid/ag-grid/pull/8005/commits/f665a98f370817bf41f833696e12726f3d5b892e) makes significant performance improvements.

AG-11678 Fix moving nodes edge case in tree data

---

documentation/ag-grid-docs/src/content/docs/master-detail-refresh/_examples/refresh-everything/main.ts
documentation/ag-grid-docs/src/content/docs/master-detail-refresh/_examples/refresh-everything/provided/modules/reactFunctionalTs/index.tsx
documentation/ag-grid-docs/src/content/docs/value-setters/_examples/read-only-transactions/main.ts

Missed a few in #8077, caught by the documentation tests

AG-9259 Fix more documentation warnings

---

documentation/ag-grid-docs/src/content/docs/row-dragging-to-external-dropzone/_examples/two-grids/provided/modules/angular/app.component.ts
documentation/ag-grid-docs/src/content/docs/row-dragging-to-external-dropzone/_examples/two-grids/provided/modules/vue3/main.js
documentation/ag-grid-docs/src/content/docs/row-dragging-to-grid/_examples/two-grids-with-drop-position/provided/modules/angular/app.component.ts
documentation/ag-grid-docs/src/content/docs/row-dragging-to-grid/_examples/two-grids-with-drop-position/provided/modules/vue3/main.js

AG-9259 Fix vue and angular docs warnings

---

documentation/ag-grid-docs/src/content/docs/server-side-model-selection/_examples/api-group-selects-children/main.ts
documentation/ag-grid-docs/src/content/docs/server-side-model-selection/_examples/api-select-all/main.ts
documentation/ag-grid-docs/src/content/docs/server-side-model-selection/index.mdoc

See https://ag-grid.atlassian.net/browse/AG-11863
Row IDs were outdated

AG-11863 Fix SSRM selection API examples

---

community-modules/styles/src/internal/base/parts/_grid-layout.scss

See https://ag-grid.atlassian.net/browse/AG-11444
Missed one case

AG-11444 Skeleton alignment respects col def

---

documentation/ag-grid-docs/src/components/example-grid/Toolbar.tsx

Fixes https://www.ag-grid.com/archive/32.0.0/react-data-grid/themes/ theme links not displaying properly on demo page.

RTI-2120 - Fix demo page theme URL params

---

documentation/ag-grid-docs/src/content/docs/keyboard-navigation/_examples/custom-tabbing-into-grid/main.ts
documentation/ag-grid-docs/src/content/docs/keyboard-navigation/_examples/custom-tabbing-into-grid/provided/modules/reactFunctional/index.jsx

Fixes https://ag-grid.atlassian.net/browse/RTI-2136

RTI-2136 - fixed custom tabbing example

---

enterprise-modules/core/src/widgets/agRichSelect.ts

Fixes https://ag-grid.atlassian.net/browse/RTI-2155

RTI-2155 - fixed richSelect completing with empty value

---

documentation/ag-grid-docs/src/content/docs/filtering/index.mdoc

Add gap between gifs for column filters page

RTI-2116 - Add spacing for gifs on columns filters page

---

external/ag-website-shared/.gitrepo
external/ag-website-shared/src/components/footer/Footer.module.scss
external/ag-website-shared/src/content/license-features/chartsFeaturesMatrix.json

Fix footer logo collapsing onto two lines at certain breakpoints

Rti 2131 footer logo layout

---

enterprise-modules/rich-select/src/richSelect/richSelectCellEditor.ts

Fixes https://ag-grid.atlassian.net/browse/RTI-2150

RTI-2150 - fixed richSelect focus handling

---

community-modules/styles/src/internal/base/parts/_grid-layout.scss
community-modules/theming/src/parts/core/css/grid-layout.css

https://ag-grid.atlassian.net/browse/RTI-2166

RTI-2166 group row indentation

---

community-modules/styles/_css-content.scss
community-modules/styles/src/internal/base/parts/_grid-layout.scss
community-modules/theming/src/parts/core/css/grid-layout.css
packages/ag-grid-charts-enterprise/styles/_css-content.scss
packages/ag-grid-charts-enterprise/styles/ag-grid-no-native-widgets.css
packages/ag-grid-community/styles/_css-content.scss
packages/ag-grid-community/styles/ag-grid-no-native-widgets.css
packages/ag-grid-community/styles/ag-grid.css

Fixes https://ag-grid.atlassian.net/browse/RTI-2182

RTI-2182 - fixes gap in sticky bottom rows

---

documentation/ag-grid-docs/public/changelog/releases/32_0_0.md
documentation/ag-grid-docs/src/content/versions/ag-grid-versions.json

RTI-2135 Fixed release date typo

---

documentation/ag-grid-docs/src/content/docs/themes/index.mdoc

Add Theme Builder section to themes docs page

RTI-2119 - Add Theme Builder section to themes docs page

---

documentation/ag-grid-docs/src/content/docs/touch/index.mdoc

RTI-2144 touch doc typo fix

---

documentation/ag-grid-docs/src/content/docs/column-definitions/_examples/column-definition-update/main.ts

Fixes https://ag-grid.atlassian.net/browse/RTI-2193

RTI-2193 - fixed updating column definition docs

---

documentation/ag-grid-docs/src/content/docs/column-updating-definitions/_examples/matching-columns/provided/modules/vue3/styles.css

Fixes https://ag-grid.atlassian.net/browse/RTI-2196

RTI-2196 - fixed matching columns example

---

community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
community-modules/core/src/entities/gridOptions.ts
documentation/ag-grid-docs/src/content/docs/grid-interface/_events-javascript.mdoc
documentation/ag-grid-docs/src/content/docs/rtl/index.mdoc
packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts

Typo fixes for:
- RTI-2153
- RTI-2154
- RTI-2167

RTI-2153 Typo fixes also includes 2154 and 2167

---

community-modules/core/src/rendering/rowRenderer.ts

Fixes https://ag-grid.atlassian.net/browse/RTI-2164

RTI-2164 - fixed cells losing focus when rows move between sticky and non-sticky

---

documentation/ag-grid-docs/src/content/docs/filter-set/index.mdoc

Fixes https://ag-grid.atlassian.net/browse/RTI-2118

RTI-2118 - fixed Set Filter docs

---

documentation/ag-grid-docs/src/content/docs/value-getters/_examples/value-getters/main.ts

Fixes https://ag-grid.atlassian.net/browse/RTI-2128

RTI-2128 - fixed value getter sorting example

---

documentation/ag-grid-docs/src/content/docs/filter-api/index.mdoc

Fixes https://ag-grid.atlassian.net/browse/RTI-2133

RTI-2133 - fixed wrong link in docs

---

documentation/ag-grid-docs/src/content/docs/filter-quick/_examples/quick-filter-configuration/main.ts
documentation/ag-grid-docs/src/content/docs/filter-quick/index.mdoc

Fixes https://ag-grid.atlassian.net/browse/RTI-2138

RTI-2138 - fixed example breaking without escaping characters

---

documentation/ag-grid-docs/src/content/docs/total-rows/index.mdoc

Fixes https://ag-grid.atlassian.net/browse/RTI-2183

RTI-2183 - fixed typo

---

documentation/ag-grid-docs/src/content/docs/pivoting/_examples/secondary-columns/index.html
documentation/ag-grid-docs/src/content/docs/pivoting/_examples/secondary-columns/main.ts
documentation/ag-grid-docs/src/content/docs/pivoting/_examples/secondary-columns/styles.css

Fixes https://ag-grid.atlassian.net/browse/RTI-2191

RTI-2191 - fixed example broken styles

---

documentation/ag-grid-docs/src/content/docs/getting-started/index.mdoc

Updated 'grid' to 'data grid' keywords in Getting Started for SEO purposes, based on data from SEMRush

RTI-2195 Update getting started keywords

---

documentation/ag-grid-docs/src/content/docs/grid-interface/_events-react.mdoc
documentation/ag-grid-docs/src/content/docs/grid-interface/_index-react.mdoc

rename "React Hooks" to "React Best Practices"

---

community-modules/theming/src/metadata/docs.ts
community-modules/theming/src/parts/core/core-part.ts
community-modules/theming/src/parts/core/css/chart-widgets-todo-split-into-separate-files.css
community-modules/theming/src/parts/core/css/charts.css
community-modules/theming/src/parts/core/css/column-drop.css
community-modules/theming/src/parts/core/css/columns-tool-panel.css
community-modules/theming/src/parts/core/css/common-structural.css
community-modules/theming/src/parts/core/css/grid-layout.css
community-modules/theming/src/parts/core/css/rich-select.css

Most recent Sass changes made to release branch ported to Theming API

AG-11726 porting AG-10928 Sass changes to Theming API

---

community-modules/core/src/filter/quickFilterService.ts
documentation/ag-grid-docs/src/content/docs/filter-quick/_examples/quick-filter-configuration/main.ts
documentation/ag-grid-docs/src/content/docs/filter-quick/index.mdoc

Fixes https://ag-grid.atlassian.net/browse/RTI-2138

RTI-2138 - fixed regular expression search

---

documentation/ag-grid-docs/src/content/docs/integrated-charts-api-cross-filter-chart/_examples/sales-dashboard/style.css

RTI-2162 cross filtering example height fix

---

documentation/ag-grid-docs/src/content/docs/grid-interface/_index-angular.mdoc
documentation/ag-grid-docs/src/content/docs/grid-interface/_index-vue.mdoc

RTI-2158   [NR] API Angular / Vue do not include event handler in first snippet

---

documentation/ag-grid-docs/src/content/docs/aggregation-custom-functions/_examples/custom-avg-function/main.ts

Fixes https://ag-grid.atlassian.net/browse/RTI-2180

RTI-2180 - fixed multi-level custom agg sorting

---

community-modules/core/src/interfaces/iChartOptions.ts
documentation/ag-grid-docs/src/content/docs/integrated-charts-chart-tool-panels/index.mdoc

Updated the chart tool panel doc to reflect the latest menu structure

RTI-2169 Chart tool panel config cleanup

---

documentation/ag-grid-docs/src/layouts/Layout.astro
documentation/ag-grid-docs/src/pages/robots.txt.ts
documentation/ag-grid-docs/src/utils/env.ts

Allow robots.txt to be shown on dev, but not on staging

AG-12053 - Add noindex to archive pages

---

documentation/ag-grid-docs/src/components/demos/examples/finance/FinanceExample.module.css
documentation/ag-grid-docs/src/components/demos/examples/hr/HRExample.module.css
documentation/ag-grid-docs/src/components/demos/examples/hr/HRExample.tsx
documentation/ag-grid-docs/src/components/demos/examples/hr/cell-renderers/ContactCellRenderer.module.css
documentation/ag-grid-docs/src/components/demos/examples/hr/cell-renderers/ContactCellRenderer.tsx
documentation/ag-grid-docs/src/components/demos/examples/inventory/InventoryExample.module.css
documentation/ag-grid-docs/src/components/demos/examples/inventory/cell-renderers/ActionsCellRenderer.module.css
documentation/ag-grid-docs/src/components/demos/examples/inventory/cell-renderers/ActionsCellRenderer.tsx
documentation/ag-grid-docs/src/pages-styles/example.module.scss

Fixes styling for all demos when run outside of website.

Ag 12061 demos styling fixes

---

enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/defaultStrategy.ts

Requested by QA: https://ag-grid.atlassian.net/browse/AG-11987

AG-11987 Improve error message

---

documentation/ag-grid-docs/src/features/docs/components/Header.module.scss
documentation/ag-grid-docs/src/features/docs/components/Header.tsx
documentation/ag-grid-docs/src/pages/[framework]-data-grid/[pageName].astro

Add version number to the top of docs pages

AG-11161 - Add version number to the top of docs pages

---

community-modules/core/src/gridBodyComp/abstractFakeScrollComp.ts
community-modules/core/src/gridBodyComp/fakeHScrollComp.ts
community-modules/core/src/gridBodyComp/fakeVScrollComp.ts
community-modules/core/src/gridBodyComp/gridBodyCtrl.ts
community-modules/core/src/gridBodyComp/gridBodyScrollFeature.ts
community-modules/core/src/gridBodyComp/rowContainer/rowContainerComp.ts
community-modules/core/src/gridBodyComp/rowContainer/rowContainerCtrl.ts
community-modules/core/src/headerRendering/columnMoveHelper.ts
community-modules/core/src/headerRendering/gridHeaderCtrl.ts
community-modules/core/src/headerRendering/rowContainer/headerRowContainerCtrl.ts
community-modules/react/src/reactUi/rows/rowContainerComp.tsx
community-modules/styles/src/internal/base/parts/_common-structural.scss
community-modules/theming/src/parts/core/css/common-structural.css
packages/ag-grid-react/src/reactUi/rows/rowContainerComp.tsx

https://ag-grid.atlassian.net/browse/AG-2065

AG-2065 - make all containers scrollable

---

community-modules/core/src/gridBodyComp/rowDragFeature.ts

I should have probably caught this in review in #8259 
Just need to map the nodes back to their row data for the transaction

AG-12085 Map nodes to row data for transaction

---

documentation/ag-grid-docs/src/content/docs/codemods/index.mdoc

Improve codemods documentation and add the command line arguments and configuration details

codemods docs

---

plugins/ag-grid-generate-code-reference-files/src/executors/generate/generate-code-reference-files.ts

Fix accessing undefined heritageClauses

Ag 11965 bug fix grid api doc generator (2)

---

community-modules/core/src/utils/object.test.ts
community-modules/core/src/utils/object.ts
enterprise-modules/charts/src/charts/chartComp/utils/object.test.ts

* Skip unsafe keys
* deepMerge is already safe
* Add tests

AG-12065 Avoid prototype polution (#8250)

---

community-modules/core/src/interfaces/iColumn.ts
documentation/ag-grid-docs/src/content/api-documentation/column-object/properties.json

* AG-12087 Restore getOriginalParent to Column interface
* Add to column ref page

AG-12087 Restore getOriginalParent to Column interface (#8251)

---

community-modules/theming/src/parts/core/css/grid-layout.css

Fixing code mis-ported from Sass themes to Theme Builder.

AG-11726 fix Theme Builder sticky row style

---

community-modules/core/src/rendering/features/stickyRowFeature.ts

See https://ag-grid.atlassian.net/browse/AG-11844?focusedCommentId=66129
Missed this case in #8256

AG-11844 Fix stickiness of footer nodes in row groups

---

documentation/ag-grid-docs/src/content/docs/codemods/index.mdoc

B32.0.1 codemods docs cherry pick

---

documentation/ag-grid-docs/src/components/reference-documentation/ApiDocumentationWithQuery.tsx
documentation/ag-grid-docs/src/components/reference-documentation/InterfaceDocumentation.astro
documentation/ag-grid-docs/src/components/reference-documentation/InterfaceDocumentationWithQuery.tsx
documentation/ag-grid-docs/src/components/reference-documentation/ReferenceDocumentation.tsx
documentation/ag-grid-docs/src/features/docs/components/DocsExampleRunner.tsx
documentation/ag-grid-docs/src/stores/frameworkStore.ts
documentation/ag-grid-docs/src/utils/hooks/useSyncFrameworkStoreState.ts

* Only fetch docs example after it has synced internal framework with localstorage
* Clean up of code

AG-12030 - Fix docs example runner fetch

---

documentation/ag-grid-docs/src/components/automated-examples/examples/row-grouping/index.ts
documentation/ag-grid-docs/src/pages/index.astro

* Only show automated examples if visible
* Don't show grid loading/no rows message

Ag-11116 - Improve lighthouse scores - part 2

---

enterprise-modules/row-grouping/src/rowGrouping/groupStage/groupStage.ts
enterprise-modules/row-grouping/src/rowGrouping/groupStage/treeStrategy.ts

- TreeNode class
- Concrete TreeNode for the root
- Use Map instead of Object for the TreeNode children
- Proper destruction of the Strategy in the stage
- Remove cacheUpsert by path

AG-12273 (3) more tree data refactoring

---

community-modules/core/src/alignedGridsService.ts
community-modules/core/src/columns/columnModel.ts
community-modules/core/src/columns/dataTypeService.ts
community-modules/core/src/filter/filterManager.ts
community-modules/core/src/gridBodyComp/gridBodyCtrl.ts
community-modules/core/src/gridBodyComp/rowContainer/rowContainerCtrl.ts
community-modules/core/src/headerRendering/cells/column/sortIndicatorComp.ts
community-modules/core/src/headerRendering/gridHeaderCtrl.ts
community-modules/core/src/misc/state/stateService.ts
community-modules/core/src/rendering/features/positionableFeature.ts
community-modules/core/src/widgets/tooltipFeature.ts

Results in a drop of 1.6kb off the minified core esm file. I am aware it's a small improvement but they are simple code changes so seems like a worthwhile change.

AG-12348 Remove code duplications

---

documentation/ag-grid-docs/src/components/pages-navigation/components/LegacyPagesNavigation.module.scss
documentation/ag-grid-docs/src/components/pages-navigation/components/PagesNavigation.tsx

Remove code for adding sub-headers to docs menu

AG-12260 - Remove docs subheaders code

---

community-modules/core/src/entities/rowNode.ts

See https://ag-grid.atlassian.net/browse/AG-12177

AG-12177 Fix footer sharing same event service as sibling

---

documentation/ag-grid-docs/src/components/demos/Demos.module.scss
documentation/ag-grid-docs/src/components/demos/DemosTabs.astro
documentation/ag-grid-docs/src/pages-styles/example.module.scss
documentation/ag-grid-docs/src/pages/example-finance.astro
documentation/ag-grid-docs/src/pages/example-hr.astro
documentation/ag-grid-docs/src/pages/example-inventory.astro
documentation/ag-grid-docs/src/pages/example.astro

Provides a fix for smaller heights below 720px

Ag 12360 improve demo example height

---

community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
community-modules/core/src/entities/gridOptions.ts
community-modules/core/src/entities/rowNode.ts
community-modules/core/src/grid.ts
community-modules/core/src/gridBodyComp/gridBodyComp.ts
community-modules/core/src/gridOptionsService.ts
community-modules/core/src/headerRendering/cells/column/selectAllFeature.ts
community-modules/core/src/main.ts
community-modules/core/src/propertyKeys.ts
community-modules/core/src/rendering/cell/cellKeyboardListenerFeature.ts
community-modules/core/src/rendering/cell/cellRangeFeature.ts
community-modules/core/src/rendering/checkboxSelectionComponent.ts
community-modules/core/src/rendering/row/rowCtrl.ts
community-modules/core/src/rowNodes/selectableService.ts
community-modules/core/src/selection/selectionService.ts
community-modules/core/src/validation/rules/gridOptionsValidations.ts
community-modules/core/src/validation/validationService.ts
enterprise-modules/range-selection/src/rangeSelection/agFillHandle.ts
enterprise-modules/range-selection/src/rangeSelection/rangeService.ts
enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/defaultStrategy.ts
enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/groupSelectsChildrenStrategy.ts
enterprise-modules/server-side-row-model/src/serverSideRowModel/services/serverSideSelectionService.ts
packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
plugins/ag-grid-generate-example-files/gridOptionsTypes/_gridOptions_Types.json

See https://ag-grid.atlassian.net/browse/AG-12285

AG-12285 Selection API changes

---

documentation/ag-grid-docs/src/content/docs/component-cell-renderer/index.mdoc

See https://ag-grid.atlassian.net/browse/RTI-2220

RTI-2220 typo cell components

---

documentation/ag-grid-docs/src/content/docs/component-cell-renderer/index.mdoc

See https://ag-grid.atlassian.net/browse/RTI-2224

RTI-2224 Fix typo in selecting components

---

documentation/ag-grid-docs/src/content/docs/row-selection/index.mdoc

See https://ag-grid.atlassian.net/browse/RTI-2226

RTI-2226 Fix typos in group selection docs

---

documentation/ag-grid-docs/src/features/matrixTable/components/MatrixTable.tsx

Use the default cell renderer for rendering markdoc

RTI-2219 - Fix modules table

---

documentation/ag-grid-docs/src/content/docs/excel-export-freeze/_examples/excel-export-freeze-callback/main.ts

https://ag-grid.atlassian.net/browse/RTI-2255

RTI-2255 - [excel] - fixed freeze callback example

---

documentation/ag-grid-docs/src/content/docs/group-cell-renderer/index.mdoc
documentation/ag-grid-docs/src/content/docs/group-custom-group-comp/index.mdoc
documentation/ag-grid-docs/src/content/docs/grouping-custom-group-columns/index.mdoc

See https://ag-grid.atlassian.net/browse/RTI-2247

RTI-2247 Fix and add "next up" links

---

community-modules/core/src/headerRendering/cells/abstractCell/abstractHeaderCellCtrl.ts
community-modules/core/src/headerRendering/gridHeaderCtrl.ts

https://ag-grid.atlassian.net/browse/RTI-2232

RTI-2232 - fixed warnings with column group autoHeaderHeight

---

enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/specialized/miniWaterfall.ts

https://ag-grid.atlassian.net/browse/RTI-2236

RTI-2236 - Fix minichart colours.

---

documentation/ag-grid-docs/src/content/api-documentation/grid-options/properties.json
documentation/update-algolia-indices/src/generators/api-refs.ts
documentation/update-algolia-indices/src/generators/docs-pages.ts
documentation/update-algolia-indices/src/index.ts
documentation/update-algolia-indices/src/types/algolia.ts
documentation/update-algolia-indices/src/utils/constants.ts
documentation/update-algolia-indices/src/utils/output.ts
plugins/ag-grid-generate-code-reference-files/src/executors/generate/generate-code-reference-files.ts

See https://ag-grid.atlassian.net/browse/AG-12399

AG-12399 Support nested properties in API reference parser

---

README.md
community-modules/angular/README.md
community-modules/angular/projects/ag-grid-angular/README.md
community-modules/react/README.md
community-modules/vue3/README.md
packages/ag-grid-angular/README.md
packages/ag-grid-angular/projects/ag-grid-angular/README.md
packages/ag-grid-community/README.md
packages/ag-grid-react/README.md
packages/ag-grid-vue3/README.md

Defaults to light images and removes Github specific alerts

AG-3390 Fix README's for NPM

---

community-modules/core/src/pagination/pageSizeSelector/pageSizeSelectorComp.ts
community-modules/core/src/pagination/paginationService.ts
community-modules/core/src/validation/rules/colDefValidations.ts
community-modules/core/src/validation/rules/gridOptionsValidations.ts
community-modules/core/src/validation/validationService.ts
community-modules/core/src/validation/validationTypes.ts

https://ag-grid.atlassian.net/browse/AG-10954

AG-10954 Update pagination page size validations

---

community-modules/core/src/rendering/features/stickyRowFeature.ts

https://ag-grid.atlassian.net/browse/AG-12577

AG-12577 - initialize stickyRowFeature correctly

---

documentation/ag-grid-docs/src/components/reference-documentation/components/Property.tsx
documentation/ag-grid-docs/src/components/reference-documentation/components/Section.tsx
documentation/update-algolia-indices/src/generators/api-refs.ts
external/ag-website-shared/src/components/search/SearchHits.jsx

* Add API documentation property title anchor links
* Fix search hit url for archive sites
* Fix update algolia script for text is empty

AG-12539 - Fix search links

---

community-modules/client-side-row-model/src/clientSideRowModel/clientSideRowModel.ts
community-modules/core/src/validation/rules/colDefValidations.ts
community-modules/core/src/validation/rules/gridOptionsValidations.ts
community-modules/core/src/validation/rules/selectionValidations.ts

See https://ag-grid.atlassian.net/browse/AG-12589

AG-12589 Add selection config validators

---

community-modules/core/src/rendering/cell/cellComp.ts
community-modules/core/src/rendering/cell/cellCtrl.ts
community-modules/react/src/reactUi/cells/cellComp.tsx
packages/ag-grid-react/src/reactUi/cells/cellComp.tsx

https://ag-grid.atlassian.net/browse/AG-12431

AG-12431 Tie features to comp instead of ctrl

---

documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/checkbox-selection-disable-checkboxes/provided/modules/reactFunctional/index.jsx
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/checkbox-selection-disable-checkboxes/provided/modules/reactFunctional/styles.css
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/checkbox-selection-disable-checkboxes/provided/modules/reactFunctionalTs/index.tsx
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/checkbox-selection-disable-checkboxes/provided/modules/reactFunctionalTs/styles.css
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/turn-off-checkboxes/main.ts
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/turn-off-checkboxes/provided/modules/reactFunctional/index.jsx
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/turn-off-checkboxes/provided/modules/reactFunctional/styles.css
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/turn-off-checkboxes/provided/modules/reactFunctionalTs/index.tsx
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/turn-off-checkboxes/provided/modules/reactFunctionalTs/styles.css
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/checkbox-selection-disabled-checkboxes/provided/modules/reactFunctional/index.jsx
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/checkbox-selection-disabled-checkboxes/provided/modules/reactFunctional/styles.css
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/checkbox-selection-disabled-checkboxes/provided/modules/reactFunctionalTs/index.tsx
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/checkbox-selection-disabled-checkboxes/provided/modules/reactFunctionalTs/styles.css
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/turn-off-checkboxes/provided/modules/reactFunctional/index.jsx
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/turn-off-checkboxes/provided/modules/reactFunctional/styles.css
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/turn-off-checkboxes/provided/modules/reactFunctionalTs/index.tsx
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/turn-off-checkboxes/provided/modules/reactFunctionalTs/styles.css

Provide react examples, transpilation doesn't deal well with the checkboxes

AG-12445 Fix react examples

---

community-modules/core/src/columns/columnModel.ts

See https://ag-grid.atlassian.net/browse/AG-12627

AG-12627 Fix checkbox column ordering on Firefox

---

community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
community-modules/core/src/dragAndDrop/dragAndDropService.ts
community-modules/core/src/dragAndDrop/dragService.ts
community-modules/core/src/entities/gridOptions.ts
community-modules/core/src/eventTypes.ts
community-modules/core/src/events.ts
community-modules/core/src/gridBodyComp/rowDragFeature.ts
community-modules/core/src/headerRendering/columnDrag/bodyDropPivotTarget.ts
community-modules/core/src/headerRendering/columnDrag/bodyDropTarget.ts
community-modules/core/src/headerRendering/columnDrag/moveColumnFeature.ts
community-modules/core/src/headerRendering/common/horizontalResizeService.ts
documentation/ag-grid-docs/src/content/api-documentation/grid-api/api.json
documentation/ag-grid-docs/src/content/api-documentation/grid-events/events.json
documentation/ag-grid-docs/src/content/docs/excel-export-multiple-sheets/_examples/excel-export-multiple-sheets-multiple-grids/main.ts
documentation/ag-grid-docs/src/content/docs/row-dragging/_examples/dragger-inside-custom-start-drag-pixels/main.ts
documentation/ag-grid-docs/src/content/docs/row-dragging/_examples/dragging-events/main.ts
documentation/ag-grid-docs/src/content/docs/row-dragging/index.mdoc
enterprise-modules/core/src/features/virtualListDragFeature.ts
enterprise-modules/core/src/widgets/pillDropZonePanel.ts
enterprise-modules/range-selection/src/rangeSelection/abstractSelectionHandle.ts
enterprise-modules/range-selection/src/rangeSelection/agFillHandle.ts
enterprise-modules/range-selection/src/rangeSelection/agRangeHandle.ts
enterprise-modules/range-selection/src/rangeSelection/rangeService.ts
packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
plugins/ag-grid-generate-code-reference-files/src/executors/generate/_copiedFromCore/eventKeys.ts
plugins/ag-grid-generate-example-files/src/executors/generate/generator/_copiedFromCore/eventKeys.ts

https://ag-grid.atlassian.net/browse/AG-3776
https://ag-grid.atlassian.net/browse/AG-12446

AG-3776 - added onDragCancel

---

community-modules/core/src/environment.ts
testing/behavioural/src/memory-leaks/mutation-observer.test.ts

https://ag-grid.atlassian.net/browse/AG-12636

AG-12636 Ensure all mutation observers are disconnected

---

documentation/ag-grid-docs/src/components/demos/Demos.module.scss
external/ag-website-shared/src/components/license-pricing/license-pricing.module.scss
external/ag-website-shared/src/components/product-dropdown/ProductDropdown.module.scss
external/ag-website-shared/src/components/search/SearchHits.module.scss
external/ag-website-shared/src/design-system/_root.scss

A couple of places worth reviewing before and afters:
**Search**
**Pricing**
**Homepage**

AG-12314 improve primary buttons in dark mode

---

enterprise-modules/charts/src/charts/chartComp/menu/settings/miniCharts/miniChartHelpers.ts

PR for https://ag-grid.atlassian.net/browse/AG-12725

AG-12725 - Fix typescript error

---

community-modules/core/src/rendering/cell/cellComp.ts
community-modules/core/src/rendering/cell/cellCtrl.ts
community-modules/react/src/reactUi/cells/cellComp.tsx
documentation/ag-grid-docs/src/content/docs/drag-and-drop/_examples/two-grids/main.ts

https://ag-grid.atlassian.net/browse/AG-12726

AG-12726 Revert change to cellCtrl controls

---

community-modules/core/src/columns/columnSizeService.ts

In flex sizing, total width is divided into:
1. Reserved space: space that is already taken up
2. Available space: space to be distributed between flex columns (total width - used space)
The previous flex implementation calculated reserved space from non-flex columns only. It distributed available space among flex columns, taking into account their minWidth and maxWidth. This lead to the edge case bugs described in ticket AG-12701.
This implementation calculates reserved space from both non-flex columns, _and the minimum width of flex columns_. It then distributes available space among flex columns, taking into account their maxWidth (there is no need to take minWidth into account because it is already accounted for in the reserved width).

AG-12701 [Bug] Flex minWidth columns do not size correctly when to the left of maxWidth columns

---

community-modules/core/src/selection/selectionService.ts
enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/defaultStrategy.ts
enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/groupSelectsChildrenStrategy.ts

See https://ag-grid.atlassian.net/browse/AG-12762

AG-12762 Update log messages

---

community-modules/core/src/rendering/row/rowDragComp.ts

https://ag-grid.atlassian.net/browse/AG-12793

AG-12793 Suppress validation warnings

---

community-modules/core/src/entities/gridOptions.ts
documentation/ag-grid-docs/src/content/api-documentation/grid-options/properties.json
documentation/ag-grid-docs/src/content/docs/cell-selection-api-reference/_examples/range-selection-changed-event/main.ts
documentation/ag-grid-docs/src/content/docs/cell-selection-fill-handle/index.mdoc
documentation/ag-grid-docs/src/content/docs/grouping-row-selection/index.mdoc
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/index.mdoc
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/index.mdoc
documentation/ag-grid-docs/src/content/docs/row-selection/index.mdoc

See https://ag-grid.atlassian.net/browse/AG-12445

AG-12445 Selection docs updates

---

community-modules/core/src/gridOptionsUtils.ts
community-modules/core/src/main.ts
community-modules/core/src/misc/state/stateService.ts
community-modules/core/src/selection/selectionService.ts
enterprise-modules/range-selection/src/rangeSelection/rangeService.ts
enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/defaultStrategy.ts
enterprise-modules/server-side-row-model/src/serverSideRowModel/services/serverSideSelectionService.ts
testing/behavioural/src/selection/cell-selection-grid-api.test.ts
testing/behavioural/src/selection/cell-selection-legacy-grid-api.test.ts
testing/behavioural/src/selection/row-selection-grid-api.test.ts
testing/behavioural/src/selection/row-selection-legacy-grid-api.test.ts
testing/behavioural/src/selection/row-selection-legacy-options.test.ts
testing/behavioural/src/selection/row-selection.test.ts
testing/behavioural/src/selection/utils.ts

See https://ag-grid.atlassian.net/browse/AG-12787

AG-12787 Selection grid API methods respect new selection options

---

documentation/ag-grid-docs/src/content/docs/grouping-multiple-group-columns/index.mdoc

https://ag-grid.atlassian.net/browse/RTI-2314

RTI-2314 copy changes

---

documentation/ag-grid-docs/src/content/docs/column-groups/_open-close-react.mdoc
documentation/ag-grid-docs/src/content/docs/column-groups/index.mdoc
documentation/ag-grid-docs/src/content/docs/column-headers/index.mdoc

https://ag-grid.atlassian.net/browse/RTI-2301

RTI-2301 Doc changes

---

community-modules/core/src/entities/gridOptions.ts
documentation/ag-grid-docs/src/content/docs/clipboard/index.mdoc

https://ag-grid.atlassian.net/browse/RTI-2308

RTI-2308 - fixed typos

---

documentation/ag-grid-docs/src/components/reference-documentation/components/Property.tsx
external/ag-website-shared/src/components/site-header/SiteHeader.module.scss

Also includes a fix to Sass formatting.

Rti 2218 api default value styling

---

external/ag-website-shared/src/components/documentation-archive/DocumentationArchive.module.scss

RTI-2270 Documentation archive table padding improvements

---

community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
community-modules/core/src/columns/controlsColService.ts
community-modules/core/src/entities/gridOptions.ts
community-modules/core/src/main.ts
community-modules/core/src/propertyKeys.ts
community-modules/core/src/validation/rules/gridOptionsValidations.ts
documentation/ag-grid-docs/src/components/snippet/snippetTransformer.ts
documentation/ag-grid-docs/src/content/api-documentation/grid-options/properties.json
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/_examples/customise-checkbox-column/main.ts
documentation/ag-grid-docs/src/content/docs/row-selection-multi-row/index.mdoc
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/_examples/customise-checkbox-column/main.ts
documentation/ag-grid-docs/src/content/docs/row-selection-single-row/index.mdoc
packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
plugins/ag-grid-generate-example-files/gridOptionsTypes/_gridOptions_Types.json

https://ag-grid.atlassian.net/browse/RTI-2330

RTI-2330 Rename controlsColDef to selectionColDef

---

community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
community-modules/core/src/entities/gridOptions.ts
community-modules/core/src/main.ts
packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
plugins/ag-grid-generate-example-files/gridOptionsTypes/_gridOptions_Types.json

https://ag-grid.atlassian.net/jira/software/projects/RTI/boards/23?selectedIssue=RTI-2330

SelectionColDef -> SelectionColumnDef
