ag-grid/ag-grid

- bower.json
I use an automatic wiring logic based on bower.json meta information. It would be nice if you could merge this fix.
Thanks
> fix bower.json references

- src/js/paginationController.js
When pagination is enabled and `rowCount` is null, `calculateTotalPages()` blows up because of the check in this line. This fix makes sure that `rowCount` is always a number.
> Fix pagination error when rowCount is null

- src/js/headerRenderer.js
- src/js/inMemoryRowController.js
Related to issue #98 
Let me know if there are any requested changes (any functions that you want split, if `shiftKey` (as in, e.shiftKey) should be a constant/configurable, etc.)
> Allow sorting by multiple columns (by holding shift)

- src/js/grid.js
I take a quick look at how you implemented the row scroll via ensureIndexVisible(index), and provide a similar implementation for the column scroll. I modify ensureIndexVisible method to pass in an optional colIndex parameter. I tested and verify that this change works well for me, so I just want to share the code changes for you to review (and to include in next release if you are ok with it).
I did not change the original "index" parameter name to "rowIndex", so please update the parameter name as you see fit.
> Scroll to Column #137

- docs/angular-grid-column-definitions/index.php
- docs/angular-grid-icons/index.php
- docs/angular-grid-sorting/example1.js
- src/js/headerRenderer.js
- src/js/svgFactory.js
Hi. I implemented an optional icon when a column is unsorted (activated at a column level). This is popular with [other grids](https://www.datatables.net/examples/basic_init/table_sorting.html)
Summary of changes:
- Add class to Asc & Desc Icons containers (to style them better)
- Add unSortIcon option to columns: if true an unSort Icon is shown when the column is not sorted
- Icon can be customised with gridOptions.icon.sortUnSort (excellent to use something like `<i class="fa fa-sort"></i>` from font-awesome
- Add SVG factory for the unSort Icon
- Adjusted Documentation (including one example)
> UnSort Icon

- src/ts/columnController.ts
- src/ts/filter/filterManager.ts
- src/ts/renderedCell.ts
- src/ts/utils.ts
Hi!
Created TypeScript type definition for ColDef based on the documentation and the code itself. In two or three cases TypeScript compiler couldn't figure out what to use from union types, so had to add a few explicit casts. Or had to reorder type checking so tsc can figure out the actual type used with union types. This union type handling should improve in TS 1.5.
Also added some  generics to the array/object iteration functions the utils.ts. Therefore some `any` typedefs could be could removed from the usage of those functions, but getting actual type safety based on the type of the array.
The generated javascript is pretty much the same as before, "dist" file not changed.
> Some typescript definitions

- docs/angular-grid-sorting/index.php
- src/ts/rowControllers/inMemoryRowController.ts
We have a use case where we are flattening a parent-child hierarchy in the grid. The custom sort treats all children as if they have the same values as their parent so when sorting children are always next to their parents. To do this we need to know if the sort is ASC or DESC as children need to always be below their parent no matter the direction of the sort
> Adding isInverted parameter to the signature of the column comparator

- src/ts/filter/setFilter.ts
- src/ts/filter/setFilterModel.ts
SetFilter's with a newRowsAction of 'keep' should always select all filter values when the select All checkbox is checked.
To recreate the problem:
* rowdata = [{status:'A'}, {status:'B'}, {status:'C'}]
* Click filter menu on status column
* Uncheck select all
* Check select all
* Add new row to dataset {status:'D'}
* New row is not shown
* clicking on the filter menu shows status A.B,C selected and D unchecked
> #363 Bug with SetFilters when newRowsAction as keep and selectAll checkbox selected

- src/ts/utils.ts
First of all, let me just say what a wonderful piece of software you have written! I am in the middle of a fairly large project and was having some issues with ui-grid, and was in fact thinking of creating a grid from scratch when I stumbled on to ag-grid. It blows away any ideas I had and I have incorporated it into my project beautifully. Thank you! 
As to this pull-request, it came about because I was having a problem when applying a filterModel (with api.setFilterModel). Tracing the problem, I found that within the function setFilterModel, as it iterates over "allFilters", it removes from "modelKeys" based on the "colid" (by calling Utils.removeFromArray). However, in the "removeFromArray" function, it splices the array based on the return of "indexOf". When indexOf does not find a …
> Changed removeFromArray so it only removes "found" items

- docs/angular-grid-api/index.php
- src/ts/gridApi.ts
- src/ts/rendering/rowRenderer.ts
Add getRenderedNodes to grid api. Use case for this is to update volatile columns only when their row is shown in the grid
http://www.angulargrid.com/forum/showthread.php?tid=2734
> Expose renderedRows on gridApi

- docs/angular-grid-internationalisation/index.php
- src/ts/entities/gridOptions.ts
- src/ts/gridOptionsWrapper.ts
It is currently not possible to integrate a translation service with
the ag-grid because the ag-grid assumes a translation table in the
form of a key/value map. A component like the angular-translate
provides a function that will allow a key to be translated but it
does not expose its internal map.
This commit makes it possible to declare a localeTextFunc function
in the gridOptions. When declared, this function will be returned
by the GridOptionsWrapper.getLocaleFunc() method.
> Enable declaration of localeTextFunc in gridOptions

- src/ts/csvCreator.ts
First of all, I don't know if this is worth a pull request, but I guess
you'll be the judge of that. I'll try to explain the 'why' behind my
(small) change:
It appears that Microsoft Excel sometimes doesn't open CSV files just
right. It appears it might have another character as a separator in the
default options (or if you change them). This is easily worked around
defining, in the first line of the file:
sep=<your_separator>
which in this case translates to:
sep=,
More info:
http://kb.paessler.com/en/topic/2293-i-have-trouble-opening-csv-files-with-microsoft-excel-is-there-a-quick-way-to-fix-this
I also checked on other spreadsheet software, but the few I checked
(OpenOffice and GoogleDocs) aren't suffering from this. Therefore I
added another option to params by which you can tell the …
> Added option and functionality for comma separating

- src/ts/csvCreator.ts
This should fix - https://github.com/ceolter/ag-grid/issues/501
Same method as ng-csv is doing.
> fix(csvExport): large data export need createObjectURL

- docs/angular-grid-cell-rendering/index.php
I found out from angular-grid-angular-compiling/index.php example that params object exposes a node parameter that was not documented.
So this is a proposal to fix the documentation.
> Add documentation for params.node

- src/ts/gridApi.ts
The deselectNode function of the gridApi did not pass down the suppressEvents parameter to the selectionController.
> deselectNode should pass down suppressEvents parameter

- src/ts/columnController/columnController.ts
Due to a bug in my application code (was trying to call `getValue` for a field that doesn't have a rendered column), I discovered that the column controller is attempting to look up a `null` column's colDef. 
Calling `getColumn` with a key that does not belong to any of the columns in `allColumns` results in dropping down to the next check: `colMatches(this.groupAutoColumn)`. There's no check whether `this.groupAutoColumn` is null, so an exception can be thrown when trying to then call `getColDef` on that object.
Obviously `getColumn` will return null when you call it with an invalid key, but I don't think throwing this exception is appropriate.
> bug fix - prevent exceptions when looking up columns

- src/ts/rowControllers/inMemoryRowController.ts
while `recursivelyCheckUserProvidedNodes()`
when `suppressParentsInRowNode` is set to `true`
and `rowsAlreadyGrouped` is set to `true`
improves 8d83ff40e70cebe801025db9f629671b6627b64f
> fix(inMemoryRowController): skip add parents

- src/ts/rendering/renderedRow.ts
The compiling of rows should go after the processRowPostCreate callback (#751, #753)
> Moved compiling of Rows after processRowPostCreate Callback

- src/ts/gridPanel/gridPanel.ts
I have implemented dragging rows out of the grid for further use using the new processRowPostCreate callback.
This can only work if the 'dragstart' event is not prevented in all cases. Now 'dragstart' is only prevented for images.
> DisableBrowserDragging only if target is of type HTMLImageElement

- gulpfile.js
- src/styles/theme-blue.styl
- src/styles/theme-bootstrap.styl
- src/styles/theme-common.styl
- src/styles/theme-dark.styl
- src/styles/theme-fresh.styl
- src/styles/theme-material.styl
I would like to propose small change to make theming more flexible. 
Right now theming works as follow: 
- there is one file `theme-common.styl` that defines all common styles but requires some variables to be defined
- every theme defines all variables required by `theme-common.styl` and then includes this file
- as a result css file is generated with root class name `.ag-common`
- this magic class name is replaced on the fly by gulp task to match theme name eg. `.ag-blue`
This works fine but this is also a limitation. It is hard to create another theme by importing `theme-common.styl` one need to remember to replace this static class name.
As a solution to that problem I would like to propose dynamic class name generation. Every theme file has already variable named `ag-style` with …
> Fix to theme-common making theming more flexible

- src/ts/columnController/columnController.ts
I noticed when I called sizeColumnsToFit after autoSizeColumns, where, in our case, only the 3 left most columns aren't marked as suppressSIzeToFit, some columns would take up more width than necessary, and a column with a max-width & length content would not be getting as much as it could be.  What I did to fix this in our code was move the line `pixelsForLastCol -= newWidth;` outside of the if/else statements (so that it was the last line called in each iteration of the for loop), otherwise the pixelsForLastCol was too large because it wasn't subtracting available width in the case that the column was being set to either max or min width, and then being 'movedToNotSpread'
example plnkr:
[http://embed.plnkr.co/AcePXER70SerPXEsDgLi?p=info](http://embed.plnkr.co/AcePXER70SerPXEsDgLi?p=info) …
> Moved substraction of available pixels for the last column in sizeColumnsToFit to bottom of for loop

- src/ts/filter/textFilter.ts
TextFilter.prototype.doesFilterPass returns false if !value. This means that empty strings never pass a filter. However, when using TextFilter.NOT_EQUALS, empty strings should satisfy any non-empty filter text. As filterText is tested for empty values prior to the node value check, we are guaranteed at this point that the filterText is non-empty, so an empty node value should return true.
> NOT_EQUALS text filter type should include empty strings

- src/styles/theme-blue.styl
- src/styles/theme-bootstrap.styl
- src/styles/theme-dark.styl
- src/styles/theme-fresh.styl
- src/styles/theme-material.styl
At least, it appears to be unused, if I'm not mistaken.
> removes unused `ag-background-2` variable

- src/ts/gridPanel/gridPanel.ts
Fix for #1333 and #1386 
Hi @ceolter,
I had the issue described in 1333. When I debug through the `sizeColumnsToFit` function, I've noticed that, when having both a vertical and horizontal scrollbar, `this.isBodyVerticalScrollShowing();` is true and thus reduces the `availableWith`. When only having a vertical scrollbar, `this.isBodyVerticalScrollShowing();` is false and used the full client witdh. Using the below function seems to fix the problem. It also works correctly when having a column pinned right.
I was thinking about changing `this.isBodyVerticalScrollShowing()`, perhaps the `else` function should be changed.
Tested on chrome v 55.0.2883.87
> Fix calculation for sizeColumnsToFit

- src/ts/entities/gridOptions.ts
Please take the following issue as reference: https://github.com/ceolter/ag-grid/issues/1563
According to the documentation the paginationAutoPageSize field should be a boolean.
In the ComponentUtil Class it is already part of the BOOLEAN_PROPERTIES
Enum. Thats why this PR only consists of the gridOptions update.
> fix(gridOptions): set type of paginationAutoPageSize to boolean

- src/ts/components/componentUtil.ts
- src/ts/gridOptionsWrapper.ts
We were finding that when using agGrid with React, the **cacheBlockSize** prop was being ignored when using the infinite scroll row model. This is because the grid options (which are passed via props to React) are being copied in copyAttributesToGridOptions() in ComponentUtil. However this function only copies over grid options it's aware of and the collection of keys does not contain **cacheBlockSize**, instead it contains **infiniteBlockSize** twice. 
As a result, if using agGrid with React with the infinite scroll row model, then the **cacheBlockSize** was always defaulting to 100 no matter what was passed as a prop. This meant that the dataSource getRow() function was always called with 100 row blocks.
> Ensure cacheBlockSize is copied in ComponentUtil.copyAttributesToGridOptions

- packages/ag-grid-vue/src/vueComponentFactory.js
- packages/ag-grid-vue/src/vueFrameworkComponentWrapper.js
- #2641 is a side-effect of `createAndMountComponent` not instantiating
the component with the parent.
- The parent is available to `VueComponentFactory` as `this.parent`
- This PR adds a `parent` argument to `createMountComponent` so that
the received parameter can be used to instantiate the component.
- Method calls to `createAndMountComponent` have been adjusted
accordingly.
> fixes #2641.

- packages/ag-grid-enterprise/src/chartAdaptor/chartComp/chartProxies/cartesian/areaChartProxy.ts
- packages/ag-grid-enterprise/src/chartAdaptor/chartComp/chartProxies/cartesian/barChartProxy.ts
- packages/ag-grid-enterprise/src/chartAdaptor/chartComp/chartProxies/cartesian/lineChartProxy.ts
- packages/ag-grid-enterprise/src/chartAdaptor/chartComp/chartProxies/cartesian/scatterChartProxy.ts
- packages/ag-grid-enterprise/src/chartAdaptor/chartComp/chartProxies/polar/doughnutChartProxy.ts
- packages/ag-grid-enterprise/src/chartAdaptor/chartComp/chartProxies/polar/pieChartProxy.ts
- packages/ag-grid-enterprise/src/charts/axis.ts
- packages/ag-grid-enterprise/src/charts/chart/axis/groupedCategoryAxis.ts
- packages/ag-grid-enterprise/src/charts/chart/cartesianChart.ts
- packages/ag-grid-enterprise/src/charts/chart/groupedCategoryChart.ts
- packages/ag-grid-enterprise/src/charts/chart/series/barSeries.ts
- packages/ag-grid-enterprise/src/charts/chartBuilder.ts
- packages/ag-grid-enterprise/src/charts/chartOptions.ts
First step of moving the ChartBuilder into the charts module along with copies of relevant interfaces. Once this is done we can start to evolve the charts API and the grid options API separately, with the proxies translating into the options interfaces required when calling the ChartBuilder.
> AG-3327 - move ChartBuilder into charts module

- community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-column.component.ts
- community-modules/core/src/ts/entities/colDef.ts
- community-modules/core/src/ts/entities/gridOptions.ts
- community-modules/core/src/ts/main.ts
- grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-column.component.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/column-properties/properties.json
- grid-packages/ag-grid-docs/documentation/doc-pages/row-styles/index.md
Been through GridOptions and ColDef and replaced a number of `any` options with their existing type where this is obvious from the source code.
> Ag 3944 add existing but missing interfaces

- community-modules/core/src/ts/rendering/cell/cellComp.ts
Since version 26 the return value from getPopupPosition gets ignored, resulting in the cell editor using the default value 'over'.
> Fix ignored return value from getPopupPosition

- community-modules/core/src/ts/styling/stylingService.ts
I was investigating some rendering perf issues in our app. Turns out we were spending a lot of time in `processClassRules`. (To be fair, we're doing silly things with ~25 cell class rules that aren't actually useful.) I came across this code.
Currently it is (accidentally?!) quadratic. With every iteration of the loop we remove and add all previous (unique) classes. The comment makes me think that's not necessary. We can collect classes and only apply them at the very end. This also matches the scope of `classesToApply` and `classesToRemove`.
I believe this is what @ceolter intended in 6eec566babc8e33d185ab8cd24ab858a96793856 all along, the `}` just got misplaced. Note though that I haven't actually executed a grid instance with this patch applied, so I'm opening this as a draft PR.
> Fix cellClassRules quadratic perf

- grid-packages/ag-grid-docs/documentation/src/components/expandable-snippet/ExpandableSnippet.module.scss
- grid-packages/ag-grid-docs/documentation/src/components/expandable-snippet/ExpandableSnippet.tsx
- grid-packages/ag-grid-docs/documentation/src/components/expandable-snippet/__snapshots__/ExpandableSnippet.test.tsx.snap
https://ag-grid.atlassian.net/browse/AG-6440
Applies the following tweaks to the `ExpandableSnippet` rendering (now used for Standalone Charts API docs since 27.1.0):
- Switches to use of a chevron for the node expander, for consistency with the rest of the AG Grid documentation.
- Adds a line under the chevron to help visually indicate the scope of expanded content.
- Removes repeated SVG rendering for FontAwesome icons.
Before:
After:
> AG-6440 - Cleanup ExpandableSnippet rendering.

- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- fixed stacked area chart not showing a point for a series
- fixed stacked chart domain when undefined values present in data
> AG-5837 - Area series missing values

- charts-packages/ag-charts-community/src/chart/agChartV2.test.ts
- charts-packages/ag-charts-community/src/chart/galleryExamples.test.ts
- charts-packages/ag-charts-community/src/chart/test/utils.ts
https://ag-grid.atlassian.net/browse/AG-6507
Follow-up to #4982 - stub `Canvas` creation to try and fix test failure on CI.
Also opens the door for more `canvas` tweaking to support https://ag-grid.atlassian.net/browse/AG-6481.
> AG-6507 - Stub HdpiCanvas Canvas creation for Charts visual tests.

- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/api.json
- grid-packages/ag-grid-docs/documentation/src/components/documentation-overrides.test.ts
- grid-packages/ag-grid-docs/documentation/src/components/expandable-snippet/model.ts
https://ag-grid.atlassian.net/browse/AG-6549
Adds test coverage to all doc override JSON files, specifically to detect:
- Overrides for types that no longer exist or have mismatched names.
- Overrides for properties that don't exist.
The intent is to put some CI-time safeguards into place for drift in manually maintained JSON files vs. the types they decorate, especially since the recent Chart API documentation improvements rely on the correctness of these overrides.
Bonus:
- Fixes one mismatching override which should have been embedded in a `meta` property.
> AG-6549 - Add override json validation.

- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Chart.module.scss
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Chart.tsx
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/ChartsApiExplorer.module.scss
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/ChartsApiExplorer.tsx
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/CodeView.tsx
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Launcher.module.scss
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Launcher.tsx
https://ag-grid.atlassian.net/browse/AG-6569
Adds support for opening the Charts API Explorer full-screen:
- The entire explorer component, or...
- The chart preview.
Bonus:
- Fixes some alignment issues I noticed in the Chart API Explorer components.
- Moves the toolbar to the top of the explorer as per out-of-band review feedback.
New toolbar:
Full-screen:
Chart full-screen:
> AG-6569 - Add Chart API Explorer full-screen display.

- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- community-modules/core/src/ts/interfaces/iAgChartOptions.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/api.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/ChartsApiExplorer.module.scss
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Editors.tsx
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Options.tsx
https://ag-grid.atlassian.net/browse/AG-6654
Primary changes:
- During re-render we are reloading and rebuilding the entire `JsonModel` - this change seeks to remove this calculation from the re-render path by introducing caching. (https://github.com/ag-grid/ag-grid/pull/5070/commits/1011e6526b721fa5743895a3806110745e78de51)
- Fixes small-screen rendering of the API Explorer - we no longer continue squishing things to the point of uselessness, but add scroll-bars to allow the content to be moved into view. (https://github.com/ag-grid/ag-grid/pull/5070/commits/aaae9d3f5f6d1dea8628cbbfc1971def6f3eae4e)
- Makes the chart `theme` configurable interactively and adds JSDoc description for the field to improve self-documentation. (https://github.com/ag-grid/ag-grid/pull/5070/commits/c81b4bd403cff …
> AG-6654 - Charts API Explorer Caching + Visual Improvements

- charts-packages/ag-charts-community/src/chart/chart.ts
https://ag-grid.atlassian.net/browse/AG-6119
Fix pointer rendering when hovering over a legend item - we now use the the `pointer` cursor type (aka link-hover pointer type).
> AG-6119 - Highlight Charts legend items are clickable

- community-modules/core/src/ts/interfaces/iSparklineCellRendererParams.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-6674
Correct `fontSize` type to be consistent with the implementation AND standalone charts.
> AG-6674 - Fix sparklines label `fontSize` type

- enterprise-modules/charts/src/charts/chartComp/chartTitle/titleEdit.ts
https://ag-grid.atlassian.net/browse/AG-6119
Integrated charts proxy was forcing the setting of `style.cursor` on every mouse-move event, which was overwriting standalone charts updates - preventing legend hover style changes in the first case.
> AG-6119 - Fix Integrated Charts proxy override of cursor style unless necessary.

- grid-packages/ag-grid-docs/documentation/doc-pages/row-pagination/index.md
Hi, 
I just start using ag-grid and really like the library and the documentation 🙏🏻
While reading the documentation I found a tiny typo, so this is a fix.
Link to relevant page in the documentation: https://www.ag-grid.com/angular-data-grid/row-pagination/
Thank you, Michal Porag.
> fix tiny typo

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- community-modules/core/src/ts/interfaces/iAgChartOptions.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/api.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/examples/axis-label-rotation/data.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/examples/axis-label-rotation/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/examples/axis-label-rotation/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/examples/axis-label-rotation/styles.css
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Editors.tsx
https://ag-grid.atlassian.net/browse/AG-6761
Adds docs and an example that demonstrate how `rotation`, `autoRotate` and label skipping interact together.
> AG-6761 - Add label auto-rotate & skip docs

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- community-modules/core/src/ts/interfaces/iAgChartOptions.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/api.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-6769
Splits the union type of `autoRotate` into two distinct properties:
- `autoRotate: boolean` to toggle auto-rotation on/off.
- `autoRotateAngle: number` to configure the angle auto-rotation should use (defaults to `335`).
Tested:
- Plunker example for Label rotation.
- Adhoc addition of `autoRotateAngle`.
- Chart API explorer.
-  Edit in Plunker with adhoc addition of `autoRotateAngle`.
> AG-6769 - Add Charts Axis Label autoRotateAngle property.

- charts-packages/ag-charts-community/src/chart/markerLabel.ts
- charts-packages/ag-charts-community/src/scene/clipRect.ts
- charts-packages/ag-charts-community/src/scene/dropShadow.ts
- charts-packages/ag-charts-community/src/scene/group.ts
- charts-packages/ag-charts-community/src/scene/node.ts
- charts-packages/ag-charts-community/src/scene/shape/arc.ts
- charts-packages/ag-charts-community/src/scene/shape/line.ts
- charts-packages/ag-charts-community/src/scene/shape/path.ts
- charts-packages/ag-charts-community/src/scene/shape/rect.ts
- charts-packages/ag-charts-community/src/scene/shape/sector.ts
- charts-packages/ag-charts-community/src/scene/shape/shape.ts
- charts-packages/ag-charts-community/src/scene/shape/text.ts
https://ag-grid.atlassian.net/browse/AG-6786
Replace repeated change-detection `set`/`get` pattern with a simple field declarataion and an annotation to implement generic (but functionally equivalent) change detection processing.
> AG-6786 - Remove redundant boilerplate change-detection get/set.

- grid-packages/ag-grid-docs/documentation/doc-pages/dom-virtualisation/index.md
On the [documentation page for DOM virtualisation](https://www.ag-grid.com/javascript-data-grid/dom-virtualisation/) there's a typo, the word 'Virtualisation' is spelt incorrectly:
> fix typo in DOM virtualisation documentation

- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
https://ag-grid.atlassian.net/browse/AG-6791
Refactor per-datum contract for `Series.getOpacity()` to allow simplification/optimisation of where opacity is applied.
This is a follow-up to #5216.
> AG-6791 -Refactor Charts series opacity calculation.

- grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-editor/_keyboard-option-1-javascript.md
- grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-editor/_keyboard-option-1-react.md
- grid-packages/ag-grid-docs/documentation/doc-pages/component-cell-editor/_keyboard-option-1-vue.md
"keyCode" variable was renamed to "key" in a previous commit, but a few instances of "keyCode" remained.
> Fix example documentation for cell editor stopping propagation.

- charts-packages/ag-charts-community/src/canvas/hdpiCanvas.ts
- charts-packages/ag-charts-community/src/canvas/hdpiOffscreenCanvas.ts
- charts-packages/ag-charts-community/src/chart/chart.ts
- charts-packages/ag-charts-community/src/chart/legend.ts
- charts-packages/ag-charts-community/src/chart/marker/marker.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
- charts-packages/ag-charts-community/src/chart/shapes/rangeSelector.ts
- charts-packages/ag-charts-community/src/scene/group.ts
- charts-packages/ag-charts-community/src/scene/matrix.ts
- charts-packages/ag-charts-community/src/scene/node.ts
- charts-packages/ag-charts-community/src/scene/path2D.ts
- charts-packages/ag-charts-community/src/scene/scene.ts
- charts-packages/ag-charts-community/src/scene/shape/path.ts
- charts-packages/ag-charts-community/src/scene/shape/shape.ts
- charts-packages/ag-charts-community/src/scene/shape/text.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-6820
Attempts to address scaling issues with the Charts scene rendering which were identified whilst testing in the O(50K->150K) range. Focuses on line, area and scatter series as the types most likely to see use with very large data-sets:
- Switches to use of `OffscreenCanvas` + `ImageBitmap` APIs and bitmap copying of layers to main canvas for better rendering performance when a large number of points are rendered.
- Adds support to `Group` for an optimised dirty-check path, for groups where the number of visible/dirty elements is typically a low % of the total children. This is important for highlight series, where only one node will be visible / dirty at a time.
- Inlines more `@SceneChangeDetection` cases for better execution performance.
- …
> AG-6820 - Further Chart rendering optimisations for larger data-sets

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/chart.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/scene/group.ts
- charts-packages/ag-charts-community/src/scene/node.ts
- charts-packages/ag-charts-community/src/scene/scene.ts
https://ag-grid.atlassian.net/browse/AG-6820
Improves:
- Up-to halves the number of series scene nodes by reducing the highlight series node count to 0/1.
- Memory churn in some cases (unnecessary `.slice()` use and destructuring in some tight / high-volume loops).
- `LineSeries` and `AreaSeries` datum highlight performance by ~40ms and 5ms respectively, with 150K data-points.
> AG-6820 - Further Chart rendering optimisations

- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- community-modules/core/src/ts/interfaces/iAgChartOptions.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-constraints/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-constraints/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
This PR is for https://ag-grid.atlassian.net/browse/AG-5160.
The charts legend constraints example has been updated to include the new `maxWidth` property. The legend docs page has also been updated.
> AG-5160 - Charts legend docs example updates

- charts-packages/ag-charts-community/src/chart/mapping/prepareSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
Attempts to make `visible: false` behave more consistently across series. After this change, setting `visible: false` means that series will appear as if they have been toggled disabled from the legend.
> AG-5740 - Add more consistent series.visible handling.

- charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
- charts-packages/ag-charts-community/src/scene/group.ts
- charts-packages/ag-charts-community/src/scene/node.ts
- charts-packages/ag-charts-community/src/scene/scene.ts
https://ag-grid.atlassian.net/browse/AG-6887
Whilst reviewing the z-order changes made for `28.0.0` it became clear there were some easily achievable improvements, which are captured as part of this PR:
- Highlighted series is now temporarily bumped in `zIndex`, so hidden series can be more easily seen when hovering over the series itself or it's legend item.
- Highlighted datum rendering is at a higher `zIndex` than all series, so highlighted datum can be easily seen. (No change in this PR - just stating new `28.0.0` behaviour which has been approved)
Bonus:
- Cleanup Group and Scene `zIndex` processing.
> AG-6887 - Series highlight z-order improvements

- charts-packages/ag-charts-community/src/chart/cartesianChart.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/chart/series/polar/polarSeries.ts
- charts-packages/ag-charts-community/src/chart/series/seriesMarker.ts
- charts-packages/ag-charts-community/src/scene/changeDetectable.ts
- charts-packages/ag-charts-community/src/scene/dropShadow.ts
- charts-packages/ag-charts-community/src/scene/node.ts
- charts-packages/ag-charts-community/src/scene/shape/line.ts
- charts-packages/ag-charts-community/src/scene/shape/path.ts
- charts-packages/ag-charts-community/src/scene/shape/shape.ts
- charts-packages/ag-charts-community/src/util/json.test.ts
- charts-packages/ag-charts-community/src/util/json.ts
https://ag-grid.atlassian.net/browse/AG-6924
Fixes some edge-cases in option update change detection:
- `Series.lineDash` changes now correctly detected during factory json-diff phase.
- `Series.fillShadow` and `Series.strokeShadow` changes now correctly get detected as scene changes.
- `Series.marker` changes now correct detected and refreshed during scene selection update phase.
There maybe other cases, but we should be able to handle them following the patterns established here after we find them in testing.
> AG-6924 - Fix Chart update cases

- grid-packages/ag-grid-docs/documentation/doc-pages/grid-interface/_index-angular.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-interface/_index-react.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-interface/_index-vue.md
Currently it's not very clear what happens if you specify an option on the gridOptions and with a framework binding
https://www.ag-grid.com/angular-data-grid/grid-interface/#grid-options-1
I took a look at the source code and it looks like (and I can also confirm this from my testing) that the values from the framework bindings will override the settings made in gridOptions
https://github.com/ag-grid/ag-grid/blob/latest/grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts#L204
> Improved documentation for gridOptions and framework bindings

- charts-packages/ag-charts-community/src/chart/series/series.ts
- charts-packages/ag-charts-community/src/scale/continuousScale.ts
- charts-packages/ag-charts-community/src/scale/timeScale.ts
- charts-packages/ag-charts-community/src/util/numberFormat.ts
https://ag-grid.atlassian.net/browse/AG-6708
Fixes `TimeAxis` domain detection when there are no data points.
Before (https://plnkr.co/edit/GoGbXTUjclhDu3oe?open=main.js):
After (https://plnkr.co/edit/vkbStfixLc0Tp3WR?open=main.js):
Verified that switching to `line`, `scatter`, `area` and `column` all work correctly with zero data points too.
Bonus:
- Improved readability of some uses of `Array.prototype`.
> AG-6708 - Fix no data time axis range

- charts-packages/ag-charts-community/src/chart/series/hierarchy/treemapSeries.ts
https://ag-grid.atlassian.net/browse/AG-6594
Fixes `TreemapSeries` handling of `Label.enabled`.
> AG-6594 - Fix TreeMap label.enable.

- community-modules/core/src/ts/widgets/touchListener.ts
Causes the error:
IgnoredEventCancel: intervention: Ignored attempt to cancel a touchend event with cancelable=false
Internal ticket:
https://ag-grid.zendesk.com/hc/en-us/requests/23283
> Only prevent default on cancelable touch events

- charts-packages/ag-charts-community/src/chart/chart.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/chart/series/hierarchy/hierarchySeries.ts
- charts-packages/ag-charts-community/src/chart/series/polar/polarSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
https://ag-grid.atlassian.net/browse/AG-5738
As per [this analysis](https://ag-grid.atlassian.net/browse/AG-5738?focusedCommentId=43170), changes tooltip / node selection on hover to:
- For scatter series with number axes - pick closest datum.
- For scatter series with one or more category axes - pick closest X/Y category and then closest datum on that category.
- For bar/column series - pick only on hover-over a bar/column.
- For everything else - pick closest by X-axis value, then by Y-axis (when multiple series are present).
Bonus:
- Reworks the tooltip handling code to improve readability and simplify.
> AG-5738 - Improved tooltip handling

- charts-packages/ag-charts-community/src/chart/agChart.test.ts
- charts-packages/ag-charts-community/src/chart/test/utils.ts
- charts-packages/ag-charts-community/src/interpolate/color.test.ts
- charts-packages/ag-charts-community/src/scale/bandScale.test.ts
- charts-packages/ag-charts-community/src/scale/linearScale.test.ts
- charts-packages/ag-charts-community/src/scale/logScale.test.ts
- charts-packages/ag-charts-community/src/scale/ordinalScale.test.ts
- charts-packages/ag-charts-community/src/scene/matrix.test.ts
- charts-packages/ag-charts-community/src/scene/node.test.ts
- charts-packages/ag-charts-community/src/scene/path.test.ts
- charts-packages/ag-charts-community/src/util/color.test.ts
- charts-packages/ag-charts-community/src/util/number.test.ts
- charts-packages/ag-charts-community/src/util/numberFormat.test.ts
- charts-packages/ag-charts-community/src/util/object.test.ts
- charts-packages/ag-charts-community/src/util/secondaryAxisTicks.test.ts
- charts-packages/ag-charts-community/src/util/string.test.ts
- charts-packages/ag-charts-community/src/util/ticks.test.ts
- charts-packages/ag-charts-community/src/util/time/format/locale.test.ts
- charts-packages/ag-charts-community/src/util/time/minute.test.ts
- charts-packages/ag-charts-community/src/util/time/week.test.ts
- charts-packages/ag-charts-community/src/util/value.test.ts
- charts-packages/ag-charts-community/tsconfig.cjs.es5.json
- charts-packages/ag-charts-community/tsconfig.cjs.es6.json
- charts-packages/ag-charts-community/tsconfig.esm.es5.json
- charts-packages/ag-charts-community/tsconfig.esm.es6.json
- charts-packages/ag-charts-community/tsconfig.test.json
Enabled stricter `tsconfig.json` compiler options, to highlight low-hanging SonarCloud issues more proactively.
Bonus:
- Fixes all current violations of these new rules.
> Enable `noUnused*` TSConfig rules for Charts.

- enterprise-modules/sparklines/src/sparkline/sparkline.ts
Don't break out of the loop early when finding closest node during highlighting as this approach breaks in the case where the provided sparkline data is not ordered
> AG-6671 - Fix sparklines item highlighting

- charts-packages/ag-charts-community/src/chart/crossline/crossLine.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/chart/themes/chartTheme.ts
- charts-packages/ag-charts-community/src/util/value.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/index.md
- Validate the values supplied to cross lines 
- Only clamp values for range cross lines
- Do not display line for clamped range boundaries
- Do not display line cross lines outside of the axis domain
- Make crossLine invisible if update results in no path data
- Update crossLine docs
- Set the default enabled values for cross lines and cross line label to false in chartTheme
> Ag 5105/cross lines

- grid-packages/ag-grid-docs/documentation/doc-pages/column-menu/index.md
Minor style fix - stumbled across it when copying menuTabs options from the docs.
> fix(docs) minor space fix in column menu docs

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/axis/categoryAxis.ts
- charts-packages/ag-charts-community/src/chart/axis/groupedCategoryAxis.ts
- charts-packages/ag-charts-community/src/chart/axis/numberAxis.ts
- charts-packages/ag-charts-community/src/chart/axis/timeAxis.ts
- charts-packages/ag-charts-community/src/chart/cartesianChart.ts
- charts-packages/ag-charts-community/src/chart/chartAxis.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
- charts-packages/ag-charts-community/src/util/array.ts
https://ag-grid.atlassian.net/browse/AG-6133
Adjusted rendering of axes to be more consistent when no series is displayed:
- Axis lines + titles now always render.
- Category axes + ticks always render (unchanged).
- If  axis `min`, `max` or `domain` properties are specified, axis ticks and labels are always rendered.
Bonus fixes:
- Starting with `visible: true` now renders consistently with disabling all series from the legend.
- `Axis.update()` is now decomposed into a few different methods to reduce its complexity.
- Fixes `TimeAxis.domain` handling (specified domain was ignored previously).
Still TODO:
- Add test coverage for all cases above to `axisExamples.test.ts`.
Demo Plunker: https://plnkr.co/edit/kiO6RztUm4MAiSFD?open=main.js
> AG-6133 - Improve axes rendering when no series enabled

- charts-packages/ag-charts-community/src/chart/cartesianChart.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/util/array.ts
https://ag-grid.atlassian.net/browse/AG-7054
Fixes `NaN` in the `BarSeries.processData()`  causing all stacked-series `y` calculations to also resolve to `NaN`.
Looks like this was probably a result of the change here: https://github.com/ag-grid/ag-grid/pull/5396/files#diff-84e11554c8f4be20782e7971d008d090fa7cbf2b8d2329863f0c386903961b9fR377
Bonus:
- Found some redundant calls triggering series data reprocessing in the `Chart.performLayout()` code - removed these since we're typically already doing this at the next stage in `Chart.performUpdate()` processing.
> AG-7054 - Fix disabled stack bar series hides all series

- charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
https://ag-grid.atlassian.net/browse/AG-7062
Attempts to fix series label obstruction by highlighted datum.
Adds a special group for highlighted item labels (in the same layer as the existing highlight, but higher z-index) to render an unobscured label for the highlighted datum. We then follow a similar processing pattern as for highlighted items - i.e. identifying the 0 or 1 highlighted label datum, and then updating the special highlighted item label selection with this.
> AG-7062 - Add series highlight label handling.

- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- charts-packages/ag-charts-community/src/chart/legend.ts
- community-modules/core/src/ts/interfaces/iAgChartOptions.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-formatters/examples/legend-item-formatter/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-formatters/examples/legend-item-formatter/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-formatters/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-7123
Improves the documentation around `legend.item.formatter`, including correcting parameter definitions to align with reality.
> AG-7123 - Fix legend formatter definition

- charts-packages/ag-charts-community/src/chart/chart.ts
https://ag-grid.atlassian.net/browse/AG-7195
Looks like padding values were accumulating in `legendAutoPadding` as the legend position was changed - made an adjustment to clear these before any legend positioning calculations are performed.
> AG-7195 - Fix legend auto-padding retained whilst changing legend position.

- charts-packages/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-packages/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-packages/ag-charts-community/src/chart/series/polar/polarSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
https://ag-grid.atlassian.net/browse/AG-7201
Moves `PieSeries` labels into their own layer so that they can always appear above series highlights.
> AG-7201 - Fix PieSeries label rendering zindex.

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/axis/numberAxis.ts
PR for https://ag-grid.atlassian.net/browse/AG-7202.
Fixes ticks being set to `NaN` values when the domain is undefined.
> AG-7202 - Fix secondary axis ticks when series are toggled via legend

- grid-packages/ag-grid-docs/documentation/doc-pages/column-headers/examples/header-tooltip/main.ts
This is obviously super minor but I thought I'd fix it.
> Small typo fix for header tooltip example

- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/histogramChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/chartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/gridChartComp.ts
- enterprise-modules/charts/src/charts/chartComp/services/chartTranslationService.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/localisation/examples/localisation/locale.en.js
* Add ability to update histogram "Frequency" label in localisation file
* Fix bug where xKey was used instead of "Frequency" label in histogram
Before - using `xKey` in series
https://ag-grid.com/javascript-data-grid/integrated-charts-customisation/#example-histogram-chart-overrides
After - with label `Frequency` in series
https://ag-grid.com/javascript-data-grid/integrated-charts-customisation/#example-histogram-chart-overrides
With localisation
https://ag-grid.com/javascript-data-grid/localisation/
> AG-7110 Add localised "Frequency" as default histogram series label

- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- charts-packages/ag-charts-community/src/chart/series/polar/pieSeries.ts
- community-modules/core/src/ts/interfaces/iAgChartOptions.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-pie-series/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-5988
Improvements for Pie/Doughnut Chart segment label formatter:
- Allow access to associated data record through `datum` property.
- Access to config properties `labelKey`, `labelName`, `labelValue`, `angleKey`, `angleName`, `angleValue`, `radiusKey`, `radiusName`, `radiusValue`.
- `value` property becomes deprecated.
> AG-5988 - More parameters for pie label formatter

- community-modules/core/src/ts/gridApi.ts
- community-modules/core/src/ts/interfaces/IChartService.ts
- community-modules/core/src/ts/main.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/chartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/gridChartComp.ts
- enterprise-modules/charts/src/charts/chartService.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/api.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/grid-api.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-api-downloading-image/examples/downloading-chart-image/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-api-downloading-image/examples/downloading-chart-image/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-api-downloading-image/index.md
Added docs to https://ag-grid.com/react-data-grid/integrated-charts-api-downloading-image/
> AG-4460 - Add downloadChart to gridApi to allow custom size chart

- charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- enterprise-modules/charts/src/charts/chartComp/menu/format/series/seriesPanel.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-histogram-series/index.md
PR for https://ag-grid.atlassian.net/browse/AG-7234. 
If both `binCount` and `bins` specified in the histogram series options, `binCount` will now take precedence. Integrated charts now reads from `bin` and writes to `binCount` to get an accurate count for the formatting panel.
> Ag 7234/histogram series

- community-modules/styles/src/internal/base/parts/_common-structural.scss
https://localhost:8000/javascript-data-grid/column-groups/ with `enableRtl: true`
Contracted
Expanded (was not previously flipped)
> AG-7277 - Flip expanded icon when RTL is enabled

- charts-packages/ag-charts-community/src/canvas/hdpiCanvas.ts
- charts-packages/ag-charts-community/src/canvas/hdpiOffscreenCanvas.ts
- charts-packages/ag-charts-community/src/chart/agChartV2.ts
- charts-packages/ag-charts-community/src/chart/cartesianChart.ts
- charts-packages/ag-charts-community/src/chart/chart.ts
- charts-packages/ag-charts-community/src/chart/hierarchyChart.ts
- charts-packages/ag-charts-community/src/chart/polarChart.ts
- charts-packages/ag-charts-community/src/scene/scene.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/chartProxy.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
PR for https://ag-grid.atlassian.net/browse/AG-6879
Allow downloading chart as image in a specified size without flashing/ re-rendering of the visible chart
> Ag 6879/export chart as image

- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- community-modules/core/src/ts/interfaces/iAgChartOptions.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
The description for the formatter property was missing.
Before:
After:
> AG-5220 Fix for Treemap formatter docs

- charts-packages/ag-charts-community/src/scene/bbox.ts
- charts-packages/ag-charts-community/src/scene/group.ts
https://ag-grid.atlassian.net/browse/AG-7300
Fixes some edge cases where Chart layout changes don't trigger  rerender of the main series area.
> AG-7300 - Fix Chart  layer bbox changes not triggering rerender.

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/axis/numberAxis.ts
- charts-packages/ag-charts-community/src/chart/axis/timeAxis.ts
- charts-packages/ag-charts-community/src/chart/crossline/crossLine.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/util/validation.test.ts
- charts-packages/ag-charts-community/src/util/validation.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-7298?focusedCommentId=44546
Adds:
- Cross-field validations (specifically for `min`/`max` validations).
- Unit-tests for the `validation.ts` module.
Side-note: I'm not 100% happy with the pattern we landed on for `OPTIONAL` (it's not very composition friendly), but let's circle back on this distinctly as the scope of this PR is already much larger than I'd like :-/
> AG-7298 - Add validation tests and cross field validations

- community-modules/angular-legacy/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- community-modules/core/src/styles/structural/_common-structural.scss
- community-modules/core/src/ts/entities/gridOptions.ts
- community-modules/core/src/ts/gridOptionsWrapper.ts
- community-modules/core/src/ts/interfaces/IChartService.ts
- community-modules/core/src/ts/interfaces/iChartOptions.ts
- community-modules/core/src/ts/main.ts
- community-modules/core/src/ts/propertyKeys.ts
- community-modules/styles/src/internal/base/parts/_common-structural.scss
- enterprise-modules/charts/src/charts/chartComp/gridChartComp.ts
- enterprise-modules/charts/src/charts/chartComp/menu/chartMenu.ts
- enterprise-modules/charts/src/charts/chartComp/menu/settings/chartSettingsPanel.ts
- enterprise-modules/charts/src/charts/chartComp/menu/settings/miniChartsContainer.ts
- grid-packages/ag-grid-angular-legacy/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/grid-options.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-options/properties.json
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-chart-groups/data.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-chart-groups/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-chart-groups/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-panels/data.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-panels/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-panels/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/index.md
- grid-packages/ag-grid-enterprise/src/main.ts
* Allow customizing the list of available chart groups in the Chart Tool Panel settings panel
* Allow customizing chart tool panels
* Separate chart toolbar and chart tool panels logic
* Override `getChartToolbarItems()` panels (use `chartToolPanels.settingsPanel.panels` instead)
* Move `ChartToolPanelName` type to `iChartOptions`
* Add `ChartToolPanelMenuOptions` type to be more specific than `ChartMenuOptions`
* Allow default tool panel to be set and open
* If there is no default panel set, then the first panel is used
* Don't animate when first shown
* Added docs to `/javascript-data-grid/integrated-charts-toolbar/#chart-tool-panel-customisation` 
```
const gridOptions: GridOptions = {
// ...
chartToolPanels: {
settingsPanel: {        
chartGroups: {
pieGroup: [
'pie',
'doughnut'
], …
```
> AG-5026 - Allow customizing chart tool panels

- charts-packages/ag-charts-community/src/chart/series/polar/pieSeries.ts
The circle was still visible when all data was hidden through legend.
> RTI-1072 Hide Doughnut inner circle when no data

- charts-packages/ag-charts-community/src/chart/series/polar/pieSeries.ts
When the chart's radius appears to be less than the `innerRadiusOffset`, the doughnut inner circle should be hidden.
In future we should warn when outer radius is smaller than inner radius or less than 0.
> RTI-1074 Hide doughnut inner circle when radius <0

- enterprise-modules/charts/src/charts/chartComp/chartProxies/polar/pieChartProxy.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-api-cross-filter-chart/examples/sales-dashboard/main.ts
- Fixed assigning wrong properties to calloutLine.
- Renamed deprecated property in example.
> AG-7290 Fixed warnings in Integrated docs

- charts-packages/ag-charts-community/src/util/color.test.ts
- charts-packages/ag-charts-community/src/util/color.ts
https://ag-grid.atlassian.net/browse/AG-7356
Makes web-colour validation and use case-insensitive.
> AG-7356 - Make Chart colour validations case-insensitive.

- community-modules/core/src/ts/columns/columnApi.ts
- community-modules/core/src/ts/columns/columnModel.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/column-api/column-api.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/excel-export-extra-content/examples/excel-export-customisation/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/excel-export-extra-content/examples/excel-export-customisation/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/excel-export-extra-content/examples/excel-export-customisation/styles.css
- grid-packages/ag-grid-docs/documentation/doc-pages/excel-export-extra-content/index.md
* Allow `getDisplayNameForColumnGroup` location to be null. Just like `getDisplayNameForColumn`
* Add excel export customisation docs at `/javascript-data-grid/excel-export-extra-content/#export-customisation`
> AG-5296 Excel export customisation docs

- community-modules/core/src/ts/widgets/popupService.ts
* Use resize observer to update popup position when first open. Fix bug where popup would show underneath the grid because the calculation happens before the popup contents have rendered.
Before
After
> AG-7214 - Use resize observer to update popup position when first open

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/cartesianChart.ts
- Start the primary axis grid lines at the same place as the secondary.
- Use the proper ticks count for primary/secondary axes.
- Merge the primary/secondary ticks together if nice=true.
- Properly use axes min/max when nice=false, don't try to align the primary/secondary ticks.
> AG-7398 + AG-7399 Fix primary/secondary axis ticks

- community-modules/core/src/ts/filter/floating/provided/simpleFloatingFilter.ts
* Localise blank and not blank in filter text box
Docs: https://ag-grid.com/javascript-data-grid/localisation/#example-localisation
Before (not localised)
After (localised)
> AG-7185 - Localise blank and not blank in filter text box

- grid-packages/ag-grid-docs/documentation/doc-pages/charts-area-series/examples/missing-data-area/data.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-area-series/examples/missing-data-area/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-area-series/examples/missing-data-area/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-area-series/examples/missing-data-area/styles.css
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-area-series/index.md
Pr for https://ag-grid.atlassian.net/browse/AG-7336
Added docs example in Area docs page to show handling of missing data.
Example has buttons to switch between missing X and missing Y values, as well as from grouped to stacked area series.
> AG-7336 - Area series missing data docs example

- community-modules/core/src/ts/filter/provided/simpleFilter.ts
- community-modules/core/src/ts/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/filter-provided-simple/examples/filter-placeholder-text/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/filter-provided-simple/examples/filter-placeholder-text/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/filter-provided-simple/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
- grid-packages/ag-grid-enterprise/src/main.ts
* Add simple filter placeholder text colDef option
* Add docs to `/javascript-data-grid/filter-provided-simple/#customising-filter-placeholder-text`
Adding `columnDefs` > `filterParams.filterPlaceholder`
```
const gridOptions = {
columnDefs: [
{
field: 'age',
filter: 'agNumberColumnFilter',
filterParams: {
filterPlaceholder: 'Age...'
}
},
{
field: 'total',
filter: 'agNumberColumnFilter',
filterParams: {
filterPlaceholder: (params) => {
const { filterOption, placeholder } = params;
return `${filterOption} ${placeholder}`;
}
}
}
]
}
```
> AG-7412 - Add simple filter placeholder text colDef option

- enterprise-modules/charts/src/charts/chartComp/menu/format/axis/axisPanel.ts
X Type option in the Format panel for integrated charts is non-functional. Remove the option for now, to be re-implemented later.
> AG-7419 - Remove non-functional integrated chart x axis type option

- charts-packages/ag-charts-community/src/chart/chart.ts
- charts-packages/ag-charts-community/src/util/observable.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/scatterChartProxy.ts
- The use of event.series is deprecated.
- Make the keys (except deprecated) enumerable in the fired event.
> RTI-1094 Fixed CrossFilter click error

- enterprise-modules/charts/src/charts/chartComp/chartProxies/chartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/polar/pieChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/menu/format/series/fontPanelParams.ts
- enterprise-modules/charts/src/charts/chartComp/menu/format/series/seriesPanel.ts
- enterprise-modules/charts/src/charts/chartComp/services/chartTranslationService.ts
* Extend pie chart series labels to have sector labels 
* Show sector labels on pie charts from grid values
* Separate out callout labels and sector labels
* Add font panel for sector labels
* Disable sector label by default in integrated charts
UI for the `sectorLabel` grid options:
```
const gridOptions: GridOptions = {
chartThemeOverrides: {
pie: {
series: {
// Can update sector label here too
sectorLabel: {
enabled: true,
fontSize: 20
},
},
},
},
}
```
> AG-5117 - Add pie sector label UI to integrated charts

- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-time-series/examples/time-axis-config/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-time-series/examples/time-combination-chart/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-time-series/examples/time-vs-category/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-time-series/index.md
https://ag-grid.atlassian.net/browse/AG-7477
Attempts to improve Integrated Charts Time Axis example date formatting (primarily tooltip rendering) to guide users on the supported approach to formatting date/times in Integrated Charts.
The motivation for this is an incoming support request asking how to do this and referencing our time-axis examples as source of truth on how to manage time formatting.
**Time vs Category Axis Example**
Before:
After:
**Time Axis Configuration Example**
Before:
After:
**Time Axis Combination Chart**
Before:
After:
> AG-7477 - Improve date formatting in Integrated time-axis examples.

- enterprise-modules/set-filter/src/setFilter/setValueModel.ts
Change all/none visible selection checks to short-circuit.
Use native Set constructor instead of convertToSet (already used in core, so no compatibility issues).
> AG-6958 - Improve set filter selection performance

- charts-packages/ag-charts-community/src/chart/mapping/themes.ts
- charts-packages/ag-charts-community/src/integrated-charts-theme.ts
- community-modules/core/src/ts/utils/object.test.ts
- community-modules/core/src/ts/utils/object.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/areaChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/barChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/cartesianChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/histogramChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/lineChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/scatterChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/chartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/combo/comboChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/polar/pieChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/services/chartOptionsService.ts
- enterprise-modules/charts/src/charts/chartComp/utils/object.ts
* Replace ChartTheme instance with AgChartTheme config in Integrated Charts
Don’t need `ChartTheme` inside Grid, since we can just use `AgChartTheme` (just a plain object). Previously, Grid was getting the `ChartTheme` from Charts, merging `AgChartTheme` overrides and then passing it back to Charts. Now, we just pass in the necessary `AgChartTheme` config directly into Charts, without merging with `ChartTheme` from Charts. Charts will be in charge of managing and merging the theme with the overrides.
* Allow chart options to be empty in all the chart proxies
* Create `agChartTheme` field to store Grid theme overrides, to pass into chart creation
* Use Chart `getChartTheme` to get palette
* Use `_.set` in `chartOptionsService` for all chart option updates, so it creates objects if they are …
> AG-7502 - Simplify how integrated charts passes chart options and theme to standalone charts

- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/scene/shape/path.ts
- charts-packages/ag-charts-community/src/scene/shape/rect.ts
PR for https://ag-grid.atlassian.net/browse/AG-7530.
In the case of a custom marker shape, the shape path commands could be dependent on the node data and we may need to invoke updatePath() to update the path when the selections are updated (data for the marker node has changed).
> AG-7469 - Fix custom marker shape path not updating

- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
- Use sectors stroke colors for callout line if unset.
- Remove unused Series.setColors method.
> AG-7457 Fix callout line color mismatch

- enterprise-modules/charts/src/charts/chartComp/chartProxies/polar/pieChartProxy.ts
Note: chart tooltip options are different from series tooltip options.
> AG-7550 Fix CrossFilter Pie tooltip override

- enterprise-modules/charts/src/charts/chartComp/chartController.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/areaChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/barChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/cartesianChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/histogramChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/lineChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/cartesian/scatterChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/chartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/combo/comboChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/chartProxies/polar/pieChartProxy.ts
- enterprise-modules/charts/src/charts/chartComp/services/chartOptionsService.ts
Follow up to https://github.com/ag-grid/ag-grid/pull/5765
* Get chart options from Chart `getOptions()` and delete `chartOptions` and `chartPalette` in `chartProxy`.  `chartProxy.agChartTheme` stores theme on creation, but during updates, changes are made directly to the chart using `AgChart.updateDelta`. Hence the Chart stores the state of the options and to retrieve it `getOptions()` can be used.
* Special handling for `scatter.paired` to be persisted in `chartProxy` to make it explicit that it's only for Integrated Charts
* Remove chart options merges within child chart proxies since these were for styles, and this is now managed by the Chart
> AG-7502 - Get chart options from Chart instead of storing in `chartProxy.chartOptions`

- community-modules/client-side-row-model/src/clientSideRowModel/clientSideRowModel.ts
- community-modules/core/src/ts/columns/columnModel.ts
- community-modules/core/src/ts/components/componentUtil.ts
- community-modules/core/src/ts/context/beanStub.ts
- community-modules/core/src/ts/gridApi.ts
- community-modules/core/src/ts/gridBodyComp/centerWidthFeature.ts
- community-modules/core/src/ts/gridBodyComp/fakeHScrollCtrl.ts
- community-modules/core/src/ts/gridBodyComp/pinnedWidthService.ts
- community-modules/core/src/ts/gridBodyComp/rowContainer/rowContainerCtrl.ts
- community-modules/core/src/ts/gridOptionsService.ts
- community-modules/core/src/ts/gridOptionsWrapper.ts
- community-modules/core/src/ts/headerRendering/gridHeaderCtrl.ts
- community-modules/core/src/ts/headerRendering/row/headerRowCtrl.ts
- community-modules/core/src/ts/pagination/paginationProxy.ts
- community-modules/core/src/ts/rendering/features/setLeftFeature.ts
- community-modules/core/src/ts/rendering/row/rowDragComp.ts
- community-modules/core/src/ts/rendering/rowRenderer.ts
- community-modules/core/src/ts/styling/layoutFeature.ts
- enterprise-modules/column-tool-panel/src/columnToolPanel/toolPanelColumnComp.ts
- enterprise-modules/row-grouping/src/rowGrouping/columnDropZones/baseDropZonePanel.ts
- enterprise-modules/row-grouping/src/rowGrouping/columnDropZones/gridHeaderDropZones.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/grid-api.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
With the new GridOptionsService we have an opportunity to update how ComponentUtils works to lay a solid foundation for making as many of the Grid properties reactive as we can. As such our aims include:
1. Ensure that a `PropertyChangedEvent` is fired for every changed grid option
2. Avoid bugs due to events not firing due to updated order breaking change detection
3. Remove as much custom handling from ComponentUtils as possible
I believe the following changes meet these requirements. There could be some followup items such as:
- removing GridApi set methods that are solely for component utils to be able to update grid options. If they are not triggering reactive behaviour then maybe JS users can just update their GridOptions config option and have the grid use the new values. 
- Make …
> Ag 7579 change detection via grid options service

- community-modules/core/src/ts/interfaces/iChartOptions.ts
- enterprise-modules/charts/src/charts/chartComp/menu/data/chartDataPanel.ts
- enterprise-modules/charts/src/charts/chartComp/menu/format/formatPanel.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/grid-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-data-groups/data.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-data-groups/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/examples/customise-data-groups/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-toolbar/index.md
* Add chart data panel customisation using `chartToolPanelsDef.dataPanel.groups` grid options
* Add docs
```
const gridOptions = {
chartToolPanelsDef: {
dataPanel: {
groups: [
{ type: 'categories', isOpen: true },
{ type: 'series', isOpen: true },
{ type: 'seriesChartType', isOpen: true }
]
}
}
}
```
> AG-7578 - Add chart data panel customisation

- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- charts-packages/ag-charts-community/src/chart/mapping/__snapshots__/prepare.test.ts.snap
- charts-packages/ag-charts-community/src/chart/series/hierarchy/treemapSeries.ts
- charts-packages/ag-charts-community/src/chart/series/series.ts
- charts-packages/ag-charts-community/src/chart/themes/chartTheme.ts
- charts-packages/ag-charts-community/tools/dev-server/tsconfig.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-overview/examples/market-index-treemap/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-treemap-series/examples/custom-colors/data.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-treemap-series/examples/custom-colors/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-treemap-series/examples/custom-colors/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-treemap-series/index.md
- Untie tile and tooltip label text from colorKey.
- Ability to get depth and parent in formatter and tooltip renderer.
- Separate tile and text shadows.
- Highlight text colour (can be used in all types).
- Ability to prevent groups highlighting.
- Fixed not displaying formatted fill in the tooltip.
- API docs update and complex colouring example.
> AG-7585 Treemap API improvements & docs

- community-modules/styles/src/internal/base/parts/_charts.scss
- community-modules/styles/src/internal/themes/alpine/_index.scss
- community-modules/styles/src/internal/themes/balham/_index.scss
- community-modules/styles/src/internal/themes/material/_index.scss
- enterprise-modules/charts/src/charts/chartComp/chartProxies/chartTheme.ts
- enterprise-modules/charts/src/charts/chartComp/menu/chartMenu.ts
- grid-packages/ag-grid-docs/documentation/customise.js
- scripts/release/createAndDeployDocsToS3.sh
* Fix bug with integrated charts padding being overwritten
* Add integrated chart padding based on RTL
* Style chart tool panel button to make click target larger and more obvious
* For `alpine`, `alpine-dark`, `balham`, `balham-dark` and `material` grid themes
Closed
| Before | After |
| - | - |
| ![Screenshot 2022-12-07 at 3 29 32 pm](https://user-images.githubusercontent.com/79451/206221094-2b269f16-0119-40ca-a4f4-ea549d995516.png) | ![Screenshot 2022-12-07 at 3 22 19 pm](https://user-images.githubusercontent.com/79451/206220368-17c97e0c-0aaa-42f1-9fc9-c1d6202f674c.png) |
Open
| Before | After |
| - | - |
| ![Screenshot 2022-12-07 at 3 29 38 pm](https://user-images.githubusercontent.com/79451/206221342-a06d4d86-1923-405c-ac8f-9f74a6bec4fe.png) | ![Screenshot 2022-12-07 at 3 22 26 …
> AG-7596 - Increase Chart Tool Panels click area and increase chart padding

- charts-packages/ag-charts-community/src/chart/cartesianChart.ts
- charts-packages/ag-charts-community/src/chart/chart.ts
- charts-packages/ag-charts-community/src/chart/interaction/cursorManager.ts
- charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
- charts-packages/ag-charts-community/src/chart/legend.ts
- charts-packages/ag-charts-community/src/chart/navigator/navigator.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-7656
Attempts to consolidate `element.style.cursor` handling to better separate cursor styling logic, state and conflict resolution from various parts of the code base into `CursorManager`.
Bonus:
- Moves all legend-related `InteractionEvent` handling to `legend.ts`.
- Adds `InteractionEvent.consume()` to allow mutually-exclusive event processing without tight coupling between handlers.
- Removes some redundant code from `Chart`.
> AG-7656 - Refactor cursor style handling

- charts-packages/ag-charts-community/src/chart/agChartOptions.ts
- charts-packages/ag-charts-community/src/chart/legend.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
PR for https://ag-grid.atlassian.net/browse/AG-7583 & https://ag-grid.atlassian.net/browse/AG-6424.
Added `legend.seriesToggleEnabled` property to disable toggling the visibility of the series when the legend items are clicked.
`legend.listeners.legendItemClick` callback function will still invoked. 
If there is no `legend.listeners.legendItemClick`, and `legend.seriesToggleEnabled` is set to false, the cursor will not be changed to a pointer. Even if there is series highlighting on legend item hover.
> AG-7583- Allow disabling series toggling when legend item is clicked

- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Options.tsx
- grid-packages/ag-grid-docs/documentation/src/components/example-runner/CodeViewer.jsx
1. Fix setting component state after unmounting.
`Can't perform a React state update on an unmounted component`
2. Fix warning when switching chart type.
`React has detected a change in the order of Hooks called by Options`
This is due Gatsby using `useContext` inside `useStaticQuery`. React doesn't recommend having hooks inside conditions.
> AG-6986 Fix API explorer warnings

- charts-packages/ag-charts-community/src/chart/legend.ts
- charts-packages/ag-charts-community/src/chart/pagination/pagination.ts
https://ag-grid.atlassian.net/browse/AG-7751
Attempts to maintain state of the current legend page in resize scenarios (most commonly, in Integrated Charts when opening and closing the side-panel)
> AG-7751 - Track current legend page on chart resize.

- charts-packages/ag-charts-community/src/chart/legend.ts
PR for https://ag-grid.atlassian.net/browse/AG-7772
For now adding a tooltip for truncated legend items using the chart element title property to fix regression
> Ag 7772/truncated legend item tooltip

- charts-packages/ag-charts-community/src/chart/axis/groupedCategoryAxis.ts
- charts-packages/ag-charts-community/src/chart/axis/numberAxis.ts
- charts-packages/ag-charts-community/src/chart/axis/timeAxis.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-packages/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-packages/ag-charts-community/src/layout/tree.ts
- charts-packages/ag-charts-community/src/util/array.test.ts
- charts-packages/ag-charts-community/src/util/array.ts
- enterprise-modules/sparklines/src/sparkline/area/areaSparkline.ts
- enterprise-modules/sparklines/src/sparkline/bar-column/barColumnSparkline.ts
- enterprise-modules/sparklines/src/sparkline/line/lineSparkline.ts
- enterprise-modules/sparklines/src/sparkline/sparkline.ts
- Remove unnecessary Array utilities.
- Accept numbers and dates for `extent` utility.
- Make `extent` always return numbers.
> AG-7775 Simplify Array utilities

- charts-packages/ag-charts-community/src/chart/crossline/crossLine.ts
https://ag-grid.atlassian.net/browse/AG-7812
Significantly improves chart stability when crossline labels are being laid-out on a small chart.
https://user-images.githubusercontent.com/17544187/212365988-767be58a-ebe6-40e4-a19d-0673e1575b0f.mov
> AG-7812 - Remove Chart auto crossLine label padding when chart is small.

- charts-packages/ag-charts-community/src/chart/chart.ts
- charts-packages/ag-charts-community/src/chart/interaction/tooltipManager.ts
- charts-packages/ag-charts-community/src/chart/legend.ts
- charts-packages/ag-charts-community/src/chart/tooltip/tooltip.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-7783
https://ag-grid.atlassian.net/browse/AG-7790
Switches `Legend` to use the HTML-based `Tooltip` class, removing the (ab)use of `Canvas.title` to manage legend tooltips.
Additionally introduces `TooltipManager` to handle conflicts from multiple tooltip sources correctly.
> AG-7783 - Switch Legend to use HTML tooltips

- charts-packages/ag-charts-community/src/scene/group.ts
- charts-packages/ag-charts-community/src/scene/node.ts
- charts-packages/ag-charts-community/src/scene/scene.ts
- charts-packages/ag-charts-community/src/scene/shape/range.test.ts
- charts-packages/ag-charts-community/src/scene/shape/rect.test.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
Adds `window.agChartsSceneDebug` to render bounding boxes of scene nodes for debugging.
Supports specification of scene graph ids, group names or aliases:
- `layout` - alias for all layout-related groups.
> Add Charts agChartsSceneDebug option.

- charts-packages/ag-charts-community/src/chart/legend.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-constraints/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-constraints/main.ts
PR for https://ag-grid.atlassian.net/browse/AG-7761
- Modified legend constraints docs example so it doesn't jump when the user interacts with the `item.maxWidth` slider
- Split legend item text label truncation into its own function
> Ag 7761/legend item truncation

- community-modules/core/src/ts/dragAndDrop/dragAndDropService.ts
- community-modules/core/src/ts/filter/provided/number/numberFilter.ts
- community-modules/core/src/ts/rendering/cell/cellMouseListenerFeature.ts
- community-modules/core/src/ts/utils/browser.ts
- community-modules/core/src/ts/utils/keyboard.ts
The browser utils need to be updated to match the current state of our supported browsers. There is some dead code relating to older versions of Edge and IE that can be removed.
Also the Firefox detection is soon to fail as the property used has been deprecated. 
I have also reduced the code require to get the browser version to just what is currently require, i.e the Safari version
> AG-7848 Update browser utils

- grid-packages/ag-grid-docs/dev-server.js
- grid-packages/ag-grid-docs/gulpfile.js
- grid-packages/ag-grid-docs/package.json
- package.json
* Add a `npm run docs-serve-website-only` command to skip example generation, and only serve the gatsby server. For website development
> AG-3390 - Add website only docs runner

- charts-packages/ag-charts-community/src/chart/axis/logAxis.ts
- charts-packages/ag-charts-community/src/chart/axis/numberAxis.ts
- charts-packages/ag-charts-community/src/util/validation.ts
PR for https://ag-grid.atlassian.net/browse/AG-7746
Validation for log axis min and max values, both cannot be less than 1
> AG-7746 - Fix log axis scale min value

- charts-packages/ag-charts-angular-legacy/projects/ag-charts-angular/src/lib/ag-charts-angular.component.ts
- charts-packages/ag-charts-angular/projects/ag-charts-angular/src/lib/ag-charts-angular.component.ts
- charts-packages/ag-charts-react/src/agChartsReact.ts
- charts-packages/ag-charts-vue/src/AgChartsVue.ts
- charts-packages/ag-charts-vue3/src/AgChartsVue.ts
https://ag-grid.atlassian.net/browse/AG-7293
Adds support for exposing the Chart instance managed by FW wrapper tags, to allow use of `AgChart.download()` and other API features.
- Angular ([example](https://plnkr.co/edit/p58uM0Z9NtjceJ1Y?open=app%2Fapp.component.ts)):
- Exposes `AgChartsAgnular.chart` for parent elements to be able to access via a `@ViewChild()` decorated property.
- Adds a `onChartReady` event which is triggered after the initial rendering of the chart completes.
- React ([example](https://plnkr.co/edit/HXnjbkzjXtKXtcMR?open=index.jsx&preview)):
- Exposes `AgChartsReact.chart` for parent elements to be able to access via a `ref`.
- Adds a `onChartReady` event which is triggered after the initial rendering of the chart completes.
- Vue …
> AG-7293 - Add basic Charts FW wrapper export of chart reference.

- charts-packages/ag-charts-community/src/scale/logScale.ts
PR for https://ag-grid.atlassian.net/browse/AG-7763
`logScale` uses `ticks` to determine tick format but did not have the updated `ticks`
> AG-7763 - Fix log axis gridLines/ticks displaying without labels

- grid-packages/ag-grid-docs/documentation/src/components/site-header/SiteHeader.jsx
- Removed 'Documentation' as the default current page for main nav selected item. 
- Stoped using `useState`/`setActive(link.name)` so the nav changes selected item when the user clicks non-nav links. E.g. links in the footer.
> AG-7871 - Fix main navigation current page bug

- charts-packages/ag-charts-community/src/chart/agChartV2.ts
- charts-packages/ag-charts-community/src/chart/legend.ts
- charts-packages/ag-charts-community/src/chart/themes/chartTheme.ts
- charts-packages/ag-charts-community/src/util/json.test.ts
- charts-packages/ag-charts-community/src/util/observable.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-events/examples/standalone-events/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-events/examples/standalone-events/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/integrated-charts-events/index.md
https://ag-grid.atlassian.net/browse/AG-7905
Fixes setting of `listeners` and `legend.listeners` using `AgChart.updateDelta()` for Integrated Charts use-cases.
Additionally adds a new example to demonstrate this.
> AG-7905 - Fix listener handling on chart type changes

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/scale/continuousScale.ts
- charts-packages/ag-charts-community/src/scale/linearScale.ts
- charts-packages/ag-charts-community/src/scale/logScale.ts
- charts-packages/ag-charts-community/src/scale/timeScale.ts
- charts-packages/ag-charts-community/src/util/ticks.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-axes/index.md
PR for https://ag-grid.atlassian.net/browse/AG-7908
Addresses Davids comments:
https://ag-grid.atlassian.net/browse/AG-7908?focusedCommentId=47309
1/
Requesting too many ticks via a small interval, warns the user as expected. 
However, no ticks at all are rendered. If we are ignoring the provided interval, we should display the default ‘nice’ tick number.
2/
Invalid options of providing a string is handled correctly. 
When provided with a negative interval, it is ignored but the message does not mention why.
Property [interval] cannot be set to [-1]; expecting an optional tick count Number value or, for a time axis, a Time Interval such as 'agCharts.time.month', ignoring.
3/
When providing an interval of 0, it is ignored (I think), and no warning message is displayed.
4/
Axis intervals …
> Ag 7908/axis tick interval

- charts-packages/ag-charts-community/src/axis.ts
- charts-packages/ag-charts-community/src/chart/axis/timeAxis.ts
- charts-packages/ag-charts-community/src/chart/chartAxis.ts
- charts-packages/ag-charts-community/src/scale/bandScale.ts
- charts-packages/ag-charts-community/src/scale/colorScale.ts
- charts-packages/ag-charts-community/src/scale/continuousScale.ts
- charts-packages/ag-charts-community/src/scale/linearScale.ts
- charts-packages/ag-charts-community/src/scale/logScale.ts
- charts-packages/ag-charts-community/src/scale/scale.ts
- charts-packages/ag-charts-community/src/scale/timeScale.ts
- enterprise-modules/sparklines/src/sparkline/area/areaSparkline.ts
- enterprise-modules/sparklines/src/sparkline/bar-column/barSparkline.ts
- enterprise-modules/sparklines/src/sparkline/bar-column/columnSparkline.ts
- enterprise-modules/sparklines/src/sparkline/line/lineSparkline.ts
- enterprise-modules/sparklines/src/sparkline/sparkline.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
PR for https://ag-grid.atlassian.net/browse/AG-7909
Extends scale domain so that all provided tick values are displayed
Removes default formatting so exact tick values are displayed
Some tightening of the types for scales
> Ag 7909/axes tick values

- charts-packages/ag-charts-community/src/chart/chart.ts
PR for https://ag-grid.atlassian.net/browse/AG-7461
This takes the simplistic approach of checking the pick distance is zero, and doesn't address separating highlighting and clicking behaviour / configuration.
> AG-7461 Fix series node click to check distance is zero

- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/examples/interaction-ranges/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/examples/interaction-ranges/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/examples/interaction-ranges/styles.css
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/examples/series-node-click-event/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/interaction-range/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/interaction-range/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/examples/interaction-range/style.css
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-tooltips/index.md
PR for https://ag-grid.atlassian.net/browse/AG-8058
Adds docs for `tooltip.range` and `series[].nodeClickRange` with switchable examples.
> AG 8058 Interaction range docs for tooltips and node clicks

- grid-packages/ag-grid-docs/documentation/doc-pages/getting-started/_angular.md
- grid-packages/ag-grid-docs/documentation/doc-pages/getting-started/_react.md
- grid-packages/ag-grid-docs/documentation/doc-pages/getting-started/_vue.md
I noticed some typos in comments of sample codes at "getting started" section. Decided to fix them.
> Fix typos in getting started sample code comments

- grid-packages/ag-grid-docs/documentation/src/components/charts-api-explorer/Editors.tsx
PR for https://ag-grid.atlassian.net/browse/AG-8058
This adds a simple string editor that coerces the type so the API editor can handle mixed union types like `type Foo = number | 'bar' | 'baz'`.
> AG-8058 Add coerced editor to api explorer for mixed union types

- charts-community-modules/ag-charts-community/src/chart/legend.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-click-series-toggle/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/index.md
PR for https://ag-grid.atlassian.net/browse/AG-7121
Fixes toggling legend items when you double click on a legend item that was disabled, while one or more other items were enabled. It will now disable all others and enable only the item clicked.
Also some minor docs improvements.
> AG-7121 double click fixes

- charts-community-modules/ag-charts-community/src/axis.ts
- charts-community-modules/ag-charts-community/src/chart/agChartV2.ts
- charts-community-modules/ag-charts-community/src/chart/axis/categoryAxis.ts
- charts-community-modules/ag-charts-community/src/chart/axis/groupedCategoryAxis.ts
- charts-community-modules/ag-charts-community/src/chart/axis/logAxis.ts
- charts-community-modules/ag-charts-community/src/chart/axis/numberAxis.ts
- charts-community-modules/ag-charts-community/src/chart/axis/timeAxis.ts
- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/chartAxis.ts
https://ag-grid.atlassian.net/browse/AG-8047
Implements support for `axis` module types:
- Lifecycle management, directed from `AgChartV2`.
- Pseudo-DI via `ModuleContext` being made available to `ChartAxis` for injecting into module instances.
> AG-8047 - Add axis module lifecycle handling and DI.

- charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
- charts-community-modules/ag-charts-community/src/chart/agChartV2.ts
- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/themes/chartTheme.ts
- charts-community-modules/ag-charts-community/src/scene/node.ts
- charts-community-modules/ag-charts-community/src/scene/path2D.ts
- charts-community-modules/ag-charts-community/src/util/observable.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
PR for https://ag-grid.atlassian.net/browse/AG-7461
Checkout this branch and see this plunker for a demo - https://plnkr.co/edit/JSpdRMVodhtiEX6N?open=main.ts&preview
New behaviour is:
- If the cursor is within `tooltip.range` and the `cursor` option is defined, display that cursor
- If the cursor is within `series[].nodeClickRange` and a listener is attached to one of: `seriesNodeClick`, `seriesNodeDoubleClick`, `series[].nodeClick` or `series[].nodeDoubleClick`, then display a `pointer` cursor
In the plunker above it will display the `wait` cursor when within tooltip range of the `foo` series, the `pointer` cursor when within node click range of the `foo` or `qux` series, and finally it will not change the cursor for the `bar` series as that one has no listeners. Note `qux` is a double …
> AG-7461 Add default cursor behaviour for nodes with click listeners 

- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/examples/legend-click-series-toggle/main.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-legend/index.md
PR for https://ag-grid.atlassian.net/browse/AG-7121
Moves legend event docs to the events page, and the series toggling to the legend page.
> AG-7121 Rationalise legend series toggling and events docs

- charts-community-modules/ag-charts-community/src/canvas/hdpiCanvas.ts
- charts-community-modules/ag-charts-community/src/canvas/hdpiOffscreenCanvas.ts
- charts-community-modules/ag-charts-community/src/chart/cartesianChart.ts
- charts-community-modules/ag-charts-community/src/scene/group.ts
- charts-community-modules/ag-charts-community/src/scene/scene.ts
https://ag-grid.atlassian.net/browse/AG-8142
`ctx.getTransform()` was returning the raw Canvas matrix, including DPR multipliers - when using this as the basis for converting `clipRect` coordinates back to the canvas coordinate space, we were then getting a result that was out by a factor of the DPR.
I've removed use of `ctx.getTransform()` in favour of using the inverse of the locally managed `this.matrix`, which doesn't have DPR multipliers applied.
Bonus:
- Adds a verification that `save()` and `restore()` calls are balanced (discussed offline with @manapeirov)
> AG-8142 - Fix clipRect high DPR cases

- charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
- charts-community-modules/ag-charts-community/src/chart/chart.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/examples/interaction-ranges/index.html
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-events/examples/interaction-ranges/main.ts
PR for https://ag-grid.atlassian.net/browse/AG-8058
Adds `chart.highlightRange` option to toggle highlighting triggering in line with the tooltip or the node clicking. The default is `'tooltip'` since it would be rare for the tooltip range to be smaller than the node click range.
This has all got bit complect with the pointer, highlighting, tooltip and clicking ranges and toggling. A subject for refactor once behaviour has settled.
> AG-8058 Interaction & highlight range

- grid-packages/ag-grid-docs/documentation/doc-pages/charts-zoom/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/licensing/menu.json
For https://ag-grid.atlassian.net/browse/AG-3479
Adds zoom docs with plunker links as placeholders before we can embed the usual example component.
> AG-3479 Add zoom docs with plunker examples

- grid-community-modules/core/src/ts/rendering/row/rowCtrl.ts
- grid-community-modules/core/src/ts/rendering/rowRenderer.ts
https://ag-grid.atlassian.net/browse/AG-8202
Currently when filtering in React 18 the rows flash when updating a filter via a component. (does not impact filtering via the api methods)
What is happening is that as part of `setupRemoveAnimation` the `ag-opacity-zero` is applied synchronously to the existing row components. This immediately hides the contents of the rows that are going to be removed. However, as the rows are not actually removed until after React has asynchronously updated the row controllers we see the grid in a state where some rows are hidden and others are visible. 
It happens very fast but slow enough to see a visible flash. This does not impact the api methods as they are already using an async update method for filters. 
The fix is to only apply the `ag-opacity-zero` …
> AG-8202 Avoid visible flash in React when filtering

- charts-community-modules/ag-charts-community/src/chart/themes/chartTheme.ts
The value assigned through the theme is treated as the "previous", when another one is assigned through options.
> RTI-1426 Fix removing default Tooltip class name

- charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
- charts-community-modules/ag-charts-community/src/chart/chartAxis.ts
- charts-community-modules/ag-charts-community/src/chart/factory/seriesTypes.ts
- charts-community-modules/ag-charts-community/src/chart/mapping/__snapshots__/prepare.test.ts.snap
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/test/examples.ts
- charts-community-modules/ag-charts-community/src/chart/themes/chartTheme.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-8482
Removes the pointless `flipXY` options from `BarSeries`, which was a proxy for `type` being set to `column` or `bar`.
Adds `ColumnSeries` which trivially overrides some methods to vary rendering behaviour.
> AG-8482 - Remove BarSeries.flipXY.

- charts-community-modules/ag-charts-community/src/chart/data/__snapshots__/dataModel.test.ts.snap
- charts-community-modules/ag-charts-community/src/chart/data/aggregateFunctions.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.test.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.ts
- charts-community-modules/ag-charts-community/src/chart/data/processors.ts
- charts-community-modules/ag-charts-community/src/chart/data/utilFunctions.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-8403
Pre-requisite changes to support the `PieSeries` use-case.
Adds support for:
- Accumulative values across groups (rows - bar+area series stack case) and properties (columns - pie case).
- Normalisation across groups (rows) and properties (columns).
- Rounding to 4 significant figures for aggregate values, to mitigate cumulative error issues.
Refactors:
- Normalisation support to be a set of group/property processors, rather than an explicit built-in behaviour.
- Moved a bunch of processors into `processors.ts` to reduce the scope of `dataModel.ts`.
> AG-8403 - Add DataModel support for accumulated groups + properties

- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-community-modules/ag-charts-community/src/motion/states.ts
- charts-enterprise-modules/ag-charts-enterprise/src/animation/animation.ts
- charts-enterprise-modules/ag-charts-enterprise/src/animation/animationModule.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-context-menu/examples/context-menu-actions/main.ts
PR for https://ag-grid.atlassian.net/browse/AG-8462
This is the first of the series initial load animations. I've added a basic state machine to handle transitioning between different animation states. Happy to hear thoughts on this approach.
The pie series state machine currently starts in the `empty` state, then on the `load` event transitions to `ready`. The transition event is where the animation occurs. Once in the `ready` state it can no longer transition anywhere (currently), so the animation can't happen again even if the `load` event is called.
_edit: changed to `update` instead of `load`_
In the future this will also have a `highlight`, `add`, `remove` and `update` events with related states.
I may also look at adding event blocking and queue so that if the user adds a node in …
> AG-8462 Pie initial load animation

- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/interactionManager.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
PR for https://ag-grid.atlassian.net/browse/AG-8460
This adds the `disableInteractions: true` option when animating, which disables/enables interactions while that animation is running. With the intent on queueing some types of interaction to be run when re-enabled in the future.
> AG-8460 Add disableInteractions option on animation manager

- charts-community-modules/ag-charts-community/src/chart/data/__snapshots__/dataModel.test.ts.snap
- charts-community-modules/ag-charts-community/src/chart/data/aggregateFunctions.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.test.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.ts
- charts-community-modules/ag-charts-community/src/chart/data/processors.ts
- charts-community-modules/ag-charts-community/src/chart/polarChart.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/polarSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/series.ts
- charts-community-modules/ag-charts-community/src/util/sector.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-8403
Integrated use of `DataModel` into `PieSeries`.
Required several `DataModel` improvements:
- Reworked normalisation support to allow for non-zero-based domains (min and max specified by users).
- Updated property references to use ids rather than property keys, allowing multiple uses of the same property key with different aggregation or normalisation functions.
- Debugging of `ProcessedData` via `window.agChartsDebug = 'data-model'`.
> AG-8403 - Integrated DataModel into  PieSeries

- grid-packages/ag-grid-docs/documentation/doc-pages/grid-interface/_index-react.md
I happened to notice what appears to be a copy/paste issue in the grid interface react docs, where the body of the function is referencing `e` (presumably copied from the example directly above it), but the provided arg is `params`:
`// access API from callback params object
sendToClipboard = params => {
e.api.sizeColumnsToFit();
e.columnApi.resetColumnState();
}`
This change switches the `e` to `params`.
> Fixed incorrect parameter callback documentation

- charts-community-modules/ag-charts-community/src/chart/axis/axisExamples.test.ts
- charts-community-modules/ag-charts-community/src/chart/chartAxis.ts
- charts-community-modules/ag-charts-community/src/chart/dataService.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/polarSeries.test.ts
- charts-community-modules/ag-charts-community/src/chart/series/series.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/doc-interfaces.AUTO.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/interfaces.AUTO.json
https://ag-grid.atlassian.net/browse/AG-8603
Fixes corruption of `Series.seriesItemsEnabled` on legend toggle, which leads to side-effects such as axis labels being displayed even when there are no bound-series displayed.
Bonus:
- I made `Series.toggleSeriesItem()` protected since it no longer need to be exposed to `Legend`, a couple of tests use it but I'd rather lock it down and workaround in those situations.
> AG-8603 - Fix legend toggle corrupting seriesItemEnabled tracking.

- charts-community-modules/ag-charts-community/src/chart/chart.ts
PR for https://ag-grid.atlassian.net/browse/AG-8543 and https://ag-grid.atlassian.net/browse/AG-8544
The issue was that when `updateDelta()` is called it runs the chart constructor again so the overlays manager loses track of the no data overlay element. This fixes that by finding it each time from the class as a child of the parent.
> AG-8543 AG-8544 Fix no data overlay to re-use existing component

- charts-community-modules/ag-charts-community/src/axis.ts
- charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
- charts-community-modules/ag-charts-community/src/chart/axis/groupedCategoryAxis.ts
- charts-community-modules/ag-charts-community/src/chart/chartAxis.ts
- charts-community-modules/ag-charts-community/src/chart/chartOptions.ts
- charts-community-modules/ag-charts-community/src/util/json.ts
https://ag-grid.atlassian.net/browse/AG-7112
Adds support for `axes[].title.formatter` callback function, allowing dynamic chart-axis title calculation. The primary use-case is Integrated Charts customisation.
> AG-7112 - Add axis title formatter.

- charts-community-modules/ag-charts-community/.docker/run.sh
- charts-community-modules/ag-charts-community/src/axis.ts
- charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
- charts-community-modules/ag-charts-community/src/chart/axis/groupedCategoryAxis.ts
- charts-community-modules/ag-charts-community/src/chart/chartAxis.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/polarSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/series.ts
- charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts
https://ag-grid.atlassian.net/browse/AG-7112
Adds `xName` + `yName` to title formatter params, restructures params to better accommodate this.
Bonus: Fix for Docker test execution response to `ctrl+c`.
> AG-7112 - Extend axis formatter params

- charts-community-modules/ag-charts-community/src/chart/agChartOptions.ts
- charts-community-modules/ag-charts-community/src/chart/agChartV2.ts
- charts-community-modules/ag-charts-community/src/chart/chart.test.ts
- charts-community-modules/ag-charts-community/src/chart/mapping/prepareSeries.test.ts
- charts-community-modules/ag-charts-community/src/chart/mapping/transforms.ts
- charts-enterprise-modules/ag-charts-enterprise/src/crosshair/crosshair.test.ts
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api-create-update/index.md
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-api/api.json
- grid-packages/ag-grid-docs/documentation/doc-pages/charts-bar-series/index.md
https://ag-grid.atlassian.net/browse/AG-6613
Attempts to give `bar` vs. `column` series types distinct 1st-class typings.
> AG-6613 - Split Bar and Column option typings.

- grid-packages/ag-grid-docs/documentation/update-algolia.js
https://ag-grid.atlassian.net/browse/AG-8715
Filters `enterprise: 'charts'` menu items from the Algolia records.
Bonus:
- Removes the need for an Algolia connection/client when `-d true` is specified.
- Adds more verbose `console.log` to allow tracing of visited pages.
> AG-8715 - Remove charts enterprise Algolia entries

- charts-community-modules/ag-charts-community/src/chart/data/processors.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-community-modules/ag-charts-community/src/scene/selection.ts
PR for https://ag-grid.atlassian.net/browse/AG-8471
This provides a new selection strategy if an optional `getDatumId()` function is provided. This allows the datum id to be tracked against the nodes created for them which in turn allows correct ordering and moving about when nodes are added and removed. If this is provided the series must handle the garbage collection itself by calling the `cleanup()` method on the selection, allowing the series time to animate the removed nodes out of view.
It adds a `diff` post-processor to the data model that can be given the previous data and provide back the list of keys that have been added, updated or removed. The animation handlers can then use this to move those nodes around.
Since a series `update()` method is called whenever a node is …
> AG-8471 Add bar/column animation of adding, removing and updating data

- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataController.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/series.ts
- charts-community-modules/ag-charts-community/src/module-support.ts
- charts-enterprise-modules/ag-charts-enterprise/src/heatmap/heatmapSeries.ts
- charts-enterprise-modules/ag-charts-enterprise/src/radar-line/radarLineSeries.ts
- charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts
https://ag-grid.atlassian.net/browse/AG-8507
Step 1 to start decoupling series definitions from processing, introducing an abstraction between data-processing and series implementations in the form of a `DataController`. Later this will allow us to merge multi-series processing whilst allowing each series to be independently rendered.
For this change, there are zero changes to the actual data processing, just a change in control-flow.
> AG-8507 - Add DataController and add to main processData() flow.

- charts-community-modules/ag-charts-community/src/chart/agChartV2.ts
- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
- charts-community-modules/ag-charts-community/src/chart/series/series.ts
- charts-community-modules/ag-charts-community/src/scene/scene.ts
- charts-community-modules/ag-charts-community/src/scene/sceneDebugOptions.ts
Improves the readability of console output as a result of setting `window.agChartsDebug = true`:
- Removes low-level rendering debug output.
- Adds class-name + method-name prefixes.
Adds `window.agChartsDebug = 'scene'` to re-enable mode details scene rendering logging.
Also adds a few more strategic log messages to allow control-flow tracing for major processing steps.
> Charts debug logging improvements.

- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-community-modules/ag-charts-community/src/util/render.ts
Fixes animation resize using stale `contextNodeData`.
Bonus: Cleaned-up resize handling.
> Fix chart animation resize handling

- charts-community-modules/ag-charts-community/src/axis.ts
- charts-community-modules/ag-charts-community/src/chart/cartesianChart.ts
- charts-community-modules/ag-charts-community/src/chart/chart.ts
- charts-community-modules/ag-charts-community/src/chart/chartAxis.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/chartEventManager.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/zoomManager.ts
- charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoom.ts
- charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoomAxisDragger.ts
- charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoomModule.ts
PR for https://ag-grid.atlassian.net/browse/AG-8552
The `ZoomManager` now tracks the zoom state for each axis separately. If using the existing api, i.e. `zoomManager.updateZoom()` it will update all the axis zooms to match, keeping the existing behaviour.
There are some further ux considerations to be discussed at a later date.
https://github.com/ag-grid/ag-grid/assets/3817697/9ae285e3-3e7e-4ac8-b40b-241784867d3a
> AG-8552 Add zoom axis dragging

- charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-enterprise-modules/ag-charts-enterprise/src/animation/animation.ts
- charts-enterprise-modules/ag-charts-enterprise/src/animation/animationModule.ts
- charts-enterprise-modules/ag-charts-enterprise/src/main.ts
- charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts
PR for https://ag-grid.atlassian.net/browse/AG-8561
This only adds a basic version of the `animation.duration` option for the total duration, mostly for QA purposes.
> AG-8561 Add animation.duration option

- charts-community-modules/ag-charts-community/src/chart/data/__snapshots__/dataModel.test.ts.snap
- charts-community-modules/ag-charts-community/src/chart/data/aggregateFunctions.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataController.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.test.ts
- charts-community-modules/ag-charts-community/src/chart/data/dataModel.ts
- charts-community-modules/ag-charts-community/src/chart/data/processors.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/areaSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/histogramSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/lineSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/scatterSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/hierarchy/treemapSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/polar/pieSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/series.ts
- charts-community-modules/ag-charts-community/src/chart/test/examples.ts
- charts-enterprise-modules/ag-charts-enterprise/src/heatmap/heatmapSeries.ts
- charts-enterprise-modules/ag-charts-enterprise/src/polar-series/radar-line/radarLineSeries.ts
- charts-enterprise-modules/ag-charts-enterprise/src/waterfall/waterfallSeries.ts
https://ag-grid.atlassian.net/browse/AG-7933
Implements merging of all series-specified `DataModel` `PropertyDefinition[]` so all processing is performed by the minimum number of `DataModel` instances.
Some things to note:
- `scope` has been introduced as an additional concept, which alongside `id` allows identification of which series originated a `PropertyDefinition` after reduction (and its subsequent output values in `ProcessedData`).
- Validation state is tracked per `scope`, and if there are mismatches in the set of valid rows per `scope` there is a final step to split results appropriately.
- `ProcessedData` no longer contains property->index information, since there is no longer a trivial mapping - `DataModel` exposes methods to allow indexes to be obtained in a correct manner. …
> AG-7933 - Implement DataModel reduction/merging.

- charts-community-modules/ag-charts-community/src/chart/interaction/zoomManager.ts
- charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoom.ts
- charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoomPanner.ts
PR for https://ag-grid.atlassian.net/browse/AG-8552
This changes zoom panning so that it will pan each series together such that they stay at the same relative positions to each other. But then if one series reaches the edge of it’s axis' domain, it will then stop while the others continue to move. Sliding over each other.
Previously it would reset the zoom of all the axes to match the last axis in the array.
https://github.com/ag-grid/ag-grid/assets/3817697/8b43a253-b437-4b21-9bb8-d888bcea2b08
> AG-8552 Change zoom panning to pan each axis separately

- charts-community-modules/ag-charts-community/src/chart/interaction/chartEventManager.ts
- charts-community-modules/ag-charts-community/src/chart/legend.ts
- charts-community-modules/ag-charts-community/src/chart/legendDatum.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/cartesianSeries.ts
- charts-community-modules/ag-charts-community/src/chart/series/series.ts
- charts-community-modules/ag-charts-community/src/chart/series/seriesLayerManager.ts
https://ag-grid.atlassian.net/browse/AG-7933
Fixes:
- Some more subtle z-index issues - series highlight is now kept at the same depth as the series content, so series obscured by other series also have their highlight obscured.
- `legendItemName` handling now works correctly for `BarSeries`.
> AG-7933 - More z-index fixes - keep highlight with series layer.

- charts-community-modules/ag-charts-community/src/chart/interaction/tooltipManager.ts
- charts-community-modules/ag-charts-community/src/chart/tooltip/tooltip.ts
- charts-enterprise-modules/ag-charts-enterprise/src/zoom/zoom.ts
PR for https://ag-grid.atlassian.net/browse/AG-3479
This reverts https://github.com/ag-grid/ag-grid/commit/a75f7b95ac7ce5f378b0392c985b59d0ef5fe12c from https://ag-grid.atlassian.net/browse/RTI-1465
That change broke a couple of things that rely on overriding the tooltip with an empty instance to hide it. With the intention of using `removeTooltip()` to remove that instance from the stack. Namely zoom and context menu.
> AG-3479 Zoom panning fixes

- charts-community-modules/ag-charts-community/src/axis.ts
- charts-community-modules/ag-charts-community/src/chart/interaction/animationManager.ts
- charts-community-modules/ag-charts-community/src/chart/series/cartesian/barSeries.ts
PR for https://ag-grid.atlassian.net/browse/AG-8471
With the previous solution, bars after the first would have their animation cancelled. This solution creates animation throttle groups that signal that these animations should not throttle each other.
Using a `throttleGroup` in combination with a `throttleId` allows batches of animations to run normally but throttle later batches.
So in this example, each time the update animation is triggered a new `throttleGroup` is created for the whole datum selection, but the series always shared a single `throttleId` across all animations.
https://github.com/ag-grid/ag-grid/assets/3817697/4b617c67-8bff-4899-94e2-bbbf3942762f
> AG-8471 Add animation throttling to bar updates

- grid-packages/ag-grid-docs/documentation/src/components/footer/footer-items.json
> Fix typo in footer

- grid-community-modules/core/src/ts/gridBodyComp/rowContainer/rowContainerCtrl.ts
- grid-community-modules/core/src/ts/rendering/row/rowCtrl.ts
- grid-community-modules/react/src/reactUi/cells/cellComp.tsx
- grid-community-modules/react/src/reactUi/rows/rowComp.tsx
- grid-community-modules/react/src/reactUi/rows/rowContainerComp.tsx
- grid-community-modules/react/src/reactUi/utils.tsx
- grid-packages/ag-grid-react/src/reactUi/rows/rowComp.tsx
- grid-packages/ag-grid-react/src/reactUi/rows/rowContainerComp.tsx
- grid-packages/ag-grid-react/src/reactUi/utils.tsx
flushSync enables us to avoid issues with React batching too many slow cell renderers together which block the main thread. Using `flushSync` forces per row rendering and enables it to be interrupted for scrolling.
> AG-8873 Return to flush sync

- grid-community-modules/core/src/ts/rendering/cell/cellComp.ts
- grid-community-modules/core/src/ts/rendering/row/rowComp.ts
- grid-community-modules/core/src/ts/rendering/row/rowCtrl.ts
For Cells and Rows it is quicker for us to build the simple dom elements as opposed to re-using the general approach of providing the string value and setting this to innerHTML. As these are done a lot it is worth switching to manual creation for the speed boost.
Before the change rendering a grid with a rowBuffer of 400 to force more rendering:
After this change
> AG-10140 Render Performance

- grid-community-modules/core/src/ts/rendering/cell/cellComp.ts
- grid-community-modules/core/src/ts/rendering/row/rowComp.ts
There are some significant performance gains with these changes.
Manually creating the cell and row divs are safe changes so they should definitely land. Done in https://github.com/ag-grid/ag-grid/commit/f7165844ba97d253f7819b75f442d717005c0c37
The second change on how we render standard cells will need more validation and checks but can give a big performance gain.
> Reduce use of innerHTML

- grid-packages/ag-grid-docs/documentation/src/components/release-notes/Collapsible.tsx
- grid-packages/ag-grid-docs/documentation/src/design-system/elements/_button.scss
- grid-packages/ag-grid-docs/documentation/src/design-system/modules/Collapsible.module.scss
- grid-packages/ag-grid-docs/documentation/src/design-system/style-guide/Buttons.tsx
- grid-packages/ag-grid-docs/documentation/src/design-system/style-guide/StyleGuide.module.scss
Fix changelog versions dropdown not being clickable
* Add aria-disabled styles to design system 
* `aria-disabled` is useful if you want the styles of a disabled button, but still want pointer events to continue working eg, if the button contains other interactive elements.
* Fix changelog versions drop down not being clickable 
* Use `aria-disabled` instead of `disabled` so that pointer events are still passed through
* Clean up Collapsible button `color` and `background-color` to use design system buttons more
> AG-9939 - Fix changelog versions dropdown

- grid-community-modules/angular/package.json
- grid-community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.spec.ts
- grid-community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- grid-community-modules/angular/projects/ag-grid-angular/src/lib/angularFrameworkComponentWrapper.ts
- grid-community-modules/angular/projects/ag-grid-angular/src/lib/angularFrameworkOverrides.ts
- grid-community-modules/core/src/ts/entities/column.ts
- grid-community-modules/core/src/ts/entities/rowNode.ts
- grid-community-modules/core/src/ts/eventService.ts
- grid-community-modules/core/src/ts/gridOptionsService.ts
- grid-community-modules/core/src/ts/interfaces/iFrameworkOverrides.ts
- grid-community-modules/core/src/ts/misc/apiEventService.ts
- grid-community-modules/core/src/ts/misc/frameworkEventListenerService.ts
- grid-community-modules/core/src/ts/vanillaFrameworkOverrides.ts
- grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.spec.ts
- grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/angularFrameworkComponentWrapper.ts
- grid-packages/ag-grid-angular/projects/ag-grid-angular/src/lib/angularFrameworkOverrides.ts
Main concept is to run AG Grid internals outside of Angular Zone to prevent the grid from triggering application Change Detection cycles.
We need to ensure that user provide event handlers are run inside Angular Zone to enable users to update their templates from with event callbacks.
However, grid configuration callbacks, although running code defined in users applications should run outside of Zone as these should only be used to configure the grid and not update templates.
For event listeners registered via, gridApi, row node or column these will maintain the Zone status at registration. So if an event handler is registered within the Zone then the event handler itself will run within the Zone. However, if the event handler is registered outside the Zone then the event handler itself …
> AG-10010 Angular CD avoidance

- grid-packages/ag-grid-docs/documentation/doc-pages/themes/index.md
The code example says `ag-theme-quartz` but the paragraph above says "Alpine".
"~Alpine~" -> "Quartz"
> Fix typo in themes docs page

- documentation/ag-grid-docs/src/content/docs/getting-started/_examples/custom-quartz-theme/index.html
- documentation/ag-grid-docs/src/content/docs/getting-started/_examples/custom-quartz-theme/main.ts
- documentation/ag-grid-docs/src/content/docs/getting-started/_examples/custom-quartz-theme/styles.css
- documentation/ag-grid-docs/src/content/docs/getting-started/index.mdoc
**Changes**
- Removed Figma image (now uses DS button)
- Moved theme grid into tab switcher
- Uses real example for theme customisation
> AG-10689 Quick start style tweaks

- documentation/ag-grid-docs/src/content/docs/integrated-charts-chart-types/_examples/specialized/main.ts
- enterprise-modules/charts/src/charts/chartComp/model/chartDataModel.ts
This ensures that the selected chart model cell range is reset when the chart cell range is updated when switching between chart types
> RTI-2030 Fix specialized chart example

- documentation/ag-grid-docs/src/content/docs/integrated-charts-chart-types/_examples/specialized/main.ts
- enterprise-modules/charts/src/charts/chartComp/model/chartDataModel.ts
This ensures that the selected chart model cell range is reset when the chart cell range is updated when switching between chart types
> RTI-2030 Fix specialized chart example (#7757)

- documentation/ag-grid-docs/src/content/docs/integrated-charts-application-created/_examples/application-created-charts/exampleConfig.json
- documentation/ag-grid-docs/src/content/docs/integrated-charts-application-created/index.mdoc
This reverts commit 9ab87ddb78912c2e4948dee276838becc3a77f0a.
While the JS output was generated correctly, the example does not work when other frameworks are selected.
> Revert "RTI-2018 Enable JS output for Application Created Charts example (#7765)"

- documentation/ag-grid-docs/src/components/quotes/Quotes.tsx
- documentation/ag-grid-docs/src/content/footer/data.json
- documentation/ag-grid-docs/src/content/versions/ag-grid-versions.json
- documentation/ag-grid-docs/src/design-system/_typography.scss
- documentation/ag-grid-docs/src/design-system/modules/DocsArchive.module.scss
- documentation/ag-grid-docs/src/pages/documentation-archive.astro
- documentation/ag-grid-docs/src/pages/whats-new.astro
Create a new "Documentation Archive" page. Replaces `ag-grid.com/archive/` in the footer however `ag-grid.com/archive/` will still be accessible. 
Also includes a small refactor of typographic CSS classes.
> Ag 11158 documentation archive

- documentation/ag-grid-docs/src/components/reference-documentation/ApiDocumentation.astro
- documentation/ag-grid-docs/src/components/reference-documentation/ApiDocumentationWithQuery.tsx
- documentation/ag-grid-docs/src/components/reference-documentation/InterfaceDocumentation.astro
- documentation/ag-grid-docs/src/components/reference-documentation/InterfaceDocumentationWithQuery.tsx
- documentation/ag-grid-docs/src/components/reference-documentation/ReferenceDocumentation.tsx
- documentation/ag-grid-docs/src/utils/client/fetchExtraFile.ts
by fetching resolved interfaces instead of injecting onto page
Get interfaces and code interfaces on client side instead of injecting it from the astro file into the react component. This caused the html to be very large.
Also remove unused `pageName` prop.
On charts: https://github.com/ag-grid/ag-charts/pull/1564
> AG-11304 - Reduce HTML page size

- community-modules/core/src/entities/rowNode.ts
- community-modules/core/src/selectionService.ts
- enterprise-modules/row-grouping/src/rowGrouping/groupStage.ts
- enterprise-modules/row-grouping/src/rowGrouping/pivotStage.ts
See https://ag-grid.atlassian.net/browse/AG-11658
TLDR: We couldn't rely on `RowNode.group` for tree data because it didn't get set for rows with user data. This flag was being relied on to determine the selection for group nodes.
- Set the `node.group = true` in [GroupStage.addToParent](https://github.com/ag-grid/ag-grid/blob/86ca65867280595de7f21fb94d8c14dd618aa3c7/enterprise-modules/row-grouping/src/rowGrouping/groupStage.ts#L418) to make value of `group` consistent between tree data and normal row grouping.
- Don't remove an empty group node if using tree data and the node has associated tree data, simply mark the `.group` field `false`.
- Replace what I assume is an outdated reference to `calculatedSelectedForAllGroupNodes`
- A little bit of tidying
The original PR description is …
> AG-11658 Deselection of indeterminate row with tree data

- community-modules/core/src/cellNavigationService.ts
- community-modules/core/src/entities/rowPositionUtils.ts
- community-modules/core/src/gridBodyComp/rowContainer/rowContainerEventsFeature.ts
- community-modules/core/src/pinnedRowModel/pinnedRowModel.ts
- community-modules/core/src/rendering/rowRenderer.ts
See https://ag-grid.atlassian.net/browse/AG-7026
- Call `getRowId` if it's defined when setting the `RowNode.id` of pinned rows in the `pinnedRowModel`
- I don't think we ever rely on pinned rows having a specific prefix, so I think this is a safe change.
- Add recycling logic to refresh checks in `RowRenderer` specifically for pinned rows. This addresses TC2 in the issue
- Tidying:
- Renames `PinnedRowModel.getPinned[Top|Bottom]RowData` to `PinnedRowModel.getPinned[Top|Bottom]RowNodes` to better reflect the signature
- Removes some type annotations that are inferred
This should probably be merged after #8022 and also then be updated to use the new `getRowIdCallback` method that it introduces.
- What is the reason for `RowCtrl.rowId` being an HTML escaped version of `RowNode.id`?
> AG-7026 Allow getRowId to be called for pinned rows

- external/ag-website-shared/src/utils/cleanIndexHtml.ts
The existing regex was matching any script tags immediately before the vite script tag so would also remove anything included under "extras", for example, `alasql`, which in turn breaks the SSRM plunkr examples.
This code path is only active is dev mode.
> Fix regex to avoid matching multiple script tags

- community-modules/client-side-row-model/src/clientSideRowModel/clientSideNodeManager.ts
- community-modules/client-side-row-model/src/clientSideRowModel/immutableService.ts
- community-modules/core/src/entities/rowNode.ts
- community-modules/core/src/gridBodyComp/rowDragFeature.ts
- community-modules/core/src/gridOptionsService.ts
- community-modules/core/src/pinnedRowModel/pinnedRowModel.ts
- community-modules/infinite-row-model/src/infiniteRowModel/infiniteRowModel.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/stores/fullStore.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/stores/lazy/lazyCache.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/stores/lazy/lazyStore.ts
See https://ag-grid.atlassian.net/browse/AG-9259
- Introduce `GridOptionsService.getRowIdCallback` as a wrapper for `GridOptionsService.getCallback('getRowId')` which takes care of the logging and coercion of the ID to string
- Replace all calls to `.getCallback('getRowId')`
- **WARNING**: There's a behaviour change in this PR which IMO is a bugfix. Previously in [`RowNode.setId`](https://github.com/ag-grid/ag-grid/pull/8022/files#diff-d0c64a7a3232b7f4f9890f4a725b899809107fcb368720f1278839d5a6968f85L418-L421) we would only cast to string if the ID returned from the callback was non-`null`. We now cast to string whenever the return type is not "string". `RowNode.id` is typed as `string | undefined` anyway, so we shouldn't allow it to be `null`. The only thing this might break is if a user …
> AG-9259 Log a warning when getRowId doesn't return a string

- community-modules/core/src/entities/colDef.ts
- community-modules/core/src/gridOptionsService.ts
- community-modules/core/src/interfaces/iCommon.ts
- community-modules/core/src/propertyKeys.ts
- community-modules/core/src/validation/rules/colDefValidations.ts
- community-modules/core/src/validation/validationService.ts
- documentation/ag-grid-docs/src/content/api-documentation/column-properties/properties.json
- documentation/ag-grid-docs/src/content/docs/context/index.mdoc
- plugins/ag-grid-generate-example-files/gridOptionsTypes/_gridOptions_Types.json
- plugins/ag-grid-generate-example-files/src/executors/generate/generator/transformation-scripts/react-utils.ts
Background:
There is already a `context` property of type any, see https://localhost:4610/react-data-grid/context
Users have requested a context property also per column.
Changes:
- Adds an additional property `context` to AbstractColDef (and consequently to ColDef and ColGroupDef) of type any that allows to assign and passing custom data to to callbacks.
- Augment the error message in such a way it includes a reference to the "context" property to the valid properties validator so users know what is the proper way to pass custom data to the grid definition or columns and column groups definitions.
- Fix the documentation by adding the context property to colDef and colGroupDef
- Merge FUNCTIONAL_PROPERTIES and CALLBACK_PROPERTIES in FUNCTION_PROPERTIES for the column definitions, this is …
> [AG-11710] Add a context property to column definitions to support custom meta-data on the column-level

- community-modules/core/src/selection/selectionService.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/groupSelectsChildrenStrategy.ts
My initial PR (https://github.com/ag-grid/ag-grid/pull/8055) incorrectly preserved the `.sort` call (see [L163](https://github.com/ag-grid/ag-grid/pull/8055/files#diff-f227c6434da8ec06ad2747ca7b44c53b072b5f3fa36218829f68fde0756b52e1L163) vs [L221](https://github.com/ag-grid/ag-grid/pull/8055/files#diff-f227c6434da8ec06ad2747ca7b44c53b072b5f3fa36218829f68fde0756b52e1R221))
> AG-11087 Fix(QA) shift selecting on a collapsed group node

- community-modules/core/src/rendering/cellRenderers/skeletonCellRenderer.ts
Adds variation to the skeleton cell widths to avoid them all looking uniform.
> AG-11444 Add "randomisation" to skeleton widths

- enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/defaultStrategy.ts
As far as I can tell this is was only happening when using the default selection strategy in SSRM since the group-selects-children strategy uses the `RowNode` state as its source of truth.
I've also added a guard against the same bug in the case of selecting a single node, although this shouldn't be possible to do via the UI (it might be possible via API calls).
Also the selection context probably should be reset when trying to select a non-selectable node (or in any other case where a selection is rejected).
> AG-11843 Prevent tracking non-selectable nodes in selected state

- community-modules/core/src/columns/funcColsService.ts
See https://ag-grid.atlassian.net/browse/AG-11881
The use of `bind` defeats type checking, remove in favour of anonymous functions
> AG-11881 Set source of column events correctly

- documentation/ag-grid-docs/src/content/docs/server-side-model-selection/index.mdoc
It's been pointed out that the description of the snippet was actually inconsistent with the example.
> AG-11863 Make example description consistent with example

- community-modules/client-side-row-model/src/clientSideRowModel/clientSideRowModel.ts
- community-modules/core/src/interfaces/iRowModel.ts
- community-modules/core/src/selection/rowRangeSelectionContext.ts
- community-modules/core/src/selection/selectionService.ts
- community-modules/infinite-row-model/src/infiniteRowModel/infiniteCache.ts
- community-modules/infinite-row-model/src/infiniteRowModel/infiniteRowModel.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/serverSideRowModel.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/serverSideRowRangeSelectionContext.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/defaultStrategy.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/groupSelectsChildrenStrategy.ts
- enterprise-modules/viewport-row-model/src/viewportRowModel/viewportRowModel.ts
See https://ag-grid.atlassian.net/browse/AG-11941
- The issue was that the selection context was allowing `null` arguments to be passed to `getNodesInRangeForSelection`, which then began the range from the first row.
- `getNodesInRangeForSelection` no longer accepts `null` arguments for either of its parameters. 
- Code dealing with not knowing the limits of a range now lives in `RowRangeSelectionContext` and `ServerSideRowRangeSelectionContext`
- Implementations of `ISelectionService.selectAllRowNodes` and `ISelectionService.deselectAllRowNodes` should set the appropriate selection context.
- For `selectAllRowNodes`:
- In CSRM we set the start and end of the selection context to the first and last nodes of the selection
- In SSRM, this isn't really possible, since we don't store selected …
> AG-11941 Fix regression in row range selection

- community-modules/core/src/selection/rowRangeSelectionContext.ts
- community-modules/core/src/selection/selectionService.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/serverSideRowRangeSelectionContext.ts
- enterprise-modules/server-side-row-model/src/serverSideRowModel/services/selection/strategies/groupSelectsChildrenStrategy.ts
See https://ag-grid.atlassian.net/browse/AG-11941
The issue is that the root of the selection context (i.e. the call to `.setRoot(...)`) was only being set during single selection mode. So if a user held SHIFT for the first selection, it was never initialised. This PR explicitly handles the initial case inside the `RowRangeSelectionContext` and `ServerSideRowRangeSelectionContext`.
We also need some additional code to handle the row-grouping case where an initial SHIFT-click on a row group node should properly select its children.
> AG-11941 Set selection root on first selection when in range selection

- community-modules/core/src/rendering/overlays/overlayService.ts
- community-modules/core/src/rendering/overlays/overlayWrapperComponent.ts
- testing/behavioural/src/overlays/overlays-react-unmount.test.tsx
- testing/behavioural/src/overlays/overlays-state.test.ts
- change the logic of suppressLoadingOverlay and loading=true so that loading=true overrides it
- change the behavioural unit tests, as the behaviour changed
- handle the colDef being set after rowData better, centralising the logic
- handle better the initial loading better so it is not possible for the loading screen to show twice if loading=undefined
- avoid double rendering if the state didn't change - maintain the old behaviour instead if "legacy" show and hide is called
- removed unused warnOnce import
- simplify logic
> AG-5497 [Overlays] the priority of suppressLoadingOverlay should be lower than setting loading=true

- community-modules/core/src/widgets/component.ts
- enterprise-modules/core/src/widgets/agMenuPanel.ts
The AgMenuPanel wraps other components and the component logic then saw data-refs on the child components and noticed that these were not present on the wrapping AgMenuPanel, hence the warning.
Added suppression of that check to enable this use case to work with no warnings.
> RTI-2126 Enable suppression of data-ref warning

- community-modules/core/src/rendering/overlays/overlayService.ts
- testing/behavioural/src/overlays/overlays-infinite-scrolling.test.tsx
With infinite row models, no-rows should not show, but instead with the new changing on overlays state management it was appearing over the rows.
- Fix the no-rows logic in overlayService
- Add unit tests for infinite rows and loading and no-rows
Before the fix: 
After the fix: ![image](https://github.com/ag-grid/ag-grid/assets/6913178/1ee0be1b-9847-4cf4-8b7f-b7f689405f5c)
> RTI-2177 [regression] fix no-rows showing with infinite row model, fix tests

- community-modules/core/src/rendering/overlays/overlayService.ts
- testing/behavioural/src/overlays/overlays-infinite-scrolling.test.tsx
With infinite row models, no-rows should not show, but instead with the new changing on overlays state management it was appearing over the rows.
- Fix the no-rows logic in overlayService
- Add unit tests for infinite rows and loading and no-rows
Before the fix: 
After the fix: ![image](https://github.com/ag-grid/ag-grid/assets/6913178/1ee0be1b-9847-4cf4-8b7f-b7f689405f5c)
> RTI-2177 [regression] fix no-rows showing with infinite row model, fix tests 

- community-modules/core/src/gridOptionsService.ts
Pass items as individual arguments to the log function so that they are not forced into strings and can be passed onto console.log as raw values.
> RTI-2202 Fix debug logging output

- documentation/ag-grid-docs/src/content/docs/cell-editors/_examples/component-editor-2/simpleTextEditor.component_angular.ts
- documentation/ag-grid-docs/src/content/docs/cell-editors/_examples/get-editor-instance/provided/modules/angular/mySimple-editor.component.ts
Fix to make editing cells works in angular examples in angular-data-grid/cell-editors/
changes:
- In both angular edit components `imports: [FormsModule],` was missing, and `[(ngModel)]` should be used instead of value=
Tested all angular examples in the page.
> RTI-2145 angular custom cell editor example broken

- community-modules/core/src/rendering/features/stickyRowFeature.ts
See https://ag-grid.atlassian.net/browse/AG-11844
Prevents group nodes from being marked as `sticky` when being scrolled into the bottom of viewport. They should never stick to the bottom of the viewport and this was also preventing them being navigated to with the keyboard.
> AG-11844 Prevent group nodes from sticking to the bottom of the viewport

- plugins/ag-grid-generate-code-reference-files/src/executors/generate/generate-code-reference-files.ts
The implementation of getGridApi in docs generator was not recursive and was not processing all base interfaces.
The previous change merged in https://github.com/ag-grid/ag-grid/pull/8280 introduced a regression as it introduces a new base interface, so all core APIs were not included in the documentation generated json.
This fixes the issue by making getGridApi recursive
> AG-11965 - fix regression in code reference files generate

- documentation/ag-grid-docs/package.json
- documentation/ag-grid-docs/src/components/reference-documentation/ApiDocumentationWithQuery.tsx
- documentation/ag-grid-docs/src/components/reference-documentation/InterfaceDocumentationWithQuery.tsx
- documentation/ag-grid-docs/src/components/reference-documentation/useResolvedInterfaces.ts
- documentation/ag-grid-docs/src/features/docs/components/DocsExampleRunner.tsx
- documentation/ag-grid-docs/src/stores/queryClientStore.ts
- yarn.lock
* Upgrade react query to @tanstack/react-query v5
* Extract queryClient to nanostore atom so it can be reused
* Extract api and interface fetching and reuse them between fetches
> AG-12030 - Upgrade react query

- community-modules/core/src/focusService.ts
- community-modules/core/src/gridComp/gridCtrl.ts
- community-modules/core/src/rendering/overlays/overlayService.ts
- community-modules/core/src/rendering/overlays/overlayWrapperComponent.ts
- documentation/ag-grid-docs/src/content/docs/overlays/_examples/loading-overlay/main.ts
- add a new utility method isGridFocused in FocusService that returns true if an element in the grid has focus
- change focusable containers logic in grid controller, so that the exclusive loading overlays are the only focusable thing, and the non exclusive no-rows overlay is focusable
- change the overlay wrapper component so when the exclusive loading overlay is visible, and the grid was focused, the focus goes to the loading overlay
- change the overlay wrapper component so that when the exclusive loading overlay is closed, the focus goes back to the previous focused element, if still exists
> AG-11982 allow overlays to be focusable and prevent header cells from focus when using loading overlay

- community-modules/client-side-row-model/src/clientSideRowModel/immutableService.ts
- community-modules/core/src/cellNavigationService.ts
- community-modules/core/src/entities/rowNode.ts
- community-modules/core/src/entities/rowPositionUtils.ts
- community-modules/core/src/gridBodyComp/rowContainer/rowContainerEventsFeature.ts
- community-modules/core/src/pinnedRowModel/pinnedRowModel.ts
- community-modules/core/src/rendering/rowRenderer.ts
- community-modules/csv-export/src/csvExport/gridSerializer.ts
- testing/behavioural/src/rows/pinned-rows.test.ts
See https://ag-grid.atlassian.net/browse/AG-12193
There was previously no update logic for pinned rows, which means they were either re-created entirely (if there was no matching ID found) or they were left intact (without updating associated row data).
This now adds update logic analogous to that in `ClientSideRowModel`, but a bit simpler.
> AG-12193 Correctly update Pinned rows on data change

- community-modules/core/src/rendering/overlays/overlayService.ts
- testing/behavioural/src/overlays/overlays-state.test.ts
The initial loading state was not being cleared if row data was set via `applyTransaction` instead of via the `rowData` property. 
The fix adds a new event handler that is only fired the first time that row data is actually set, no matter the method. We use this to clear the initial loading overlay.
> AG-12327 transactions clear initial loading

- community-modules/core/src/rendering/columnAnimationService.ts
There was a race condition in React that meant that a column animation could schedule a run `next` function after these had been cleared, but before the `active` flag had been set to false when the `later` funcs where run.
So now we have a `activeNext` flag which can be used to prevent queuing next functions after they have already been flushed as part of the finish step. 
This means that the previously dropped animations will be run immediately.
> AG-11372 Ensure columnAnimations always flushed

- community-modules/core/src/rendering/overlays/loadingOverlayComponent.ts
- community-modules/core/src/rendering/overlays/noRowsOverlayComponent.ts
This change avoids the grid crashing when trying to create a dom element for an empty string.
Now empty strings are treated the same as providing undefined and so the grid displays the default loading / no rows templates.
> AG-12359 handle empty string input overlayLoadingTemplate / overlayNoRowsTemplate

- community-modules/core/src/rendering/cell/cellComp.ts
- community-modules/core/src/rendering/cell/cellCtrl.ts
- community-modules/core/src/rendering/row/rowComp.ts
- community-modules/core/src/rendering/row/rowCtrl.ts
- community-modules/core/src/rendering/rowRenderer.ts
- community-modules/core/src/utils/dom.ts
- community-modules/react/src/reactUi/cells/cellComp.tsx
- community-modules/react/src/reactUi/rows/rowComp.tsx
- packages/ag-grid-react/src/reactUi/cells/cellComp.tsx
- packages/ag-grid-react/src/reactUi/rows/rowComp.tsx
The aim is to update the `tabIndex` property for cells and fullwidth rows without triggering a React rerender. 
This is achieved by moving the management of the `tabIndex` attribute into the ctrls and out of the components.
> AG-11923 suppressCellFocus updates

- enterprise-modules/row-grouping/src/rowGrouping/groupStage/treeStrategy/treeStrategy.ts
This removes a performance degradation and a duplicate key warning that solves also partially the problem of partial updates breaking the tree structure and slowing down the operations on the tree
> AG-12198 (partial solution) remove duplicate key warning

- community-modules/angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
- community-modules/core/src/entities/gridOptions.ts
- documentation/ag-grid-docs/src/content/docs/data-update-high-frequency/_examples/flush-transactions/main.ts
- packages/ag-grid-angular/projects/ag-grid-angular/src/lib/ag-grid-angular.component.ts
The use of a promise for GridReady meant that event got fired async even though the grid was ready for it to be fired. Swapping the code to hold all events until ngAfterViewInit has been run so that we maintain a consistent ordering of events.
> AG-12433 Angular Consistent event firing order

- community-modules/core/src/entities/agColumn.ts
Tree groups should be editable by default.
The check for editable tree group was not correct.
It seems that in version 32 the "group" field of the row is now correct for tree row groups, but it wasn't before
> AG-12283 Cannot edit tree data group rows without setting `enableGroupEdit`

- community-modules/core/src/entities/gridOptions.ts
- community-modules/core/src/misc/resizeObserverService.ts
- community-modules/core/src/validation/rules/gridOptionsValidations.ts
- documentation/ag-grid-docs/src/content/api-documentation/grid-options/properties.json
This PR:
1. Removes the ResizeObserver polyfill
2. Deprecates gridOptions.suppressBrowserResizeObserver and turns it into a no-op
> AG-12464 remove ResizeObserver polyfill

- testing/behavioural/src/columns/column-test-utils.ts
- testing/behavioural/src/columns/order/auto-group-cols.test.ts
- testing/behavioural/src/columns/order/column-order.test.ts
- testing/behavioural/src/columns/order/lock-position.test.ts
- testing/behavioural/src/columns/order/pivot.test.ts
In one of the previous iteration, I added a TestGridsManager class that does:
- properly manages creation and destruction of grids and their html element
- allow to access the html element where a grid was created into
- do not print the license error message
In this PR I propose the use of TestGridsManager also for the new column tests, and a console.warn spy to avoid printing expected warnings to the console
In this way running the tests leaves a cleaner output, that is easier to debug, and, we are more consistent
> AG-12744 refactor new tests to use TestGridsManager and to not print warnings and license errors in the console

- community-modules/react/src/reactUi/customComp/customWrapperComp.tsx
- community-modules/react/src/shared/customComp/customComponentWrapper.ts
- community-modules/react/src/shared/reactComponent.ts
- packages/ag-grid-react/src/reactUi/customComp/customWrapperComp.tsx
- packages/ag-grid-react/src/shared/customComp/customComponentWrapper.ts
- testing/behavioural/vitest.config.js
Running the behavioural tests with source code, a new warning surfaced:
```
Warning: A props object containing a "key" prop is being spread into JSX:
let props = {key: someKey, api: ..., context: ..., ref: ..., reactContainer: ...};
<loadingOverlayComponent {...props} />
React keys must be passed directly to JSX without using spread:
let props = {api: ..., context: ..., ref: ..., reactContainer: ...};
<loadingOverlayComponent key={someKey} {...props} />
at CustomWrapperComp (ag-grid/community-modules/react/src/reactUi/customComp/customWrapperComp.tsx:8:11)
at div
at AgGridReactUi (ag-grid/community-modules/react/src/reactUi/agGridReactUi.tsx:44:40)
at AgGridReact (ag-grid/community-modules/react/src/agGridReact.tsx:10:5)
Warning: A props object containing a "key" prop is being spread into …
```
> AG-12747 separate key from props in custom component wrapper to avoid react 18 key spread warning

- .vscode/extensions.json
- testing/behavioural/vitest.config.js
…testsEnables vscode supports for vitest behavioural tests.
Add the recommended extension “vitest.explorer” for vscode,
fix the configuration so it loads properly also when not running via nx
> AG-12765 allow vscode integration with behavioural tests

- community-modules/client-side-row-model/src/clientSideRowModel/clientSideNodeManager.ts
- community-modules/client-side-row-model/src/clientSideRowModel/clientSideRowModel.ts
- community-modules/client-side-row-model/src/clientSideRowModel/immutableService.ts
Background:
To switch between "flat" (traditional) row data and the new hierarchidal row data with a "children" property, we want to try the approach to have two different implementations of ClientSideNodeManager and ImmutableService for hierarchical data.
At the moment, Immutable service just invokes directly some operations from the ClientSideNodeManager, and contains logic that seems to be more suited to be handled by the ClientSideRowModel.
In this refactoring PR, I moved the generation and execution of transactions outside of the ImmutableService into the ClientSideNodeManager and exposed it through the ClientSideRowModule.
In this way, when we implement the other ClientSideNodeManager for hierarchical data we do not need to worry to select the right immutable service instance, as …
> AG-12272 - step 1 - simplify the relationship between csrm and immutable service

- documentation/ag-grid-docs/src/content/docs/grouping-opening-groups/_examples/row-group-scroll/main.ts
- documentation/ag-grid-docs/src/content/docs/tree-data-opening-groups/_examples/row-group-scroll/main.ts
Steps to repro:
Open URL [JavaScript Grid: Tree Data - Expanding Groups | AG Grid](https://www.ag-grid.com/archive/32.2.0/javascript-data-grid/tree-data-opening-groups/#scrolling-child-rows-into-view) 
- Click to Expand Downloads
- Click to Collapse Downloads
** Actual:
function.ts:22 AG Grid: Invalid row index for ensureIndexVisible: 7
** Expected: 
Should be no warning
Counterintuitively, the event onRowGroupOpened is raised both on expand and unexpand, but we are not checking the event.expanded state when trying to select the right rowindex.
We should call ensureIndexVisible only if event.expanded is true in the example itself
> RTI-2313 scroll into view example logs warning

- documentation/ag-grid-docs/src/content/api-documentation/grid-api/api.json
- documentation/ag-grid-docs/src/content/api-documentation/grid-events/events.json
- documentation/ag-grid-docs/src/content/interface-documentation/integrated-charts-api-range-chart/chart-api.json
Description
Steps to repro:
Open 
- https://www.ag-grid.com/archive/32.2.0/javascript-data-grid/grid-api/#reference-selection-getCellRanges
- https://www.ag-grid.com/archive/32.2.0/javascript-data-grid/grid-api/#reference-selection-addCellRange
- https://www.ag-grid.com/archive/32.2.0/javascript-data-grid/grid-api/#reference-selection-clearCellSelection
See links in the description of these methods
Actual: Links are broken
Expected: Links point to the Selection API page instead where these methods are actually documented
Also:
searched and fixed all links to the old api reference section and fixed them
> RTI-2276 cell selection api docs methods links broken
